"""Mock data ouput for testing snapshots."""

from unittest import mock


def mock_extracted_json(_json_data=mock) -> list[dict]:  # noqa: ANN001
    """Json input for snapshot testing."""
    return [
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Review Kai's ADR on monitoring tool",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/178",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-03-05",
            "issue_closed_at": "2024-03-20",
            "issue_points": 1.0,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Prepare for roadmap planning session on 3/21",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/181",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-03-20",
            "issue_closed_at": "2024-03-22",
            "issue_points": 2.0,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Create doc with questions about content guide for Bloom",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/182",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-03-20",
            "issue_closed_at": "2024-03-22",
            "issue_points": 3.0,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Assist with adding relevancy score to search API",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/184",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-03-28",
            "issue_closed_at": "2024-04-05",
            "issue_points": None,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Assist with containerizing the analytics package",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/183",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-03-28",
            "issue_closed_at": "2024-04-05",
            "issue_points": None,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Plan deliverable spec drafting sessions for onsite",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/185",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-03-28",
            "issue_closed_at": "2024-04-05",
            "issue_points": None,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Add change log and implementation log to deliverable specs",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/186",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-04-05",
            "issue_closed_at": "2024-04-08",
            "issue_points": 2.0,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Create a Risk Register",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/188",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-04-09",
            "issue_closed_at": "2024-10-08",
            "issue_points": None,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "[Task]: Clean up issue templates",
            "issue_url": "https://github.com/HHS/simpler-grants-gov/issues/1774",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-04-18",
            "issue_closed_at": "2024-04-18",
            "issue_points": 1.0,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Deliverable spec reviews",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/192",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-04-24",
            "issue_closed_at": "2024-04-29",
            "issue_points": 2.0,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "[Internal Wiki] Make basic IA improvements",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/194",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-04-26",
            "issue_closed_at": "2024-10-08",
            "issue_points": None,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "[Internal Wiki] Audit current users and perms",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/193",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-04-26",
            "issue_closed_at": "2024-05-03",
            "issue_points": None,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Review current meeting list",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/196",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-04-26",
            "issue_closed_at": "2024-05-03",
            "issue_points": None,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Discuss Google Drive permissions with Nava",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/195",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-04-26",
            "issue_closed_at": "2024-09-17",
            "issue_points": None,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Review Github Sprint Reports",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/197",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-04-26",
            "issue_closed_at": "2024-10-08",
            "issue_points": None,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "SimplerNOFO FY25 specs and AoAs",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/198",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-04-29",
            "issue_closed_at": "2024-09-16",
            "issue_points": 3.0,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": """[Task]: Update close ticket linter to indicate
              is being performed by a bot""",
            "issue_url": "https://github.com/HHS/simpler-grants-gov/issues/1932",
            "issue_parent": None,
            "issue_type": "Task",
            "issue_is_closed": True,
            "issue_opened_at": "2024-05-06",
            "issue_closed_at": "2024-05-08",
            "issue_points": 1.0,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Create a guide for change request workflow",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/199",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-04-29",
            "issue_closed_at": "2024-09-16",
            "issue_points": 2.0,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "[Task]: Add environment variables file to analytics folder",
            "issue_url": "https://github.com/HHS/simpler-grants-gov/issues/1598",
            "issue_parent": None,
            "issue_type": None,
            "issue_is_closed": True,
            "issue_opened_at": "2024-04-02",
            "issue_closed_at": "2024-05-02",
            "issue_points": None,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": """Document process to access applicant
              and grantor test accounts for grants.gov""",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/204",
            "issue_parent": None,
            "issue_type": "Task",
            "issue_is_closed": False,
            "issue_opened_at": "2024-09-16",
            "issue_closed_at": None,
            "issue_points": None,
            "issue_status": "Todo",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "open",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": """Establish notification process for updates
              across grants.gov and simpler.grants.gov""",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/205",
            "issue_parent": None,
            "issue_type": "Task",
            "issue_is_closed": False,
            "issue_opened_at": "2024-09-16",
            "issue_closed_at": None,
            "issue_points": 8.0,
            "issue_status": "Todo",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "open",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Confirm HHS Onboarding Requirements",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/208",
            "issue_parent": "https://github.com/HHS/grants-product-and-delivery/issues/295",
            "issue_type": "Task",
            "issue_is_closed": True,
            "issue_opened_at": "2024-09-19",
            "issue_closed_at": "2024-10-09",
            "issue_points": None,
            "issue_status": "Done",
            "sprint_id": "aa857941",
            "sprint_name": "Sprint 1.1",
            "sprint_start": "2024-10-02",
            "sprint_length": 14.0,
            "sprint_end": "2024-10-16",
            "quad_id": "93412e1c",
            "quad_name": "Quad 1.1",
            "quad_start": "2024-09-09",
            "quad_length": 122.0,
            "quad_end": "2025-01-09",
            "deliverable_pillar": "SimplerDelivery",
            "deliverable_url": "https://github.com/HHS/simpler-grants-gov/issues/2357",
            "deliverable_title": "Cross-program team health",
            "deliverable_status": "In Progress",
            "epic_url": "https://github.com/HHS/simpler-grants-gov/issues/2362",
            "epic_title": "[Team health] Host first onsite",
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Adjusting Specification Nomenclature ",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/242",
            "issue_parent": "https://github.com/HHS/grants-product-and-delivery/issues/285",
            "issue_type": "Task",
            "issue_is_closed": True,
            "issue_opened_at": "2024-09-20",
            "issue_closed_at": "2024-10-04",
            "issue_points": 3.0,
            "issue_status": "Done",
            "sprint_id": "aa857941",
            "sprint_name": "Sprint 1.1",
            "sprint_start": "2024-10-02",
            "sprint_length": 14.0,
            "sprint_end": "2024-10-16",
            "quad_id": "93412e1c",
            "quad_name": "Quad 1.1",
            "quad_start": "2024-09-09",
            "quad_length": 122.0,
            "quad_end": "2025-01-09",
            "deliverable_pillar": "SimplerDelivery",
            "deliverable_url": "https://github.com/HHS/simpler-grants-gov/issues/2356",
            "deliverable_title": "Cross-program product strategy (Quad 2)",
            "deliverable_status": "Done",
            "epic_url": "https://github.com/HHS/simpler-grants-gov/issues/2358",
            "epic_title": "[Product strategy] Roadmap and deliverables for Quad 1",
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Extract and transform GitHub delivery data",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/215",
            "issue_parent": "https://github.com/HHS/grants-product-and-delivery/issues/207",
            "issue_type": "Task",
            "issue_is_closed": True,
            "issue_opened_at": "2024-09-19",
            "issue_closed_at": "2024-10-01",
            "issue_points": 5.0,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": "93412e1c",
            "quad_name": "Quad 1.1",
            "quad_start": "2024-09-09",
            "quad_length": 122.0,
            "quad_end": "2025-01-09",
            "deliverable_pillar": "📊 SimplerReporting",
            "deliverable_url": "https://github.com/HHS/simpler-grants-gov/issues/2347",
            "deliverable_title": "Cross-program delivery metrics",
            "deliverable_status": "Done",
            "epic_url": "https://github.com/HHS/simpler-grants-gov/issues/2353",
            "epic_title": "[Delivery metrics] Prototype dashboard in Metabase",
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Consolidate GitHubs - Projects",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/210",
            "issue_parent": "https://github.com/HHS/grants-product-and-delivery/issues/285",
            "issue_type": "Task",
            "issue_is_closed": True,
            "issue_opened_at": "2024-09-19",
            "issue_closed_at": "2024-10-09",
            "issue_points": 5.0,
            "issue_status": "Done",
            "sprint_id": "aa857941",
            "sprint_name": "Sprint 1.1",
            "sprint_start": "2024-10-02",
            "sprint_length": 14.0,
            "sprint_end": "2024-10-16",
            "quad_id": "93412e1c",
            "quad_name": "Quad 1.1",
            "quad_start": "2024-09-09",
            "quad_length": 122.0,
            "quad_end": "2025-01-09",
            "deliverable_pillar": "SimplerDelivery",
            "deliverable_url": "https://github.com/HHS/simpler-grants-gov/issues/2356",
            "deliverable_title": "Cross-program product strategy (Quad 2)",
            "deliverable_status": "Done",
            "epic_url": "https://github.com/HHS/simpler-grants-gov/issues/2358",
            "epic_title": "[Product strategy] Roadmap and deliverables for Quad 1",
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Determine current availability of metrics needed to track KPIs",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/211",
            "issue_parent": None,
            "issue_type": "Task",
            "issue_is_closed": False,
            "issue_opened_at": "2024-09-19",
            "issue_closed_at": None,
            "issue_points": None,
            "issue_status": "Todo",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "open",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Reconcile updates made to existing Grants. gov site & DB",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/214",
            "issue_parent": None,
            "issue_type": "Task",
            "issue_is_closed": True,
            "issue_opened_at": "2024-09-19",
            "issue_closed_at": "2024-09-26",
            "issue_points": None,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Consolidate GitHubs - Repos",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/218",
            "issue_parent": None,
            "issue_type": "Task",
            "issue_is_closed": True,
            "issue_opened_at": "2024-09-20",
            "issue_closed_at": "2024-09-20",
            "issue_points": None,
            "issue_status": "Done",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "closed",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Get new team members onboarded ASAP",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/220",
            "issue_parent": None,
            "issue_type": "Task",
            "issue_is_closed": False,
            "issue_opened_at": "2024-09-20",
            "issue_closed_at": None,
            "issue_points": None,
            "issue_status": "In Progress",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "open",
        },
        {
            "project_owner": "HHS",
            "project_number": 17,
            "issue_title": "Revise KPIs based on updated Objectives",
            "issue_url": "https://github.com/HHS/grants-product-and-delivery/issues/222",
            "issue_parent": None,
            "issue_type": "Task",
            "issue_is_closed": False,
            "issue_opened_at": "2024-09-20",
            "issue_closed_at": None,
            "issue_points": None,
            "issue_status": "Todo",
            "sprint_id": None,
            "sprint_name": None,
            "sprint_start": None,
            "sprint_length": None,
            "sprint_end": None,
            "quad_id": None,
            "quad_name": None,
            "quad_start": None,
            "quad_length": None,
            "quad_end": None,
            "deliverable_pillar": None,
            "deliverable_url": None,
            "deliverable_title": None,
            "deliverable_status": None,
            "epic_url": None,
            "epic_title": None,
            "issue_state": "open",
        },
    ]
