services:
  grants-analytics:
    build:
      context: .
      target: dev
      args:
        - RUN_UID=${RUN_UID:-4000}
        - RUN_USER=${RUN_USER:-analytics}
    container_name: grants-analytics
    env_file: ./local.env
    volumes:
      - .:/analytics
      - ~/.ssh:/home/${RUN_USER:-analytics}/.ssh
    networks:
      - default
      - local_db

  grants-metabase:
    image: metabase/metabase:latest
    container_name: grants-metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3100:3000
    env_file: ./local.env


networks:
  local_db:
    # NOTE: This network is created by starting the shared DB
    # defined in /backend/docker-compose.db.yml
    external: true
    name: local_db