services:
  nextjs:
    container_name: next-dev
    platform: linux/amd64
    build:
      context: .
      target: dev
    env_file:
      - ./.env.development
      - ./.env.local
    environment:
      SESSION_SECRET: extraSecretSessionSecretValueSssh
      API_JWT_PUBLIC_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn+VBEtznw3VN/ChVXB2I
        t36IpXD9j/dfQNWPkIJ/42ZF3XsK0MjkExrH9CSdeTOxxPk2qINYOEuMW9nkUFRr
        1fQW/ztrvKtCIqEHKCJiVP2hxos+/mGcKyahdEIZ5+U0Hk3TE6MRCGN6WtXz5rlJ
        J9vIGLRrJ7HaxQBKzc+tIWMMbrmKkqMweHi1dZCs2iMMO+TCc6s48nUtzdLITwTN
        TgwWmkBykpoaG2d3sOUpLdod/UiGhvXNmeIvx6x6C7J/cH9eVQdyfdU5WMTtuYES
        Rdz/zR4uQR6WQ1H+ORWOr0VPe7UpwXWaHp8LAkhQIZ9LNRg6fph30pL0TYNjfi2v
        8QIDAQAB
        -----END PUBLIC KEY-----
      API_URL: http://grants-api:8080
      LOCAL_DEV: "true"
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - default
      - api_grants_backend

  storybook:
    container_name: storybook
    platform: linux/amd64
    build:
      context: .
      target: dev
    command: npm run storybook
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public
      - ./.storybook:/frontend/.storybook
      - ./stories:/frontend/stories
    restart: always
    ports:
      - 6006:6006
    networks:
      - default

networks:
  api_grants_backend:
    external: true
