services:
  grants-shared:
    build:
      context: .
      target: base
      args:
        - RUN_UID=${RUN_UID:-4000}
        - RUN_USER=${RUN_USER:-grants-shared}
    container_name: grants-shared
    env_file: ./local.env
    volumes:
      - .:/grants_shared
      # Override the dist folder so the build is isolated
      # and doesn't override with what exists outside
      - dist:/grants_shared/dist
    networks:
      - local_db
      - default

volumes:
  dist:

networks:
  grants_backend:
    driver: bridge
  local_db:
    # NOTE: This network is created by starting the shared DB
    # defined in /backend/docker-compose.db.yml
    external: true
    name: local_db