"""Holds all constant values."""

from enum import StrEnum


class OpportunityTables(StrEnum):
    """Opportunity tables that are copied over to analytics database."""

    LK_OPPORTUNITY_STATUS = "lk_opportunity_status"
    LK_OPPORTUNITY_CATEGORY = "lk_opportunity_category"
    OPPORTUNITY = "opportunity"
    OPPORTUNITY_SUMMARY = "opportunity_summary"
    CURRENT_OPPORTUNITY_SUMMARY = "current_opportunity_summary"
    USER_SAVED_OPPORTUNITY = "user_saved_opportunity"
    USER_SAVED_SEARCH = "user_saved_search"
    USER_DATA = "user_data"


LK_OPPORTUNITY_STATUS_COLS = (
    "OPPORTUNITY_STATUS_ID",
    "DESCRIPTION",
    "CREATED_AT",
    "UPDATED_AT",
)

LK_OPPORTUNITY_CATEGORY_COLS = (
    "OPPORTUNITY_CATEGORY_ID",
    "DESCRIPTION",
    "CREATED_AT",
    "UPDATED_AT",
)
OPPORTUNITY_COLS = (
    "OPPORTUNITY_ID",
    "LEGACY_OPPORTUNITY_ID",
    "OPPORTUNITY_NUMBER",
    "OPPORTUNITY_TITLE",
    "AGENCY_CODE",
    "OPPORTUNITY_CATEGORY_ID",
    "CATEGORY_EXPLANATION",
    "IS_DRAFT",
    "REVISION_NUMBER",
    "MODIFIED_COMMENTS",
    "CREATED_AT",
    "UPDATED_AT",
)
OPOORTUNITY_SUMMARY_COLS = (
    "OPPORTUNITY_SUMMARY_ID",
    "OPPORTUNITY_ID",
    "LEGACY_OPPORTUNITY_ID",
    "SUMMARY_DESCRIPTION",
    "IS_COST_SHARING",
    "IS_FORECAST",
    "POST_DATE",
    "CLOSE_DATE",
    "CLOSE_DATE_DESCRIPTION",
    "ARCHIVE_DATE",
    "UNARCHIVE_DATE",
    "EXPECTED_NUMBER_OF_AWARDS",
    "ESTIMATED_TOTAL_PROGRAM_FUNDING",
    "AWARD_FLOOR",
    "AWARD_CEILING",
    "ADDITIONAL_INFO_URL",
    "ADDITIONAL_INFO_URL_DESCRIPTION",
    "FORECASTED_POST_DATE",
    "FORECASTED_CLOSE_DATE",
    "FORECASTED_CLOSE_DATE_DESCRIPTION",
    "FORECASTED_AWARD_DATE",
    "FORECASTED_PROJECT_START_DATE",
    "FISCAL_YEAR",
    "MODIFICATION_COMMENTS",
    "FUNDING_CATEGORY_DESCRIPTION",
    "APPLICANT_ELIGIBILITY_DESCRIPTION",
    "AGENCY_CONTACT_DESCRIPTION",
    "AGENCY_EMAIL_ADDRESS",
    "AGENCY_EMAIL_ADDRESS_DESCRIPTION",
    "VERSION_NUMBER",
    "CAN_SEND_MAIL",
    "CREATED_AT",
    "UPDATED_AT",
)
CURRENT_OPPORTUNITY_SUMMARY_COLS = (
    "OPPORTUNITY_ID",
    "OPPORTUNITY_SUMMARY_ID",
    "OPPORTUNITY_STATUS_ID",
    "CREATED_AT",
    "UPDATED_AT",
)

USER_SAVED_OPPORTUNITY_COLS = (
    "USER_ID",
    "OPPORTUNITY_ID",
    "LAST_NOTIFIED_AT",
    "IS_DELETED",
    "CREATED_AT",
    "UPDATED_AT",
)
USER_SAVED_SEARCH_COLS = (
    "SAVED_SEARCH_ID",
    "USER_ID",
    "SEARCH_QUERY",
    "NAME",
    "LAST_NOTIFIED_AT",
    "SEARCHED_OPPORTUNITY_IDS",
    "IS_DELETED",
    "CREATED_AT",
    "UPDATED_AT",
)

USER_COLS = (
    "USER_ID",
    "CREATED_AT",
    "UPDATED_AT",
)

MAP_TABLES_TO_COLS: dict[OpportunityTables, tuple[str, ...]] = {
    OpportunityTables.LK_OPPORTUNITY_STATUS: LK_OPPORTUNITY_STATUS_COLS,
    OpportunityTables.LK_OPPORTUNITY_CATEGORY: LK_OPPORTUNITY_CATEGORY_COLS,
    OpportunityTables.OPPORTUNITY: OPPORTUNITY_COLS,
    OpportunityTables.OPPORTUNITY_SUMMARY: OPOORTUNITY_SUMMARY_COLS,
    OpportunityTables.CURRENT_OPPORTUNITY_SUMMARY: CURRENT_OPPORTUNITY_SUMMARY_COLS,
    OpportunityTables.USER_SAVED_OPPORTUNITY: USER_SAVED_OPPORTUNITY_COLS,
    OpportunityTables.USER_SAVED_SEARCH: USER_SAVED_SEARCH_COLS,
    OpportunityTables.USER_DATA: USER_COLS,
}

# Optional mapping for cases where file name differs from table name
# If a table is not in this mapping, the file name will be the same as the table name
MAP_TABLE_TO_FILE_NAME: dict[OpportunityTables, str] = {
    OpportunityTables.USER_DATA: "user",
}
