"""Holds all constant values."""

from enum import StrEnum


class OpportunityTables(StrEnum):
    """Opportunity tables that are copied over to analytics database."""

    LK_OPPORTUNITY_STATUS = "lk_opportunity_status"
    LK_OPPORTUNITY_CATEGORY = "lk_opportunity_category"
    OPPORTUNITY = "opportunity"
    OPPORTUNITY_SUMMARY = "opportunity_summary"
    CURRENT_OPPORTUNITY_SUMMARY = "current_opportunity_summary"


LK_OPPORTUNITY_STATUS_COLS = (
    "OPPORTUNITY_STATUS_ID",
    "DESCRIPTION",
    "CREATED_AT",
    "UPDATED_AT",
)

LK_OPPORTUNITY_CATEGORY_COLS = (
    "OPPORTUNITY_CATEGORY_ID",
    "DESCRIPTION",
    "CREATED_AT",
    "UPDATED_AT",
)
OPPORTUNITY_COLS = (
    "OPPORTUNITY_ID",
    "OPPORTUNITY_NUMBER",
    "OPPORTUNITY_TITLE",
    "AGENCY_CODE",
    "OPPORTUNITY_CATEGORY_ID",
    "CATEGORY_EXPLANATION",
    "IS_DRAFT",
    "REVISION_NUMBER",
    "MODIFIED_COMMENTS",
    "PUBLISHER_USER_ID",
    "PUBLISHER_PROFILE_ID",
    "CREATED_AT",
    "UPDATED_AT",
)
OPOORTUNITY_SUMMARY_COLS = (
    "OPPORTUNITY_SUMMARY_ID",
    "OPPORTUNITY_ID",
    "SUMMARY_DESCRIPTION",
    "IS_COST_SHARING",
    "IS_FORECAST",
    "POST_DATE",
    "CLOSE_DATE",
    "CLOSE_DATE_DESCRIPTION",
    "ARCHIVE_DATE",
    "UNARCHIVE_DATE",
    "EXPECTED_NUMBER_OF_AWARDS",
    "ESTIMATED_TOTAL_PROGRAM_FUNDING",
    "AWARD_FLOOR",
    "AWARD_CEILING",
    "ADDITIONAL_INFO_URL",
    "ADDITIONAL_INFO_URL_DESCRIPTION",
    "FORECASTED_POST_DATE",
    "FORECASTED_CLOSE_DATE",
    "FORECASTED_CLOSE_DATE_DESCRIPTION",
    "FORECASTED_AWARD_DATE",
    "FORECASTED_PROJECT_START_DATE",
    "FISCAL_YEAR",
    "MODIFICATION_COMMENTS",
    "FUNDING_CATEGORY_DESCRIPTION",
    "APPLICANT_ELIGIBILITY_DESCRIPTION",
    "AGENCY_CODE",
    "AGENCY_NAME",
    "AGENCY_PHONE_NUMBER",
    "AGENCY_CONTACT_DESCRIPTION",
    "AGENCY_EMAIL_ADDRESS",
    "AGENCY_EMAIL_ADDRESS_DESCRIPTION",
    "CAN_SEND_MAIL",
    "PUBLISHER_PROFILE_ID",
    "PUBLISHER_USER_ID",
    "UPDATED_BY",
    "CREATED_BY",
    "CREATED_AT",
    "UPDATED_AT",
    "VERSION_NUMBER",
)
CURRENT_OPPORTUNITY_SUMMARY_COLS = (
    "OPPORTUNITY_ID",
    "OPPORTUNITY_SUMMARY_ID",
    "OPPORTUNITY_STATUS_ID",
    "CREATED_AT",
    "UPDATED_AT",
)

MAP_TABLES_TO_COLS: dict[OpportunityTables, tuple[str, ...]] = {
    OpportunityTables.LK_OPPORTUNITY_STATUS: LK_OPPORTUNITY_STATUS_COLS,
    OpportunityTables.LK_OPPORTUNITY_CATEGORY: LK_OPPORTUNITY_CATEGORY_COLS,
    OpportunityTables.OPPORTUNITY: OPPORTUNITY_COLS,
    OpportunityTables.OPPORTUNITY_SUMMARY: OPOORTUNITY_SUMMARY_COLS,
    OpportunityTables.CURRENT_OPPORTUNITY_SUMMARY: CURRENT_OPPORTUNITY_SUMMARY_COLS,
}
