fail-on-severity: "medium"

# List of vulnerabilities to ignore for the anchore scan
# https://github.com/anchore/grype#specifying-matches-to-ignore
# More info can be found in the docs/infra/vulnerability-management.md file

# Please add safelists in the following format to make it easier when checking
# Package/module name: URL to vulnerability for checking updates
#  Versions:     URL to the version history
#  Dependencies: Name of any other packages or modules that are dependent on this version
#                 Link to the dependencies for ease of checking for updates
#  Issue:         Why there is a finding and why this is here or not been removed
#  Last checked:  Date last checked in scans
# - vulnerability: The-CVE-or-vuln-id # Remove comment at start of line

ignore:
  # These settings ignore any findings that fall into these categories
  - fix-state: not-fixed
  - fix-state: wont-fix
  - fix-state: unknown

  # Zipfile Module
  # We don't a potch available yet in the python 3.13.x version. The latest version 3.13.8 still has the vulnerability.
  - vulnerability: CVE-2025-8291

  # This is a vulnerability in python when using bytes.decode("unicode_escape", error="ignore|replace")
  # We don't use this anywhere, and I can't find any uses of decode
  # in this manner in any library we use (but won't guarantee there are zero).
  # A fix hasn't been backported to python 3.13 yet.
  #
  # Last checked: May 20th, 2025
  - vulnerability: CVE-2025-4516

  # This is a vulnerability in html.parser.HTMLParser which we don't use
  # Last checked: June 20th, 2025
  - vulnerability: CVE-2025-6069

  # This is a vulnerability in python's tarfile module when parsing tarfiles
  # We don't use this anywhere, and it will be fixed in python 3.14
  # Last checked: July 30th, 2025
  - vulnerability: CVE-2025-8194

  # Tornado has a vulnerability in it, but we don't use this library.
  # This is one way you can run a gunicorn workers, but we don't.
  # We don't even pull this package in ourselves, so we likely need
  # an upstream library (gunicorn itself?) to update.
  #
  # Last checked: May 20th, 2025
  - vulnerability: GHSA-7cx3-6m66-7c5m

  # https://github.com/HHS/simpler-grants-gov/issues/3855
  # esbuild fixed in a new minor version, but we don't install/call esbuild directly
  - vulnerability: GHSA-67mh-4wv8-2f99

  # Last Check - October 14th
  # Issue with zip64 in the zipfile module which we aren't using
  # Fixed in latest Python version
  - vulnerability: CVE-2025-8291
