fail-on-severity: "medium"

# List of vulnerabilities to ignore for the anchore scan
# https://github.com/anchore/grype#specifying-matches-to-ignore
# More info can be found in the docs/infra/vulnerability-management.md file

# Please add safelists in the following format to make it easier when checking
# Package/module name: URL to vulnerability for checking updates
#  Versions:     URL to the version history
#  Dependencies: Name of any other packages or modules that are dependent on this version
#                 Link to the dependencies for ease of checking for updates
#  Issue:         Why there is a finding and why this is here or not been removed
#  Last checked:  Date last checked in scans
# - vulnerability: The-CVE-or-vuln-id # Remove comment at start of line

ignore:
  # These settings ignore any findings that fall into these categories
  - fix-state: not-fixed
  - fix-state: wont-fix
  - fix-state: unknown

  # These vulnerabilities should be fixed in the next version of Debian
  # Doing installs directly on them in our Dockerfile doesn't seem to
  # pick up the changes, so we'll have to wait until the base images
  # of our Docker images are updated, usually around the start of the month
  #
  # Last checked: March 17th, 2025
  - vulnerability: CVE-2025-0395
  - vulnerability: CVE-2025-1094
  - vulnerability: CVE-2024-38428

  # https://github.com/HHS/simpler-grants-gov/issues/3855
  # esbuild fixed in a new minor version, but we don't install/call esbuild directly
  - vulnerability: GHSA-67mh-4wv8-2f99
