fail-on-severity: "medium"

# List of vulnerabilities to ignore for the anchore scan
# https://github.com/anchore/grype#specifying-matches-to-ignore
# More info can be found in the docs/infra/vulnerability-management.md file

# Please add safelists in the following format to make it easier when checking
# Package/module name: URL to vulnerability for checking updates
#  Versions:     URL to the version history
#  Dependencies: Name of any other packages or modules that are dependent on this version
#                 Link to the dependencies for ease of checking for updates
#  Issue:         Why there is a finding and why this is here or not been removed
#  Last checked:  Date last checked in scans
# - vulnerability: The-CVE-or-vuln-id # Remove comment at start of line

ignore:
  # These settings ignore any findings that fall into these categories
  - fix-state: not-fixed
  - fix-state: wont-fix
  - fix-state: unknown

  # https://github.com/HHS/simpler-grants-gov/issues/3855
  # esbuild fixed in a new minor version, but we don't install/call esbuild directly
  - vulnerability: GHSA-67mh-4wv8-2f99

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2026-0865

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2025-15282

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2026-0672

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2025-15366

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2025-15367

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2025-12781

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2025-11468

  # Not fixed in GA Python yet
  # Vulnerability in a very specific part of the python email
  # package which we don't use.
  # Last checked: 02/04/26
  - vulnerability: CVE-2026-1299

  # Next.js vulnerability reported as fixed only in canary prerelease
  # Scanner indicates fix in 15.6.0-canary.61, which cannot be installed due to
  # npm peer dependency resolution rules for prerelease versions
  # Attempting to upgrade to canary causes ERESOLVE failures with
  # @next/third-parties peer dependencies
  # Stable Next.js 15.x releases include backported fixes, but are not
  # recognized by the scanner at this time
  # https://github.com/advisories/GHSA-5f7q-jpqc-wp7h
  # Versions: https://github.com/vercel/next.js/releases
  # Dependencies: @next/third-parties
  # Last checked: 01/29/26
  - vulnerability: GHSA-5f7q-jpqc-wp7h

  # ============================================================================
  # Amazon Linux 2023 packages - fixes not yet available in public repos
  # The security advisories have been published but the patched packages
  # have not been released to the Amazon Linux 2023 repositories yet.
  # Monitor: https://alas.aws.amazon.com/alas2023.html
  # Last checked: 02/06/26
  # ============================================================================

  # openssl: Stack buffer overflow in CMS message parsing (ALAS2023-2026-1406)
  # https://alas.aws.amazon.com/AL2023/ALAS-2026-1406.html
  # Fixed version 1:3.2.2-1.amzn2023.0.4 not available in repos (latest is 0.3)
  - vulnerability: ALAS2023-2026-1406

  # libtasn1: Stack-based buffer overflow (ALAS2023-2026-1395)
  # https://alas.aws.amazon.com/AL2023/ALAS-2026-1395.html
  # Fixed version 4.19.0-1.amzn2023.0.6 not available in repos (latest is 0.5)
  - vulnerability: ALAS2023-2026-1395

  # libcap: Multiple vulnerabilities (ALAS2023-2026-1389)
  # https://alas.aws.amazon.com/AL2023/ALAS-2026-1389.html
  # Fixed version 2.73-1.amzn2023.0.6 not available in repos (latest is 0.5)
  - vulnerability: ALAS2023-2026-1389

  # libxml2: Uncontrolled recursion in xmlCatalogXMLResolveURI (ALAS2023-2026-1396)
  # https://alas.aws.amazon.com/AL2023/ALAS-2026-1396.html
  # Fixed version 2.10.4-1.amzn2023.0.16 not available in repos (latest is 0.15)
  - vulnerability: ALAS2023-2026-1396

  # libxml2: Uncontrolled recursion in RelaxNG parser (ALAS2023-2026-1397)
  # https://alas.aws.amazon.com/AL2023/ALAS-2026-1397.html
  # Fixed version 2.10.4-1.amzn2023.0.17 not available in repos (latest is 0.15)
  - vulnerability: ALAS2023-2026-1397

  # unzip: Denial of service via overlapping files in ZIP (ALAS2023-2026-1422)
  # https://alas.aws.amazon.com/AL2023/ALAS-2026-1422.html
  # Fixed version 6.0-68.amzn2023.0.1 not available in repos (latest is 6.0-57.amzn2023.0.2)
  - vulnerability: ALAS2023-2026-1422

  # python3-pip-wheel: urllib3 decompression bomb vulnerability (ALAS2023-2026-1416)
  # https://alas.aws.amazon.com/AL2023/ALAS-2026-1416.html
  # Fixed version 21.3.1-2.amzn2023.0.16 not available in repos (latest is 0.15)
  - vulnerability: ALAS2023-2026-1416
