fail-on-severity: "medium"

# List of vulnerabilities to ignore for the anchore scan
# https://github.com/anchore/grype#specifying-matches-to-ignore
# More info can be found in the docs/infra/vulnerability-management.md file

# Please add safelists in the following format to make it easier when checking
# Package/module name: URL to vulnerability for checking updates
#  Versions:     URL to the version history
#  Dependencies: Name of any other packages or modules that are dependent on this version
#                 Link to the dependencies for ease of checking for updates
#  Issue:         Why there is a finding and why this is here or not been removed
#  Last checked:  Date last checked in scans
# - vulnerability: The-CVE-or-vuln-id # Remove comment at start of line

ignore:
  # These settings ignore any findings that fall into these categories
  - fix-state: not-fixed
  - fix-state: wont-fix
  - fix-state: unknown

  # https://github.com/HHS/simpler-grants-gov/issues/3855
  # esbuild fixed in a new minor version, but we don't install/call esbuild directly
  - vulnerability: GHSA-67mh-4wv8-2f99

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2026-0865

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2025-15282

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2026-0672

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2025-15366

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2025-15367

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2025-12781

  # Not fixed in GA Python yet
  # https://github.com/HHS/simpler-grants-gov/issues/8109
  # Last checked: 01/23/26
  - vulnerability: CVE-2025-11468

  # Next.js 15.4.10 -> 15.5.10 upgrade causes breaking changes in next.config.js
  # The fix requires path pattern syntax updates that need more testing
  # https://github.com/advisories/GHSA-9g9p-9gw9-jx7f
  # Last checked: 01/28/26
  - vulnerability: GHSA-9g9p-9gw9-jx7f

  # Next.js vulnerability reported as fixed only in canary prerelease
  # Scanner indicates fix in 15.6.0-canary.61, which cannot be installed due to
  # npm peer dependency resolution rules for prerelease versions
  # Attempting to upgrade to canary causes ERESOLVE failures with
  # @next/third-parties peer dependencies
  # Stable Next.js 15.x releases include backported fixes, but are not
  # recognized by the scanner at this time
  # https://github.com/advisories/GHSA-5f7q-jpqc-wp7h
  # Versions: https://github.com/vercel/next.js/releases
  # Dependencies: @next/third-parties
  # Last checked: 01/29/26
  - vulnerability: GHSA-5f7q-jpqc-wp7h
  