from marshmallow import ValidationError, validates_schema

from src.api.competition_alpha.competition_schema import CompetitionAlphaSchema
from src.api.opportunities_v1.opportunity_schemas import (
    OpportunityAttachmentV1Schema,
    OpportunitySummaryV1Schema,
    OpportunityV1Schema,
)
from src.api.schemas.extension import Schema, fields, validators
from src.api.schemas.extension.schema_common import MarshmallowErrorContainer
from src.api.schemas.response_schema import AbstractResponseSchema, PaginationMixinSchema
from src.constants.lookup_constants import (
    ApplicantType,
    FundingCategory,
    FundingInstrument,
    OpportunityCategory,
)
from src.pagination.pagination_schema import generate_pagination_schema
from src.validation.validation_constants import ValidationErrorType


class OpportunityCreateRequestSchema(Schema):
    """Schema for POST /v1/grantors/opportunities/ request

    Example Request:
    {
      "opportunity_number": "ABC-2026-001",
      "opportunity_title": "Research Grant for Climate Innovation",
      "agency_id": "550e8400-e29b-41d4-a716-446655440000",
      "category": "discretionary",
      "category_explanation": "Competitive research grant"
    }

    Note: The following fields are automatically generated by the system and should not be included in the request:
    - opportunity_id (UUID)
    - legacy_opportunity_id (always null for new opportunities)
    - agency_code (derived from agency_id)
    - is_draft (always true for new opportunities)
    - created_at / updated_at (timestamps)
    """

    opportunity_number = fields.String(
        required=True,
        validate=validators.Length(max=40),
        metadata={
            "description": "The funding opportunity number (must be unique)",
            "example": "ABC-2026-001",
        },
    )
    opportunity_title = fields.String(
        required=True,
        validate=validators.Length(max=255),
        metadata={
            "description": "The title of the opportunity",
            "example": "Research Grant for Climate Innovation",
        },
    )
    agency_id = fields.UUID(
        required=True,
        metadata={
            "description": "The UUID of the agency that will own this opportunity",
        },
    )
    category = fields.Enum(
        OpportunityCategory,
        required=True,
        metadata={
            "description": "The opportunity category",
        },
    )
    category_explanation = fields.String(
        allow_none=True,
        validate=validators.Length(max=255),
        metadata={
            "description": "Explanation of the category (required when category is 'other')",
            "example": "Competitive research grant",
        },
    )


class OpportunityGrantorSchema(OpportunityV1Schema):
    """Schema for opportunity data in grantor-facing API responses"""

    is_draft = fields.Boolean(
        metadata={
            "description": "Whether the opportunity is a draft",
        },
    )

    forecast_summary = fields.Nested(
        OpportunitySummaryV1Schema(),
        allow_none=True,
        attribute="forecast_summary",
        metadata={
            "description": "The forecast summary of the opportunity (if available)",
        },
    )

    non_forecast_summary = fields.Nested(
        OpportunitySummaryV1Schema(),
        allow_none=True,
        attribute="non_forecast_summary",
        metadata={
            "description": "The non-forecast summary of the opportunity (if available)",
        },
    )

    attachments = fields.List(
        fields.Nested(OpportunityAttachmentV1Schema),
        attribute="opportunity_attachments",
        metadata={"description": "List of attachments associated with the opportunity"},
    )

    competitions = fields.List(
        fields.Nested(CompetitionAlphaSchema),
        metadata={"description": "List of competitions associated with the opportunity"},
    )


class OpportunityUpdateRequestSchema(Schema):
    """Schema for PUT /v1/grantors/opportunities/<opportunity_id> request"""

    opportunity_title = fields.String(
        required=True,
        validate=validators.Length(max=255),
        metadata={
            "description": "The title of the opportunity",
            "example": "Updated Research Grant for Climate Innovation",
        },
    )
    category = fields.Enum(
        OpportunityCategory,
        required=True,
        metadata={
            "description": "The opportunity category",
        },
    )
    category_explanation = fields.String(
        allow_none=True,
        load_default=None,
        validate=validators.Length(max=255),
        metadata={
            "description": "Explanation of the category (required when category is 'other')",
        },
    )


class OpportunityUpdateResponseSchema(AbstractResponseSchema):
    """Schema for PUT /v1/grantors/opportunities/<opportunity_id> response"""

    data = fields.Nested(OpportunityGrantorSchema())


class OpportunityCreateResponseSchema(AbstractResponseSchema):
    """Schema for POST /v1/grantors/opportunities/ response

    Example Response:
    {
      "message": "Success",
      "data": {
        "opportunity_id": "550e8400-e29b-41d4-a716-446655440000",
        "opportunity_number": "ABC-2026-001",
        "opportunity_title": "Research Grant for Climate Innovation",
        "agency_id": "add4b88f-e895-4ca9-92f4-38ed34055247",
        "agency_code": "DOC",
        "category": "discretionary",
        "category_explanation": "Competitive research grant",
        "is_draft": true,
        "created_at": "2026-02-10T16:20:00Z",
        "updated_at": "2026-02-10T16:20:00Z"
      }
    }
    """

    data = fields.Nested(OpportunityGrantorSchema())


class OpportunityGetResponseSchema(AbstractResponseSchema):
    """Schema for GET /v1/grantors/opportunities/:opportunity_id/grantor response

    Example Response:
    {
      "message": "Success",
      "data": {
        "opportunity_number": "ABC-2026-001",
        "opportunity_title": "Research Grant for Climate Innovation",
        "agency_id": "550e8400-e29b-41d4-a716-446655440000",
        "category": "discretionary",
        "category_explanation": "Competitive research grant",
        "is_draft": true,
        "created_at": "2026-01-27T22:11:58.119Z",
        "updated_at": "2026-01-27T22:11:58.119Z"
      }
    }
    """

    data = fields.Nested(OpportunityGrantorSchema())


class OpportunityListRequestSchema(Schema):
    """Schema for POST /v1/grantors/opportunities/:agency_id/opportunities request"""

    pagination = fields.Nested(
        generate_pagination_schema(
            "OpportunityListPaginationSchema",
            [
                "opportunity_id",
                "opportunity_number",
                "opportunity_title",
                "created_at",
            ],
            default_sort_order=[{"order_by": "created_at", "sort_direction": "descending"}],
            default_page_size=25,
            default_page_offset=1,
        ),
        required=True,
        metadata={
            "description": "Pagination parameters for opportunity list (default sort: created_at descending)"
        },
    )


class OpportunityListResponseSchema(AbstractResponseSchema, PaginationMixinSchema):
    """Schema for POST /v1/grantors/opportunities/:agency_id/opportunities response"""

    data = fields.List(
        fields.Nested(OpportunityGrantorSchema),
        metadata={"description": "List of opportunities"},
    )


class OpportunitySummaryCreateRequestV1Schema(OpportunitySummaryV1Schema):
    is_forecast = fields.Boolean(
        required=True,
        metadata={"description": "Whether the opportunity is forecasted", "example": False},
    )

    summary_description = fields.String(
        required=True,
        validate=validators.Length(max=18000),
        metadata={"description": "Opportunity summary", "example": "This opportunity..."},
    )

    is_cost_sharing = fields.Boolean(
        required=True,
        metadata={
            "description": "Whether or not the opportunity has a cost sharing/matching requirement",
        },
    )

    post_date = fields.Date(
        required=True,
        metadata={
            "description": "The date the opportunity was posted",
        },
    )

    expected_number_of_awards = fields.Integer(
        required=False,
        validate=validators.Range(min=0, max=999_999_999_999_999),
        metadata={
            "description": "The number of awards the opportunity is expected to award",
            "example": 10,
        },
    )

    estimated_total_program_funding = fields.Integer(
        required=False,
        validate=validators.Range(min=0, max=999_999_999_999_999),
        metadata={
            "description": "The total program funding of the opportunity in US Dollars",
            "example": 10_000_000,
        },
    )

    award_floor = fields.Integer(
        required=True,
        validate=validators.Range(min=0, max=999_999_999_999_999),
        metadata={
            "description": "The minimum amount an opportunity would award",
            "example": 10_000,
        },
    )

    award_ceiling = fields.Integer(
        required=True,
        validate=validators.Range(min=0, max=999_999_999_999_999),
        metadata={
            "description": "The maximum amount an opportunity would award",
            "example": 100_000,
        },
    )

    additional_info_url = fields.String(
        required=False,
        validate=validators.Length(max=250),
        metadata={
            "description": "A URL to a website that can provide additional information about the opportunity",
            "example": "grants.gov",
        },
    )

    additional_info_url_description = fields.String(
        required=False,
        validate=validators.Length(max=250),
        metadata={
            "description": "The text to display for the additional_info_url link",
            "example": "Click me for more info",
        },
    )

    funding_categories = fields.List(
        fields.Enum(FundingCategory),
        required=True,
        validate=validators.Length(min=1),
        metadata={
            "description": "Categories of funding for this opportunity",
            "example": ["education", "health"],
        },
    )

    funding_category_description = fields.String(
        required=False,
        validate=validators.Length(max=2500),
        metadata={
            "description": "Additional information about the funding category",
            "example": "Economic Support",
        },
    )

    funding_instruments = fields.List(
        fields.Enum(FundingInstrument),
        required=True,
        validate=validators.Length(min=1),
        metadata={
            "description": "Types of funding instruments used for this opportunity",
            "example": ["cooperative_agreement", "grant"],
        },
    )

    applicant_types = fields.List(
        fields.Enum(ApplicantType),
        required=True,
        validate=validators.Length(min=1),
        metadata={
            "description": "Types of applicants eligible for this opportunity",
            "example": ["state_governments", "county_governments"],
        },
    )

    applicant_eligibility_description = fields.String(
        required=False,
        validate=validators.Length(max=4000),
        metadata={
            "description": "Additional information about the types of applicants that are eligible",
            "example": "All types of domestic applicants are eligible to apply",
        },
    )

    agency_contact_description = fields.String(
        required=True,
        validate=validators.Length(max=1000),
        metadata={
            "description": "Information regarding contacting the agency who owns the opportunity",
            "example": "For more information, reach out to Jane Smith at agency US-ABC",
        },
    )

    agency_email_address = fields.String(
        required=True,
        validate=validators.Length(max=130),
        metadata={
            "description": "The contact email of the agency who owns the opportunity",
            "example": "fake_email@grants.gov",
        },
    )

    agency_email_address_description = fields.String(
        required=True,
        validate=validators.Length(max=108),
        metadata={
            "description": "The text for the link to the agency email address",
            "example": "Click me to email the agency",
        },
    )

    @validates_schema
    def validate_award_values(self, data: dict, **kwargs: dict) -> None:
        """Validate that award floor is less than or equal to award ceiling"""
        if data.get("award_floor") is not None and data.get("award_ceiling") is not None:
            if data["award_floor"] > data["award_ceiling"]:
                raise ValidationError(
                    [
                        MarshmallowErrorContainer(
                            ValidationErrorType.INVALID,
                            "Award floor must be less than or equal to award ceiling",
                        )
                    ]
                )

    @validates_schema
    def validate_dates(self, data: dict, **kwargs: dict) -> None:
        """Validate that post date is less than or equal to close date"""
        if data.get("post_date") is not None and data.get("close_date") is not None:
            if data["post_date"] > data["close_date"]:
                raise ValidationError(
                    [
                        MarshmallowErrorContainer(
                            ValidationErrorType.INVALID,
                            "Post date must be less than or equal to close date",
                        )
                    ]
                )


class OpportunitySummaryCreateResponseV1Schema(AbstractResponseSchema):
    data = fields.Nested(OpportunitySummaryV1Schema())
