from enum import StrEnum

from src.api.schemas.extension import Schema, fields, validators
from src.api.schemas.response_schema import AbstractResponseSchema, FileResponseSchema
from src.constants.lookup_constants import OpportunityCategory


class OpportunityAttachmentV1Schema(FileResponseSchema):
    mime_type = fields.String(
        metadata={"description": "The MIME type of the attachment", "example": "application/pdf"}
    )
    file_name = fields.String(
        metadata={"description": "The name of the attachment file", "example": "my_NOFO.pdf"}
    )
    file_description = fields.String(
        metadata={
            "description": "A description of the attachment",
            "example": "The full announcement NOFO",
        }
    )


class OpportunityCreateRequestSchema(Schema):
    """Schema for POST /v1/grantors/opportunities/ request

    Example Request:
    {
      "opportunity_number": "ABC-2026-001",
      "opportunity_title": "Research Grant for Climate Innovation",
      "agency_id": "550e8400-e29b-41d4-a716-446655440000",
      "category": "discretionary",
      "category_explanation": "Competitive research grant"
    }

    Note: The following fields are automatically generated by the system and should not be included in the request:
    - opportunity_id (UUID)
    - legacy_opportunity_id (always null for new opportunities)
    - agency_code (derived from agency_id)
    - is_draft (always true for new opportunities)
    - created_at / updated_at (timestamps)
    """

    opportunity_number = fields.String(
        required=True,
        validate=validators.Length(max=40),
        metadata={
            "description": "The funding opportunity number (must be unique)",
            "example": "ABC-2026-001",
        },
    )
    opportunity_title = fields.String(
        required=True,
        validate=validators.Length(max=255),
        metadata={
            "description": "The title of the opportunity",
            "example": "Research Grant for Climate Innovation",
        },
    )
    agency_id = fields.UUID(
        required=True,
        metadata={
            "description": "The UUID of the agency that will own this opportunity",
            "example": "add4b88f-e895-4ca9-92f4-38ed34055247",
        },
    )
    category = fields.Enum(
        OpportunityCategory,
        required=True,
        metadata={
            "description": "The opportunity category",
            "example": OpportunityCategory.DISCRETIONARY,
        },
    )
    category_explanation = fields.String(
        validate=validators.Length(max=255),
        metadata={
            "description": "Explanation of the category (required when category is 'other')",
            "example": "Competitive research grant",
        },
    )


class OpportunityGrantorSchema(Schema):
    """Schema for opportunity data in grantor-facing API responses

    This schema defines the opportunity fields that are returned in grantor-facing API responses.
    """

    opportunity_id = fields.UUID(
        metadata={"description": "The internal ID of the opportunity"},
    )
    opportunity_number = fields.String(
        metadata={"description": "The funding opportunity number", "example": "ABC-2026-001"},
    )
    opportunity_title = fields.String(
        metadata={
            "description": "The title of the opportunity",
            "example": "Research Grant for Climate Innovation",
        },
    )
    agency_id = fields.UUID(
        metadata={
            "description": "The UUID of the agency that owns this opportunity",
            "example": "add4b88f-e895-4ca9-92f4-38ed34055247",
        },
    )
    agency_code = fields.String(
        metadata={"description": "The agency code", "example": "US-ABC"},
    )
    category = fields.Enum(
        OpportunityCategory,
        metadata={
            "description": "The opportunity category",
            "example": OpportunityCategory.DISCRETIONARY,
        },
    )
    category_explanation = fields.String(
        metadata={
            "description": "Explanation of the category",
            "example": "Competitive research grant",
        },
    )
    is_draft = fields.Boolean(
        metadata={
            "description": "Whether the opportunity is a draft",
            "example": True,
        },
    )
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)


class OpportunityCreateResponseSchema(AbstractResponseSchema):
    """Schema for POST /v1/grantors/opportunities/ response

    Example Response:
    {
      "message": "Success",
      "data": {
        "opportunity_id": "550e8400-e29b-41d4-a716-446655440000",
        "opportunity_number": "ABC-2026-001",
        "opportunity_title": "Research Grant for Climate Innovation",
        "agency_id": "add4b88f-e895-4ca9-92f4-38ed34055247",
        "agency_code": "DOC",
        "category": "discretionary",
        "category_explanation": "Competitive research grant",
        "is_draft": true,
        "created_at": "2026-02-10T16:20:00Z",
        "updated_at": "2026-02-10T16:20:00Z"
      }
    }
    """

    data = fields.Nested(OpportunityGrantorSchema())
