from src.api.opportunities_v1.opportunity_schemas import (
    OpportunitySummaryV1Schema,
    OpportunityV1Schema,
)
from src.api.schemas.extension import Schema, fields, validators
from src.api.schemas.response_schema import AbstractResponseSchema, PaginationMixinSchema
from src.constants.lookup_constants import OpportunityCategory
from src.pagination.pagination_schema import generate_pagination_schema


class OpportunityCreateRequestSchema(Schema):
    """Schema for POST /v1/grantors/opportunities/ request

    Example Request:
    {
      "opportunity_number": "ABC-2026-001",
      "opportunity_title": "Research Grant for Climate Innovation",
      "agency_id": "550e8400-e29b-41d4-a716-446655440000",
      "category": "discretionary",
      "category_explanation": "Competitive research grant"
    }

    Note: The following fields are automatically generated by the system and should not be included in the request:
    - opportunity_id (UUID)
    - legacy_opportunity_id (always null for new opportunities)
    - agency_code (derived from agency_id)
    - is_draft (always true for new opportunities)
    - created_at / updated_at (timestamps)
    """

    opportunity_number = fields.String(
        required=True,
        validate=validators.Length(max=40),
        metadata={
            "description": "The funding opportunity number (must be unique)",
            "example": "ABC-2026-001",
        },
    )
    opportunity_title = fields.String(
        required=True,
        validate=validators.Length(max=255),
        metadata={
            "description": "The title of the opportunity",
            "example": "Research Grant for Climate Innovation",
        },
    )
    agency_id = fields.UUID(
        required=True,
        metadata={
            "description": "The UUID of the agency that will own this opportunity",
        },
    )
    category = fields.Enum(
        OpportunityCategory,
        required=True,
        metadata={
            "description": "The opportunity category",
        },
    )
    category_explanation = fields.String(
        validate=validators.Length(max=255),
        metadata={
            "description": "Explanation of the category (required when category is 'other')",
            "example": "Competitive research grant",
        },
    )


class OpportunityGrantorSchema(OpportunityV1Schema):
    """Schema for opportunity data in grantor-facing API responses"""

    is_draft = fields.Boolean(
        metadata={
            "description": "Whether the opportunity is a draft",
        },
    )

    forecast_summary = fields.Nested(
        OpportunitySummaryV1Schema(),
        allow_none=True,
        attribute="forecast_summary",
        metadata={
            "description": "The forecast summary of the opportunity (if available)",
        },
    )

    non_forecast_summary = fields.Nested(
        OpportunitySummaryV1Schema(),
        allow_none=True,
        attribute="non_forecast_summary",
        metadata={
            "description": "The non-forecast summary of the opportunity (if available)",
        },
    )


class OpportunityCreateResponseSchema(AbstractResponseSchema):
    """Schema for POST /v1/grantors/opportunities/ response

    Example Response:
    {
      "message": "Success",
      "data": {
        "opportunity_id": "550e8400-e29b-41d4-a716-446655440000",
        "opportunity_number": "ABC-2026-001",
        "opportunity_title": "Research Grant for Climate Innovation",
        "agency_id": "add4b88f-e895-4ca9-92f4-38ed34055247",
        "agency_code": "DOC",
        "category": "discretionary",
        "category_explanation": "Competitive research grant",
        "is_draft": true,
        "created_at": "2026-02-10T16:20:00Z",
        "updated_at": "2026-02-10T16:20:00Z"
      }
    }
    """

    data = fields.Nested(OpportunityGrantorSchema())


class OpportunityGetResponseSchema(AbstractResponseSchema):
    """Schema for GET /v1/grantors/opportunities/:opportunity_id/grantor response

    Example Response:
    {
      "message": "Success",
      "data": {
        "opportunity_number": "ABC-2026-001",
        "opportunity_title": "Research Grant for Climate Innovation",
        "agency_id": "550e8400-e29b-41d4-a716-446655440000",
        "category": "discretionary",
        "category_explanation": "Competitive research grant",
        "is_draft": true,
        "created_at": "2026-01-27T22:11:58.119Z",
        "updated_at": "2026-01-27T22:11:58.119Z"
      }
    }
    """

    data = fields.Nested(OpportunityGrantorSchema())


class OpportunityListRequestSchema(Schema):
    """Schema for POST /v1/grantors/opportunities/:agency_id/opportunities request"""

    pagination = fields.Nested(
        generate_pagination_schema(
            "OpportunityListPaginationSchema",
            [
                "opportunity_id",
                "opportunity_number",
                "opportunity_title",
                "created_at",
                "updated_at",
            ],
            default_sort_order=[{"order_by": "opportunity_id", "sort_direction": "ascending"}],
            default_page_size=25,
            default_page_offset=1,
        ),
        required=True,
        metadata={
            "description": "Pagination parameters for opportunity list (default sort: opportunity_id ascending)"
        },
    )


class OpportunityListResponseSchema(AbstractResponseSchema, PaginationMixinSchema):
    """Schema for POST /v1/grantors/opportunities/:agency_id/opportunities response"""

    data = fields.List(
        fields.Nested(OpportunityGrantorSchema),
        metadata={"description": "List of opportunities"},
    )
