import { FillFieldDefinition } from "tests/e2e/apply/helpers/general-forms-filling";
import type { SflllEntityData } from "tests/e2e/apply/fixtures/test-data-for-forms.fixture";

export const SFLLL_FORM_CONFIG = {
	formName: "Disclosure of Lobbying Activities (SF-LLL)",
	noErrorsText: "No errors were detected",
	saveButtonTestId: "apply-form-save",
} as const;

export function getSflllFillFields(
	data: SflllEntityData,
): FillFieldDefinition[] {
	return [
		{
			selector: "#federal_action_type",
			value: data.federalAction.type,
			type: "dropdown",
			section: "Section 1: Type of Federal Action",
		},
		{
			selector: "#federal_action_status",
			value: data.federalAction.status,
			type: "dropdown",
			section: "Section 2: Status of Federal Action",
		},
		{
			selector: "#report_type",
			value: data.federalAction.reportType,
			type: "dropdown",
			section: "Section 3: Report Type",
		},
		{
			testId: "material_change_year",
			value: data.materialChange.year,
			type: "text",
			section: "Section 3: Material Change Year",
		},
		{
			testId: "material_change_quarter",
			value: data.materialChange.quarter,
			type: "text",
			section: "Section 3: Material Change Quarter",
		},
		{
			testId: "last_report_date",
			value: data.materialChange.lastReportDate,
			type: "text",
			section: "Section 3: Last Report Date",
		},
		{
			selector: "#reporting_entity--entity_type",
			value: data.reportingEntity.type,
			type: "dropdown",
			section: "Section 4: Entity Type",
		},
		{
			testId: "reporting_entity--tier",
			value: data.reportingEntity.tier,
			type: "text",
			section: "Section 4: Tier",
		},
		{
			testId: "reporting_entity--applicant_reporting_entity--organization_name",
			value: data.reportingEntity.orgName,
			type: "text",
			section: "Section 4: Organization Name",
		},
		{
			testId: "reporting_entity--applicant_reporting_entity--address--street1",
			value: data.reportingEntity.street1,
			type: "text",
			section: "Section 4: Street 1",
		},
		{
			testId: "reporting_entity--applicant_reporting_entity--address--street2",
			value: data.reportingEntity.street2,
			type: "text",
			section: "Section 4: Street 2",
		},
		{
			testId: "reporting_entity--applicant_reporting_entity--address--city",
			value: data.reportingEntity.city,
			type: "text",
			section: "Section 4: City",
		},
		{
			selector: "#reporting_entity--applicant_reporting_entity--address--state",
			value: data.reportingEntity.state,
			type: "dropdown",
			section: "Section 4: State",
		},
		{
			testId: "reporting_entity--applicant_reporting_entity--address--zip_code",
			value: data.reportingEntity.zip,
			type: "text",
			section: "Section 4: Zip Code",
		},
		{
			testId:
				"reporting_entity--applicant_reporting_entity--congressional_district",
			value: data.reportingEntity.district,
			type: "text",
			section: "Section 4: Congressional District",
		},
		{
			testId: "reporting_entity--prime_reporting_entity--organization_name",
			value: data.primeEntity.orgName,
			type: "text",
			section: "Section 5: Prime Organization Name",
		},
		{
			testId: "reporting_entity--prime_reporting_entity--address--street1",
			value: data.primeEntity.street1,
			type: "text",
			section: "Section 5: Prime Street 1",
		},
		{
			testId: "reporting_entity--prime_reporting_entity--address--street2",
			value: data.primeEntity.street2,
			type: "text",
			section: "Section 5: Prime Street 2",
		},
		{
			testId: "reporting_entity--prime_reporting_entity--address--city",
			value: data.primeEntity.city,
			type: "text",
			section: "Section 5: Prime City",
		},
		{
			selector: "#reporting_entity--prime_reporting_entity--address--state",
			value: data.primeEntity.state,
			type: "dropdown",
			section: "Section 5: Prime State",
		},
		{
			testId: "reporting_entity--prime_reporting_entity--address--zip_code",
			value: data.primeEntity.zip,
			type: "text",
			section: "Section 5: Prime Zip Code",
		},
		{
			testId: "reporting_entity--prime_reporting_entity--congressional_district",
			value: data.primeEntity.district,
			type: "text",
			section: "Section 5: Prime Congressional District",
		},
		{
			testId: "federal_agency_department",
			value: data.federalInfo.agencyDepartment,
			type: "text",
			section: "Section 6: Federal Agency/Department",
		},
		{
			testId: "federal_program_name",
			value: data.federalInfo.programName,
			type: "text",
			section: "Section 7: Federal Program Name",
		},
		{
			testId: "assistance_listing_number",
			value: data.federalInfo.assistanceListingNumber,
			type: "text",
			section: "Section 7: Assistance Listing Number",
		},
		{
			testId: "federal_action_number",
			value: data.federalInfo.actionNumber,
			type: "text",
			section: "Section 8: Federal Action Number",
		},
		{
			testId: "award_amount",
			value: data.federalInfo.awardAmount,
			type: "text",
			section: "Section 9: Award Amount",
		},
		{
			testId: "lobbying_registrant--individual--first_name",
			value: data.lobbyingRegistrant.firstName,
			type: "text",
			section: "Section 10a: First Name",
		},
		{
			testId: "lobbying_registrant--individual--middle_name",
			value: data.lobbyingRegistrant.middleName,
			type: "text",
			section: "Section 10a: Middle Name",
		},
		{
			testId: "lobbying_registrant--individual--last_name",
			value: data.lobbyingRegistrant.lastName,
			type: "text",
			section: "Section 10a: Last Name",
		},
		{
			testId: "lobbying_registrant--individual--prefix",
			value: data.lobbyingRegistrant.prefix,
			type: "text",
			section: "Section 10a: Prefix",
		},
		{
			testId: "lobbying_registrant--individual--suffix",
			value: data.lobbyingRegistrant.suffix,
			type: "text",
			section: "Section 10a: Suffix",
		},
		{
			testId: "lobbying_registrant--address--street1",
			value: data.lobbyingRegistrant.street1,
			type: "text",
			section: "Section 10a: Street 1",
		},
		{
			testId: "lobbying_registrant--address--street2",
			value: data.lobbyingRegistrant.street2,
			type: "text",
			section: "Section 10a: Street 2",
		},
		{
			testId: "lobbying_registrant--address--city",
			value: data.lobbyingRegistrant.city,
			type: "text",
			section: "Section 10a: City",
		},
		{
			selector: "#lobbying_registrant--address--state",
			value: data.lobbyingRegistrant.state,
			type: "dropdown",
			section: "Section 10a: State",
		},
		{
			testId: "lobbying_registrant--address--zip_code",
			value: data.lobbyingRegistrant.zip,
			type: "text",
			section: "Section 10a: Zip Code",
		},
		{
			testId: "individual_performing_service--individual--first_name",
			value: data.performingService.firstName,
			type: "text",
			section: "Section 10b: First Name",
		},
		{
			testId: "individual_performing_service--individual--middle_name",
			value: data.performingService.middleName,
			type: "text",
			section: "Section 10b: Middle Name",
		},
		{
			testId: "individual_performing_service--individual--last_name",
			value: data.performingService.lastName,
			type: "text",
			section: "Section 10b: Last Name",
		},
		{
			testId: "individual_performing_service--individual--prefix",
			value: data.performingService.prefix,
			type: "text",
			section: "Section 10b: Prefix",
		},
		{
			testId: "individual_performing_service--individual--suffix",
			value: data.performingService.suffix,
			type: "text",
			section: "Section 10b: Suffix",
		},
		{
			testId: "individual_performing_service--address--street1",
			value: data.performingService.street1,
			type: "text",
			section: "Section 10b: Street 1",
		},
		{
			testId: "individual_performing_service--address--street2",
			value: data.performingService.street2,
			type: "text",
			section: "Section 10b: Street 2",
		},
		{
			testId: "individual_performing_service--address--city",
			value: data.performingService.city,
			type: "text",
			section: "Section 10b: City",
		},
		{
			selector: "#individual_performing_service--address--state",
			value: data.performingService.state,
			type: "dropdown",
			section: "Section 10b: State",
		},
		{
			testId: "individual_performing_service--address--zip_code",
			value: data.performingService.zip,
			type: "text",
			section: "Section 10b: Zip Code",
		},
		{
			testId: "signature_block--name--prefix",
			value: data.signature.prefix,
			type: "text",
			section: "Section 11: Prefix",
		},
		{
			testId: "signature_block--name--first_name",
			value: data.signature.firstName,
			type: "text",
			section: "Section 11: First Name",
		},
		{
			testId: "signature_block--name--middle_name",
			value: data.signature.middleName,
			type: "text",
			section: "Section 11: Middle Name",
		},
		{
			testId: "signature_block--name--last_name",
			value: data.signature.lastName,
			type: "text",
			section: "Section 11: Last Name",
		},
		{
			testId: "signature_block--name--suffix",
			value: data.signature.suffix,
			type: "text",
			section: "Section 11: Suffix",
		},
		{
			testId: "signature_block--title",
			value: data.signature.title,
			type: "text",
			section: "Section 11: Title",
		},
		{
			testId: "signature_block--telephone",
			value: data.signature.phone,
			type: "text",
			section: "Section 11: Telephone",
		},
	];
}
