import type { SflllEntityData } from "tests/e2e/apply/fixtures/test-data-for-sflll-forms.fixture";
import { FillFieldDefinition } from "tests/e2e/utils/forms/general-forms-filling";
import { FORM_DEFAULTS } from "tests/e2e/utils/forms/form-defaults";

export const SFLLL_FORM_CONFIG = {
  formName: "Disclosure of Lobbying Activities (SF-LLL)",
  ...FORM_DEFAULTS,
} as const;

export function getSflllFillFields(
  data: SflllEntityData,
): FillFieldDefinition[] {
  return [
    {
      selector: "#federal_action_type",
      value: data.federalAction.type,
      type: "dropdown",
      section: "Section 1",
      field: "Type of Federal Action",
    },
    {
      selector: "#federal_action_status",
      value: data.federalAction.status,
      type: "dropdown",
      section: "Section 2",
      field: "Status of Federal Action",
    },
    {
      selector: "#report_type",
      value: data.federalAction.reportType,
      type: "dropdown",
      section: "Section 3",
      field: "Report Type",
    },
    {
      testId: "material_change_year",
      value: data.materialChange.year,
      type: "text",
      section: "Section 3",
      field: "Material Change Year",
    },
    {
      testId: "material_change_quarter",
      value: data.materialChange.quarter,
      type: "text",
      section: "Section 3",
      field: "Material Change Quarter",
    },
    {
      testId: "last_report_date",
      value: data.materialChange.lastReportDate,
      type: "text",
      section: "Section 3",
      field: "Last Report Date",
    },
    {
      selector: "#reporting_entity--entity_type",
      value: data.reportingEntity.type,
      type: "dropdown",
      section: "Section 4",
      field: "Entity Type",
    },
    {
      testId: "reporting_entity--tier",
      value: data.reportingEntity.tier,
      type: "text",
      section: "Section 4",
      field: "Tier",
    },
    {
      testId: "reporting_entity--applicant_reporting_entity--organization_name",
      value: data.reportingEntity.orgName,
      type: "text",
      section: "Section 4",
      field: "Organization Name",
    },
    {
      testId: "reporting_entity--applicant_reporting_entity--address--street1",
      value: data.reportingEntity.street1,
      type: "text",
      section: "Section 4",
      field: "Street 1",
    },
    {
      testId: "reporting_entity--applicant_reporting_entity--address--street2",
      value: data.reportingEntity.street2,
      type: "text",
      section: "Section 4",
      field: "Street 2",
    },
    {
      testId: "reporting_entity--applicant_reporting_entity--address--city",
      value: data.reportingEntity.city,
      type: "text",
      section: "Section 4",
      field: "City",
    },
    {
      selector: "#reporting_entity--applicant_reporting_entity--address--state",
      value: data.reportingEntity.state,
      type: "dropdown",
      section: "Section 4",
      field: "State",
    },
    {
      testId: "reporting_entity--applicant_reporting_entity--address--zip_code",
      value: data.reportingEntity.zip,
      type: "text",
      section: "Section 4",
      field: "Zip Code",
    },
    {
      testId:
        "reporting_entity--applicant_reporting_entity--congressional_district",
      value: data.reportingEntity.district,
      type: "text",
      section: "Section 4",
      field: "Congressional District",
    },
    {
      testId: "reporting_entity--prime_reporting_entity--organization_name",
      value: data.primeEntity.orgName,
      type: "text",
      section: "Section 5",
      field: "Prime Organization Name",
    },
    {
      testId: "reporting_entity--prime_reporting_entity--address--street1",
      value: data.primeEntity.street1,
      type: "text",
      section: "Section 5",
      field: "Prime Street 1",
    },
    {
      testId: "reporting_entity--prime_reporting_entity--address--street2",
      value: data.primeEntity.street2,
      type: "text",
      section: "Section 5",
      field: "Prime Street 2",
    },
    {
      testId: "reporting_entity--prime_reporting_entity--address--city",
      value: data.primeEntity.city,
      type: "text",
      section: "Section 5",
      field: "Prime City",
    },
    {
      selector: "#reporting_entity--prime_reporting_entity--address--state",
      value: data.primeEntity.state,
      type: "dropdown",
      section: "Section 5",
      field: "Prime State",
    },
    {
      testId: "reporting_entity--prime_reporting_entity--address--zip_code",
      value: data.primeEntity.zip,
      type: "text",
      section: "Section 5",
      field: "Prime Zip Code",
    },
    {
      testId:
        "reporting_entity--prime_reporting_entity--congressional_district",
      value: data.primeEntity.district,
      type: "text",
      section: "Section 5",
      field: "Prime Congressional District",
    },
    {
      testId: "federal_agency_department",
      value: data.federalInfo.agencyDepartment,
      type: "text",
      section: "Section 6",
      field: "Federal Agency/Department",
    },
    {
      testId: "federal_program_name",
      value: data.federalInfo.programName,
      type: "text",
      section: "Section 7",
      field: "Federal Program Name",
    },
    {
      testId: "assistance_listing_number",
      value: data.federalInfo.assistanceListingNumber,
      type: "text",
      section: "Section 7",
      field: "Assistance Listing Number",
    },
    {
      testId: "federal_action_number",
      value: data.federalInfo.actionNumber,
      type: "text",
      section: "Section 8",
      field: "Federal Action Number",
    },
    {
      testId: "award_amount",
      value: data.federalInfo.awardAmount,
      type: "text",
      section: "Section 9",
      field: "Award Amount",
    },
    {
      testId: "lobbying_registrant--individual--first_name",
      value: data.lobbyingRegistrant.firstName,
      type: "text",
      section: "Section 10a",
      field: "First Name",
    },
    {
      testId: "lobbying_registrant--individual--middle_name",
      value: data.lobbyingRegistrant.middleName,
      type: "text",
      section: "Section 10a",
      field: "Middle Name",
    },
    {
      testId: "lobbying_registrant--individual--last_name",
      value: data.lobbyingRegistrant.lastName,
      type: "text",
      section: "Section 10a",
      field: "Last Name",
    },
    {
      testId: "lobbying_registrant--individual--prefix",
      value: data.lobbyingRegistrant.prefix,
      type: "text",
      section: "Section 10a",
      field: "Prefix",
    },
    {
      testId: "lobbying_registrant--individual--suffix",
      value: data.lobbyingRegistrant.suffix,
      type: "text",
      section: "Section 10a",
      field: "Suffix",
    },
    {
      testId: "lobbying_registrant--address--street1",
      value: data.lobbyingRegistrant.street1,
      type: "text",
      section: "Section 10a",
      field: "Street 1",
    },
    {
      testId: "lobbying_registrant--address--street2",
      value: data.lobbyingRegistrant.street2,
      type: "text",
      section: "Section 10a",
      field: "Street 2",
    },
    {
      testId: "lobbying_registrant--address--city",
      value: data.lobbyingRegistrant.city,
      type: "text",
      section: "Section 10a",
      field: "City",
    },
    {
      selector: "#lobbying_registrant--address--state",
      value: data.lobbyingRegistrant.state,
      type: "dropdown",
      section: "Section 10a",
      field: "State",
    },
    {
      testId: "lobbying_registrant--address--zip_code",
      value: data.lobbyingRegistrant.zip,
      type: "text",
      section: "Section 10a",
      field: "Zip Code",
    },
    {
      testId: "individual_performing_service--individual--first_name",
      value: data.performingService.firstName,
      type: "text",
      section: "Section 10b",
      field: "First Name",
    },
    {
      testId: "individual_performing_service--individual--middle_name",
      value: data.performingService.middleName,
      type: "text",
      section: "Section 10b",
      field: "Middle Name",
    },
    {
      testId: "individual_performing_service--individual--last_name",
      value: data.performingService.lastName,
      type: "text",
      section: "Section 10b",
      field: "Last Name",
    },
    {
      testId: "individual_performing_service--individual--prefix",
      value: data.performingService.prefix,
      type: "text",
      section: "Section 10b",
      field: "Prefix",
    },
    {
      testId: "individual_performing_service--individual--suffix",
      value: data.performingService.suffix,
      type: "text",
      section: "Section 10b",
      field: "Suffix",
    },
    {
      testId: "individual_performing_service--address--street1",
      value: data.performingService.street1,
      type: "text",
      section: "Section 10b",
      field: "Street 1",
    },
    {
      testId: "individual_performing_service--address--street2",
      value: data.performingService.street2,
      type: "text",
      section: "Section 10b",
      field: "Street 2",
    },
    {
      testId: "individual_performing_service--address--city",
      value: data.performingService.city,
      type: "text",
      section: "Section 10b",
      field: "City",
    },
    {
      selector: "#individual_performing_service--address--state",
      value: data.performingService.state,
      type: "dropdown",
      section: "Section 10b",
      field: "State",
    },
    {
      testId: "individual_performing_service--address--zip_code",
      value: data.performingService.zip,
      type: "text",
      section: "Section 10b",
      field: "Zip Code",
    },
    {
      testId: "signature_block--name--prefix",
      value: data.signature.prefix,
      type: "text",
      section: "Section 11",
      field: "Prefix",
    },
    {
      testId: "signature_block--name--first_name",
      value: data.signature.firstName,
      type: "text",
      section: "Section 11",
      field: "First Name",
    },
    {
      testId: "signature_block--name--middle_name",
      value: data.signature.middleName,
      type: "text",
      section: "Section 11",
      field: "Middle Name",
    },
    {
      testId: "signature_block--name--last_name",
      value: data.signature.lastName,
      type: "text",
      section: "Section 11",
      field: "Last Name",
    },
    {
      testId: "signature_block--name--suffix",
      value: data.signature.suffix,
      type: "text",
      section: "Section 11",
      field: "Suffix",
    },
    {
      testId: "signature_block--title",
      value: data.signature.title,
      type: "text",
      section: "Section 11",
      field: "Title",
    },
    {
      testId: "signature_block--telephone",
      value: data.signature.phone,
      type: "text",
      section: "Section 11",
      field: "Telephone",
    },
  ];
}
