environment_name = "dev"
tfstate_bucket   = "grants-equity-315341936575-us-east-1-tf"
tfstate_key      = "infra/frontend/service/dev.tfstate"
region           = "us-east-1"
domain           = "beta.grants.gov"
