/**
* @feature Print view validation
* @specFile e2e/apply/submission/specs/submission-print-view.spec.ts
* @description Validates that submitted application data renders correctly in the internal post-submission print view workflow.
*
* NOTE:
* Submitted application creates downloadable ZIP file containing PDF/XML artifacts are generated by the system.
* The validation approach in this workflow verifies the print view output instead of directly validating generated ZIP - PDF artifact.
* The print view acts as a pre-PDF rendering validation layer to confirm submitted application data is rendered correctly.
*/

Feature: Happy Path – Application Submission and Print View Workflow
  As a grant applicant
  I want to complete the full application submission workflow successfully
  So that I can submit a complete application and validate all submitted data in the print view

  Background:
    Given the user is able to login with all required roles
    And the system is available

  @Happy-Path
  Scenario: Complete the Application Submission and Print View workflow for an <user type> user

    # --- Login ---
    Given the user is logged in

    # --- Navigate to Opportunity page ---
    And the user launches the URL for an opportunity with an open competition

    # --- Starting a new Application ---
    When the user clicks "Start Application" on the opportunity page
    Then the "Start a new application" modal opens
    When the <user type> selects <who is applying> in the "Who's applying" dropdown
    And the user enters the application name
    And the user clicks "Create Application"
    Then a new application is created

    # --- Application Landing Page Validation ---
    And the application landing page loads with a list of required and optional forms

    # --- Completing Required Forms ---
    Given the user has completed the required forms

    # --- Completing Conditionally Required Forms (if present) ---
    And the user has completed the conditionally required forms

    # --- Confirm Optional Forms for Submission (if present) ---
    And the user has confirmed optional forms for submission

    # --- Validate Required and Optional Forms ---
    And the required and optional forms contain no validation errors

    # --- Submit Application ---
    When the user submits the application
    Then the application is submitted successfully

    # --- Confirmation Page Validation ---
    And the user validates the confirmation page

    # --- Print View Validation ---
    And the user validates the print view

  Examples:
    | user type    | who is applying           |
    | Organization | Organization A            |
    | Individual   | As an individual (myself) |

# =================================================================
# --- Shared Workflow Details ---
# =================================================================

# --- Search the Opportunity ---
When the user goes to the search page
And the user searches for the specific Funding Opportunity number
Then the user scrolls to the search results table
When the user clicks the Funding Opportunity title
Then the user is taken to the Funding Opportunity details page

# --- Completing Forms (Required or Conditionally Required) ---
Given there are forms in the application forms list

When the user clicks on a form
Then the form opens

And the user completes all required fields
And the user enters unique test data into non-prepopulated fields

# --- Uploading Attachments (if present) ---
When the user uploads a file in any available attachment field
And the user clicks "Choose from folder" or drags and drops the file
Then the file is successfully attached
And the file appears in the appropriate attachment table
 
# --- Saving the Form ---
When the user clicks "Save"
Then no validation errors should appear
And the system saves the form successfully

# --- Capture Form URL ---
And the user copies the current form URL from the browser
And the form URL is in the format:
  /workspace/applications/{applicationId}/form/{appFormId}

# --- Returning to Application Landing Page ---
When the user clicks on the Application Name link
Then the system navigates back to the application landing page

# --- Confirm Optional Forms for Submission (if present) ---
When the user scrolls to the "Conditionally-Required forms" section
And under "Submit with application" the user selects "Yes" for completed optional forms
Then no validation errors should appear
And remaining optional forms have "No" selected

# --- Validate Required and Optional Forms ---
When the user completes all required and optional forms
Then all required and optional forms contain no validation errors

# --- Submit Application ---
When the user clicks "Submit application" with incomplete or invalid fields
Then the system displays validation errors
When the user resolves all validation errors
And the user clicks "Submit application"
Then the system submits the application successfully

# --- Confirmation Page ---
Then the user is taken to the submission confirmation page
And the user sees a confirmation message

# --- Print View Validation ---
When the user constructs the print URL by replacing "workspace/applications" with "/print/application"
Then the print URL should be in the format:
  /print/application/{applicationId}/form/{appFormId}
When the user launches the print URL
Then the print form page loads successfully
And the correct form title is displayed
And no validation or authorization errors appear

# --- Print Data Validation ---
And all unique data entered into the form appears correctly in the print view
And the values entered for each field appear under the correct field titles

# --- Print Rendering Validation ---
When the user opens browser print preview
Then the print layout renders correctly
And no interactive elements break the print layout
And all visible form data appears in the print output
 
