name: Internal - Epic
description: Describe a large body of work that can be broken down into smaller tasks
type: Epic
body:
  - type: textarea
    id: summary
    attributes:
      label: Description
      description: A brief summary that captures how this epic will achieve the goals of a deliverable
    validations:
      required: false

  - type: textarea
    id: success_probability
    attributes:
      label: Risks and assumptions
      description: A brief summary of key risks and assumptions
    validations:
      required: true

