name: Internal - Reoccuring Task - Sam.gov Key Rotation
description: Describe details about updating the sam.gov keys
type: Task
body:
  - type: input
    id: expiration_date
    attributes:
      label: Expiration Date
      description: When are the sam.gov keys expiring that we need to replace?
      placeholder: January 1st, 2000
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: Information
      description: Any additional information
      value: |
        The sam.gov keys in our training and production environments are expiring soon
        and need to be updated before that happens.

        * [Runbook](https://navasage.atlassian.net/wiki/spaces/Grantsgov/pages/2135065043/Updating+Sam.gov+Keys)
    validations:
      required: true

  - type: checkboxes
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: Leave the following acceptance criteria unchecked when the ticket is created then mark them as completed as you meet each criterion
      options:
        - label: We have received a new sam.gov API key in our sam.gov account
        - label: Updated training environment to have new sam.gov API Key
        - label: Updated prod environment to have new sam.gov API Key
        - label: Verified sam.gov jobs ran successfully with new API key
    validations:
      required: false
