name: Install and cache npm and Playwright
description: Composite action to install and cache Playwright

runs:
  using: "composite"

  steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: ${{ env.PACKAGE_MANAGER }}
        cache-dependency-path: ${{ env.LOCKFILE_PATH }}

    - uses: actions/cache@v5
      id: playwright-cache
      with:
        # if cache is missing randomly so instead of being able to just trust the cache existing, we have to download here and push it to an artifact for the next job, by commenting the lookup-only out
        # lookup-only: true
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

    - uses: actions/cache@v5
      id: npm-cache
      with:
        # if cache is missing randomly so instead of being able to just trust the cache existing, we have to download here and push it to an artifact for the next job, by commenting the lookup-only out
        # lookup-only: true
        path: |
          frontend/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

    - id: install-npm-packages
      if: steps.npm-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npm ci

    # 2 of the 4 shards need chrome, so cache that, install the others as needed
    - run: npx playwright install --with-deps chrome
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
    #- run: npx playwright install-deps
    #  if: steps.playwright-cache.outputs.cache-hit != 'true'

    # We package ourselves as tar.gz because this preserves permissions that a regular artifact upload/download does not.
    - name: Package node_modules
      shell: bash
      run: |
        tar -czf /tmp/node_modules.tar.gz ./node_modules/
        ls /tmp

    - name: Upload node_modules artifact
      uses: actions/upload-artifact@v7
      with:
        archive: false
        path: /tmp/node_modules.tar.gz

    # We package ourselves as tar.gz because this preserves permissions that a regular artifact upload/download does not.
    - name: Package Playwright artifact
      shell: bash
      run: |
        cd ~/.cache/ms-playwright
        tar -czf /tmp/playwright.tar.gz .
        ls /tmp

    - name: Upload Playwright artifact
      uses: actions/upload-artifact@v7
      with:
        archive: false
        path: /tmp/playwright.tar.gz
