import uuid

from black import datetime

from src.db.models.competition_models import Form

SF424_v4_0 = Form(
    # legacy form ID - 713
    # https://www.grants.gov/forms/form-items-description/fid/713
    form_id=uuid.UUID("1623b310-85be-496a-b84b-34bdee22a68a"),
    form_name="Application for Federal Assistance (SF-424)",
    form_version="4.0",
    agency_code="SGG",  # TODO - Do we want to add Simpler Grants.gov as an "Agency"?
    omb_number="4040-0004",
    form_json_schema={
        "type": "object",
        "required": [
            "SubmissionType",
            "ApplicationType",
            "DateReceived",
            "OrganizationName",
            "EmployerTaxpayerIdentificationNumber",
            "SAMUEI",
            "Applicant",
            "ContactPerson",
            "PhoneNumber",
            "Email",
            "ApplicantTypeCode",
            "AgencyName",
            "FundingOpportunityNumber",
            "FundingOpportunityTitle",
            "ProjectTitle",
            "CongressionalDistrictApplicant",
            "CongressionalDistrictProgramProject",
            "ProjectStartDate",
            "ProjectEndDate",
            "FederalEstimatedFunding",
            "ApplicantEstimatedFunding",
            "StateEstimatedFunding",
            "LocalEstimatedFunding",
            "OtherEstimatedFunding",
            "ProgramIncomeEstimatedFunding",
            "TotalEstimatedFunding",
            "StateReview",
            "DelinquentFederalDebt",
            "CertificationAgree",
            "AuthorizedRepresentative",
            "AuthorizedRepresentativePhoneNumber",
            "AuthorizedRepresentativeEmail",
            "AORSignature",
            "DateSigned",
        ],
        # Conditional validation rules for SF424
        # TODO - go through .dat and see what I'm missing
        "allOf": [
            # If ApplicationType is Revision, RevisionType + FederalAwardIdentifier are required
            {
                "if": {"properties": {"ApplicationType": {"const": "Revision"}}},
                "then": {"required": ["RevisionType", "FederalAwardIdentifier"]},
            },
            # If ApplicationType is Continuation, FederalAwardIdentifier is required
            {
                "if": {"properties": {"ApplicationType": {"const": "Continuation"}}},
                "then": {"required": ["FederalAwardIdentifier"]},
            },
            # If RevisionType is E, RevisionOtherSpecify becomes required
            {
                "if": {
                    "properties": {"RevisionType": {"const": "E: Other (specify)"}},
                    "required": ["RevisionType"] # Only run rule if RevisionType is set
                },
                "then": {"required": ["RevisionOtherSpecify"]},
            },
            # If DelinquentFederalDebt is True, DebtExplanation is required
            {
                "if": {"properties": {"DelinquentFederalDebt": {"const": True}}},
                "then": {"required": ["DebtExplanation"]},
            },
            # If StateReview is option A, StateReviewAvailableDate is required
            {
                "if": {"properties": {"StateReview": {"const": "a. This application was made available to the State under the Executive Order 12372 Process for review on"}}},
                "then": {"required": ["StateReviewAvailableDate"]},
            },
            # If one of the ApplicantTypeCode values is X: Other, then ApplicantTypeOtherSpecify is required
            {
                "if": {"properties": {"ApplicantTypeCode": {"const": "X: Other (specify)"}}}, # TODO - test this?
                "then": {"required": ["ApplicantTypeOtherSpecify"]},
            },
        ],
        "properties": {
            "SubmissionType": {
                "type": "string",
                "title": "Submission Type",
                "description": "Select one type of submission in accordance with agency instructions. One selection is required.",
                "enum": ["Preapplication", "Application", "Changed/Corrected Application"],
            },
            "ApplicationType": {
                "type": "string",
                "title": "Application Type",
                "description": "Select one type of application in accordance with agency instructions. One selection is required.",
                "enum": ["New", "Continuation", "Revision"],
            },
            "RevisionType": {
                "type": "string",
                "title": "Revision Type",
                "description": "Select a revision type from the list provided.  A selection is required if Type of Application is Revision.",
                "enum": [
                    "A: Increase Award",
                    "B: Decrease Award",
                    "C: Increase Duration",
                    "D: Decrease Duration",
                    "E: Other (specify)",
                    "AC: Increase Award, Increase Duration",
                    "AD: Increase Award, Decrease Duration",
                    "BC: Decrease Award, Increase Duration",
                    "BD: Decrease Award, Decrease Duration",
                ],
            },
            "RevisionOtherSpecify": {
                "type": "string",
                "title": "Other Explanation",
                "description": "Please specify the type of revision.  This field is required if E. Other is checked.",
            },
            "DateReceived": {
                "type": "string",
                "title": "Date Received Header",
                "description": "Completed by Grants.gov upon submission.",
                "format": "date",
                # TODO - post-populated value
            },
            "ApplicantID": {
                "type": "string",
                "title": "Applicant Identifier",
                "description": "Enter the applicant's control number, if applicable.",
                "minLength": 1,
                "maxLength": 30,
                # Based on ApplicantIDDataType
                # https://apply07.grants.gov/apply/system/schemas/GlobalLibrary-V2.0.xsd
                # From the instructions: "Enter the entity identifier assigned by the Federal agency, if any, or the applicant’s control number if applicable."
            },
            "FederalEntityIdentifier": {
                "type": "string",
                "title": "Federal Entity Identifier",
                "minLength": 1,
                "maxLength": 30,
                "description": "Enter the number assigned to your organization by the Federal agency.",
                # Based on FederalIDDataType
                # https://apply07.grants.gov/apply/system/schemas/GlobalLibrary-V2.0.xsd
                # From the instructions: "Enter the number assigned to your organization by the federal agency"
            },
            "FederalAwardIdentifier": {
                "type": "string",
                "title": "Federal Award Identifier",
                "description": "For new applications leave blank. For a continuation or revision to an existing award, enter the previously assigned Federal award identifier number. If a changed/corrected application, enter the Federal Identifier in accordance with agency instructions.",
            },
            "StateReceiveDate": {
                "type": "string",
                "title": "Date Received by State",
                "description": "Enter the date received by the State, if applicable. Enter in the format mm/dd/yyyy.",
                "format": "date",
                "readOnly": True,
                # TODO - this is only used by the state, this should be read-only, right?
            },
            "StateApplicationID": {
                "type": "string",
                "title": "State Application Identifier",
                "description": "Enter the identifier assigned by the State, if applicable.",
                "minLength": 0,
                "maxLength": 30,
                "readOnly": True,
                # TODO - this is only used by the state, this should be read-only, right?
            },
            "OrganizationName": {
                "type": "string",
                "title": "Organization Name",
                "description": "Enter the legal name of the applicant that will undertake the assistance activity. This field is required.",
                "minLength": 1,
                "maxLength": 60,
            },
            "EmployerTaxpayerIdentificationNumber": {
                "type": "string",
                "title": "EIN/TIN",
                "description": "Enter either TIN or EIN as assigned by the Internal Revenue Service.  If your organization is not in the US, enter 44-4444444. This field is required.",
                "minLength": 9,
                "maxLength": 30,
            },
            "SAMUEI": {
                "type": "string",
                "title": "SAM UEI",
                "description": "UEI of the applicant organization. This field is pre-populated from the Application cover sheet.",
                "minLength": 12,
                "maxLength": 12,
                # TODO - pre-populate
            },
            "Applicant": {
                "allOf": [{"$ref": "#/$defs/Address"}],
                "title": "TODO",
                "description": "TODO",
            },
            "DepartmentName": {
                "type": "string",
                "title": "Department Name",
                "description": "Enter the name of primary organizational department, service, laboratory, or equivalent level within the organization which will undertake the assistance activity.",
                "minLength": 1,
                "maxLength": 30,
            },
            "DivisionName": {
                "type": "string",
                "title": "Division Name",
                "description": "Enter the name of primary organizational division, office, or major subdivision which will undertake the assistance activity.",
                "minLength": 1,
                "maxLength": 100,
            },
            "ContactPerson": {
                "allOf": [{"$ref": "#/$defs/PersonName"}],
                "title": "TODO",
                "description": "TODO",
            },
            "OrganizationAffiliation": {
                "type": "string",
                "title": "Organizational Affiliation",
                "description": "Enter the organization if different from the applicant organization.",
                "minLength": 1,
                "maxLength": 60,
            },
            "PhoneNumber": {
                "type": "string",
                "title": "Telephone Number",
                "description": "Enter the daytime Telephone Number. This field is required.",
                "minLength": 1,
                "maxLength": 25,
            },
            "Fax": {
                "type": "string",
                "title": "Fax Number",
                "description": "Enter the Fax Number.",
                "minLength": 1,
                "maxLength": 25,
            },
            "Email": {
                "type": "string",
                "title": "Email",
                "description": "Enter a valid Email Address. This field is required.",
                "format": "email",
            },
            "ApplicantTypeCode": {
                # NOTE: In the xml model, this is 3 separate fields, we joined them together
                # into a single value.
                "type": "array",
                "title": "Type of Applicant",
                "description": "Select the appropriate applicant types. A selection is required.",
                "minItems": 1,
                "maxItems": 3,
                "items": {
                    "type": "string",
                    "enum": [
                        "A: State Government",
                        "B: County Government",
                        "C: City or Township Government",
                        "D: Special District Government",
                        "E: Regional Organization",
                        "F: U.S. Territory or Possession",
                        "G: Independent School District",
                        "H: Public/State Controlled Institution of Higher Education",
                        "I: Indian/Native American Tribal Government (Federally Recognized)",
                        "J: Indian/Native American Tribal Government (Other than Federally Recognized)",
                        "K: Indian/Native American Tribally Designated Organization",
                        "L: Public/Indian Housing Authority",
                        "M: Nonprofit with 501C3 IRS Status (Other than Institution of Higher Education)",
                        "N: Nonprofit without 501C3 IRS Status (Other than Institution of Higher Education)",
                        "O: Private Institution of Higher Education",
                        "P: Individual",
                        "Q: For-Profit Organization (Other than Small Business)",
                        "R: Small Business",
                        "S: Hispanic-serving Institution",
                        "T: Historically Black Colleges and Universities (HBCUs)",
                        "U: Tribally Controlled Colleges and Universities (TCCUs)",
                        "V: Alaska Native and Native Hawaiian Serving Institutions",
                        "W: Non-domestic (non-US) Entity",
                        "X: Other (specify)",
                    ],
                },
            },
            "ApplicantTypeOtherSpecify": {
                # TODO - required if Other is chosen above
                "type": "string",
                "title": "Type of Applicant Other Explanation",
                "description": 'Enter the applicant type here if you selected "Other (specify)" for Type of Applicant.',
                "minLength": 0,
                "maxLength": 30,
            },
            "AgencyName": {
                "type": "string",
                "title": "Agency Name",
                "description": "Pre-populated from the Application cover sheet.",
                "minLength": 1,
                "maxLength": 60,
                # TODO - prepopulate
            },
            "CFDANumber": {
                "type": "string",
                "title": "Assistance Listing Number",
                "description": "Pre-populated from the Application cover sheet.",
                "minLength": 1,
                "maxLength": 15,
                # TODO - prepopulate
            },
            "CFDAProgramTitle": {
                "type": "string",
                "title": "Assistance Listing Title",
                "description": "Pre-populated from the Application cover sheet.",
                "minLength": 1,
                "maxLength": 120,
                # TODO - prepopulate
            },
            "FundingOpportunityNumber": {
                "type": "string",
                "title": "Opportunity Number",
                "description": "Pre-populated from the Application cover sheet. This field is required.",
                "minLength": 1,
                "maxLength": 40,
                # TODO - prepopulate
            },
            "FundingOpportunityTitle": {
                "type": "string",
                "title": "Opportunity Title",
                "description": "Pre-populated from the Application cover sheet. This field is required.",
                "minLength": 1,
                "maxLength": 255,
                # TODO - prepopulate
            },
            "CompetitionIdentificationNumber": {
                "type": "string",
                "title": "Competition Number",
                "description": "Pre-populated from the Application cover sheet.",
                "minLength": 1,
                "maxLength": 40,
                # TODO - prepopulate
            },
            "CompetitionIdentificationTitle": {
                "type": "string",
                "title": "Competition Title",
                "description": "Pre-populated from the Application cover sheet.",
                "minLength": 1,
                "maxLength": 255,
                # TODO - prepopulate
            },
            "AreasAffected": {
                # TODO - attachment validation
                # TODO - make an attachment we can use allOf against
                "type": "string",
                "format": "uuid",
                "title": "Areas Affected",
                "description": "List the areas or entities using the categories (e.g., cities, counties, states, etc.) specified in agency instructions.",
            },
            "ProjectTitle": {
                "type": "string",
                "title": "Project Title",
                "description": "Enter a brief, descriptive title of the project. This field is required.",
                "minLength": 1,
                "maxLength": 200,
            },
            "AdditionalProjectTitle": {
                # TODO - attachment validation (why is that the name of this field?)
                "type": "array",
                "title": "Additional Project Title",
                "description": "Attach file(s) using the appropriate buttons.",
                "maxItems": 100,
                "items": {"type": "string", "format": "uuid"},
            },
            "CongressionalDistrictApplicant": {
                "type": "string",
                "title": "Applicant District",
                "description": "Enter the Congressional District in the format: 2 character State Abbreviation - 3 character District Number. Examples: CA-005 for California's 5th district, CA-012 for California's 12th district.If outside the US, enter 00-000.This field is required.",
                "minLength": 1,
                "maxLength": 6,
            },
            "CongressionalDistrictProgramProject": {
                "type": "string",
                "title": "Program District",
                "description": "Enter the Congressional District in the format: 2 character State Abbreviation - 3 character District Number. Examples: CA-005 for California's 5th district, CA-012 for California's 12th district.If all districts in a state are affected, enter \"all\" for the district number. Example: MD-all for all congressional districts in Maryland.If nationwide (all districts in all states), enter US-all.If the program/project is outside the US, enter 00-000.This field is required.",
                "minLength": 1,
                "maxLength": 6,
            },
            "AdditionalCongressionalDistricts": {
                # TODO - attachment validation
                "type": "string",
                "format": "uuid",
                "title": "Additional Congressional Districts",
                "description": "Additional Congressional Districts.",
            },
            "ProjectStartDate": {
                "type": "string",
                "title": "Project Start Date",
                "description": "Enter the date in the format MM/DD/YYYY.  This field is required.",
                "format": "date",
            },
            "ProjectEndDate": {
                "type": "string",
                "title": "Project End Date",
                "description": "Enter the date in the format MM/DD/YYYY.  This field is required.",
                "format": "date",
            },
            "FederalEstimatedFunding": {
                "allOf": [{"$ref": "#/$defs/BudgetMonetaryAmount"}],
                "title": "Federal Estimated Funding",
                "description": "Enter the dollar amount. This field is required.",
            },
            "ApplicantEstimatedFunding": {
                "allOf": [{"$ref": "#/$defs/BudgetMonetaryAmount"}],
                "title": "Applicant Estimated Funding",
                "description": "Enter the dollar amount. This field is required.",
            },
            "StateEstimatedFunding": {
                "allOf": [{"$ref": "#/$defs/BudgetMonetaryAmount"}],
                "title": "State Estimated Funding",
                "description": "Enter the dollar amount. This field is required.",
            },
            "LocalEstimatedFunding": {
                "allOf": [{"$ref": "#/$defs/BudgetMonetaryAmount"}],
                "title": "Local Estimated Funding",
                "description": "Enter the dollar amount. This field is required.",
            },
            "OtherEstimatedFunding": {
                "allOf": [{"$ref": "#/$defs/BudgetMonetaryAmount"}],
                "title": "Other Estimated Funding",
                "description": "Enter the dollar amount. This field is required.",
            },
            "ProgramIncomeEstimatedFunding": {
                "allOf": [{"$ref": "#/$defs/BudgetMonetaryAmount"}],
                "title": "Program Income Estimated Funding",
                "description": "Enter the dollar amount. This field is required.",
            },
            "TotalEstimatedFunding": {
                "allOf": [{"$ref": "#/$defs/BudgetMonetaryAmount"}],
                "title": "Total Estimated Funding",
                "description": "Total dollar amount. This is a calculated field.",
            },
            "StateReview": {
                "type": "string",
                "title": "Application Subject to Review",
                "description": "One selection is required.",
                "enum": [
                    "a. This application was made available to the State under the Executive Order 12372 Process for review on",
                    "b. Program is subject to E.O. 12372 but has not been selected by the State for review.",
                    "c. Program is not covered by E.O. 12372.",
                ],
            },
            "StateReviewAvailableDate": {
                "type": "string",
                "title": "State Review Date",
                "description": "Enter the date in the format MM/DD/YYYY.",
                "format": "date",
            },
            "DelinquentFederalDebt": {
                # TODO - verify with frontend that we can make a bool be a yes/no easily enough
                # or should we make this literally yes/no?
                "type": "boolean",
                "title": "Applicant Delinquent on Federal Debt",
                "description": "A selection is required.",
            },
            "DebtExplanation": {
                # TODO - attachment ID validation allOf
                "type": "string",
                "format": "uuid",
                "title": "Debt Explanation",
                "description": "Debt Explanation is required.",
            },
            "CertificationAgree": {
                "type": "boolean",
                "title": "Certification Agree",
                "description": "Check to select. This field is required.",
            },
            "AuthorizedRepresentative": {
                "allOf": [{"$ref": "#/$defs/PersonName"}],
                "title": "Authorized Representative Header",
                "description": "",
            },
            "AuthorizedRepresentativePhoneNumber": {
                # TODO - add a phone number allOf
                "type": "string",
                "title": "AOR Telephone Number",
                "description": "Enter the daytime Telephone Number. This field is required.",
                "minLength": 1,
                "maxLength": 25,
            },
            "AuthorizedRepresentativeFax": {
                "type": "string",
                "title": "AOR Fax Number",
                "description": "Enter the Fax Number.",
                "minLength": 1,
                "maxLength": 25,
            },
            "AuthorizedRepresentativeEmail": {
                "type": "string",
                "format": "email",
                "title": "AOR Email",
                "description": "Enter a valid Email Address. This field is required.",
            },
            "AORSignature": {
                "type": "string",
                "title": "AOR Signature",
                "description": "Completed by Grants.gov upon submission.",
                "minLength": 1,
                "maxLength": 144,
            },
            "DateSigned": {
                "type": "string",
                "format": "date",
                "title": "Date Signed",
                "description": "Completed by Grants.gov upon submission.",
            },
        },
        "$defs": {
            "Address": {
                "type": "object",
                # TODO - text here
                "title": "Address Header",
                "description": "",
                "required": [
                    "Street1",
                    "City",
                    "Country",
                ],
                # Conditional validation rules for an address field
                "allOf": [
                    # If country is United States, State and ZipCode are required
                    {
                        "if": {"properties": {"Country": {"const": "USA: UNITED STATES"}}},
                        "then": {"required": ["State", "ZipCode"]},
                    },
                ],
                "properties": {
                    "Street1": {
                        "type": "string",
                        "title": "Street1",
                        "description": "Enter the first line of the Street Address. This field is required.",
                        "minLength": 1,
                        "maxLength": 55,
                    },
                    "Street2": {
                        "type": "string",
                        "title": "Street2",
                        "description": "Enter the second line of the Street Address.",
                        "minLength": 1,
                        "maxLength": 55,
                    },
                    "City": {
                        "type": "string",
                        "title": "City",
                        "description": "Enter the City. This field is required.",
                        "minLength": 1,
                        "maxLength": 35,
                    },
                    "County": {
                        "type": "string",
                        "title": "County/Parish",
                        "description": "Enter the County/Parish.",
                        "minLength": 1,
                        "maxLength": 30,
                    },
                    "State": {
                        "allOf": [{"$ref": "#/$defs/StateCode"}],
                        "title": "State",
                        "description": "Enter the State.",
                    },
                    "Province": {
                        "type": "string",
                        "title": "Province",
                        "description": "Enter the Province.",
                        "minLength": 1,
                        "maxLength": 30,
                        # Note that grants.gov would hide this if the country isn't USA, but it isn't required even then
                    },
                    "Country": {"$ref": "#/$defs/CountryCode"},
                    "ZipCode": {
                        "type": "string",
                        "title": "Zip / Postal Code",
                        "description": "Enter the nine-digit Postal Code (e.g., ZIP code). This field is required if the country is the United States.",
                    },
                },
            },
            "PersonName": {
                "type": "object",
                "title": "Name and Contact Information Header",
                "description": "",
                "required": [
                    "FirstName",
                    "LastName",
                ],
                "properties": {
                    "Prefix": {
                        "type": "string",
                        "title": "Prefix",
                        # TODO - this doesn't have an enum?
                        "description": "Select the Prefix from the provided list or enter a new Prefix not provided on the list.",
                        "minLength": 1,
                        "maxLength": 10,
                    },
                    "FirstName": {
                        "type": "string",
                        "title": "First Name",
                        "description": "Enter the First Name. This field is required.",
                        "minLength": 1,
                        "maxLength": 35,
                    },
                    "MiddleName": {
                        "type": "string",
                        "title": "Middle Name",
                        "description": "Enter the Middle Name.",
                        "minLength": 1,
                        "maxLength": 25,
                    },
                    "LastName": {
                        "type": "string",
                        "title": "Last Name",
                        "description": "Enter the Last Name. This field is required.",
                        "minLength": 1,
                        "maxLength": 60,
                    },
                    "Suffix": {
                        "type": "string",
                        "title": "Suffix",
                        "description": "Select the Suffix from the provided list or enter a new Suffix not provided on the list.",
                        "minLength": 1,
                        "maxLength": 10,
                    },
                    "Title": {
                        # TODO - this isn't in this part of the model of the SF424, but is in the global lib
                        "type": "string",
                        "title": "Title",
                        "description": "Enter the position title.",
                        "minLength": 1,
                        "maxLength": 45,
                    },
                },
            },
            "BudgetMonetaryAmount": {
                # Represents a monetary amount. We use a string instead of number
                # to avoid any floating point rounding issues.
                "type": "string",
                # Pattern here effectively says:
                # * Must start with a digit 1-9 (no negative, no currency symbol, no leading 0s)
                # * Then any number of digits
                # * A decimal point
                # * Then exactly 2 digits
                "pattern": "^[1-9]\d*([.]\d{2})?$", # TODO - getting a warning with this
                # Limit the max amount based on the length (11-digits, allows up to 99 billion)
                "maxLength": 14,
            },
            "StateCode": {
                "type": "string",
                "title": "State",
                "description": "US State or Territory Code",
                "enum": [
                    "AL: Alabama",
                    "AK: Alaska",
                    "AZ: Arizona",
                    "AR: Arkansas",
                    "CA: California",
                    "CO: Colorado",
                    "CT: Connecticut",
                    "DE: Delaware",
                    "DC: District of Columbia",
                    "FL: Florida",
                    "GA: Georgia",
                    "HI: Hawaii",
                    "ID: Idaho",
                    "IL: Illinois",
                    "IN: Indiana",
                    "IA: Iowa",
                    "KS: Kansas",
                    "KY: Kentucky",
                    "LA: Louisiana",
                    "ME: Maine",
                    "MD: Maryland",
                    "MA: Massachusetts",
                    "MI: Michigan",
                    "MN: Minnesota",
                    "MS: Mississippi",
                    "MO: Missouri",
                    "MT: Montana",
                    "NE: Nebraska",
                    "NV: Nevada",
                    "NH: New Hampshire",
                    "NJ: New Jersey",
                    "NM: New Mexico",
                    "NY: New York",
                    "NC: North Carolina",
                    "ND: North Dakota",
                    "OH: Ohio",
                    "OK: Oklahoma",
                    "OR: Oregon",
                    "PA: Pennsylvania",
                    "RI: Rhode Island",
                    "SC: South Carolina",
                    "SD: South Dakota",
                    "TN: Tennessee",
                    "TX: Texas",
                    "UT: Utah",
                    "VT: Vermont",
                    "VA: Virginia",
                    "WA: Washington",
                    "WV: West Virginia",
                    "WI: Wisconsin",
                    "WY: Wyoming",
                    "AS: American Samoa",
                    "FM: Federated States of Micronesia",
                    "GU: Guam",
                    "MH: Marshall Islands",
                    "MP: Northern Mariana Islands",
                    "PW: Palau",
                    "PR: Puerto Rico",
                    "VI: Virgin Islands",
                    "FQ: Baker Island",
                    "HQ: Howland Island",
                    "DQ: Jarvis Island",
                    "JQ: Johnston Atoll",
                    "KQ: Kingman Reef",
                    "MQ: Midway Islands",
                    "BQ: Navassa Island",
                    "LQ: Palmyra Atoll",
                    "WQ: Wake Island",
                    "AA: Armed Forces Americas (except Canada)",
                    "AE: Armed Forces Europe, the Middle East, and Canada",
                    "AP: Armed Forces Pacific",
                ],
            },
            "CountryCode": {
                "type": "string",
                "title": "Country",
                "description": "Country Code",
                "enum": [
                    "AFG: AFGHANISTAN",
                    "XQZ: AKROTIRI",
                    "ALB: ALBANIA",
                    "DZA: ALGERIA",
                    "AND: ANDORRA",
                    "AGO: ANGOLA",
                    "AIA: ANGUILLA",
                    "ATA: ANTARCTICA",
                    "ATG: ANTIGUA AND BARBUDA",
                    "ARG: ARGENTINA",
                    "ARM: ARMENIA",
                    "ABW: ARUBA",
                    "XAC: ASHMORE AND CARTIER ISLANDS",
                    "AUS: AUSTRALIA",
                    "AUT: AUSTRIA",
                    "AZE: AZERBAIJAN",
                    "BHS: BAHAMAS, THE",
                    "BHR: BAHRAIN",
                    "BGD: BANGLADESH",
                    "BRB: BARBADOS",
                    "XBI: BASSAS DA INDIA",
                    "BLR: BELARUS",
                    "BEL: BELGIUM",
                    "BLZ: BELIZE",
                    "BEN: BENIN",
                    "BMU: BERMUDA",
                    "BTN: BHUTAN",
                    "BOL: BOLIVIA",
                    "BES: BONAIRE, SINT EUSTATIUS, AND SABA",
                    "BIH: BOSNIA AND HERZEGOVINA",
                    "BWA: BOTSWANA",
                    "BVT: BOUVET ISLAND",
                    "BRA: BRAZIL",
                    "IOT: BRITISH INDIAN OCEAN TERRITORY",
                    "BRN: BRUNEI",
                    "BGR: BULGARIA",
                    "BFA: BURKINA FASO",
                    "MMR: BURMA",
                    "BDI: BURUNDI",
                    "CPV: CABO VERDE",
                    "KHM: CAMBODIA",
                    "CMR: CAMEROON",
                    "CAN: CANADA",
                    "CYM: CAYMAN ISLANDS",
                    "CAF: CENTRAL AFRICAN REPUBLIC",
                    "TCD: CHAD",
                    "CHL: CHILE",
                    "CHN: CHINA",
                    "CXR: CHRISTMAS ISLAND",
                    "CPT: CLIPPERTON ISLAND",
                    "CCK: COCOS (KEELING) ISLANDS",
                    "COL: COLOMBIA",
                    "COM: COMOROS",
                    "COG: CONGO (BRAZZAVILLE)",
                    "COD: CONGO (KINSHASA)",
                    "COK: COOK ISLANDS",
                    "XCS: CORAL SEA ISLANDS",
                    "CRI: COSTA RICA",
                    # TODO - char
                    "CIV: COTE D'IVOIRE",
                    "HRV: CROATIA",
                    "CUB: CUBA",
                    # TODO - char
                    "CUW: CURACAO",
                    "CYP: CYPRUS",
                    "CZE: CZECHIA",
                    "DNK: DENMARK",
                    "XXD: DHEKELIA",
                    "DGA: DIEGO GARCIA",
                    "DJI: DJIBOUTI",
                    "DMA: DOMINICA",
                    "DOM: DOMINICAN REPUBLIC",
                    "ECU: ECUADOR",
                    "EGY: EGYPT",
                    "SLV: EL SALVADOR",
                    "XAZ: ENTITY 1",
                    "XCR: ENTITY 2",
                    "XCY: ENTITY 3",
                    "XKM: ENTITY 4",
                    "XKN: ENTITY 5",
                    "AX3: ENTITY 6",
                    "GNQ: EQUATORIAL GUINEA",
                    "ERI: ERITREA",
                    "EST: ESTONIA",
                    "SWZ: ESWATINI",
                    "ETH: ETHIOPIA",
                    "XEU: EUROPA ISLAND",
                    "FLK: FALKLAND ISLANDS (ISLAS MALVINAS)",
                    "FRO: FAROE ISLANDS",
                    "FJI: FIJI",
                    "FIN: FINLAND",
                    "FRA: FRANCE",
                    "GUF: FRENCH GUIANA",
                    "PYF: FRENCH POLYNESIA",
                    "ATF: FRENCH SOUTHERN AND ANTARCTIC LANDS",
                    "GAB: GABON",
                    "GMB: GAMBIA, THE",
                    "XGZ: GAZA STRIP",
                    "GEO: GEORGIA",
                    "DEU: GERMANY",
                    "GHA: GHANA",
                    "GIB: GIBRALTAR",
                    "XGL: GLORIOSO ISLANDS",
                    "GRC: GREECE",
                    "GRL: GREENLAND",
                    "GRD: GRENADA",
                    "GLP: GUADELOUPE",
                    "GTM: GUATEMALA",
                    "GGY: GUERNSEY",
                    "GIN: GUINEA",
                    "GNB: GUINEA-BISSAU",
                    "GUY: GUYANA",
                    "HTI: HAITI",
                    "HMD: HEARD ISLAND AND MCDONALD ISLANDS",
                    "HND: HONDURAS",
                    "HKG: HONG KONG",
                    "HUN: HUNGARY",
                    "ISL: ICELAND",
                    "IND: INDIA",
                    "IDN: INDONESIA",
                    "IRN: IRAN",
                    "IRQ: IRAQ",
                    "IRL: IRELAND",
                    "IMN: ISLE OF MAN",
                    "ISR: ISRAEL",
                    "ITA: ITALY",
                    "JAM: JAMAICA",
                    "XJM: JAN MAYEN",
                    "JPN: JAPAN",
                    "JEY: JERSEY",
                    "JOR: JORDAN",
                    "XJN: JUAN DE NOVA ISLAND",
                    "KAZ: KAZAKHSTAN",
                    "KEN: KENYA",
                    "KIR: KIRIBATI",
                    "PRK: KOREA, NORTH",
                    "KOR: KOREA, SOUTH",
                    "XKS: KOSOVO",
                    "KWT: KUWAIT",
                    "KGZ: KYRGYZSTAN",
                    "LAO: LAOS",
                    "LVA: LATVIA",
                    "LBN: LEBANON",
                    "LSO: LESOTHO",
                    "LBR: LIBERIA",
                    "LBY: LIBYA",
                    "LIE: LIECHTENSTEIN",
                    "LTU: LITHUANIA",
                    "LUX: LUXEMBOURG",
                    "MAC: MACAU",
                    "MDG: MADAGASCAR",
                    "MWI: MALAWI",
                    "MYS: MALAYSIA",
                    "MDV: MALDIVES",
                    "MLI: MALI",
                    "MLT: MALTA",
                    "MTQ: MARTINIQUE",
                    "MRT: MAURITANIA",
                    "MUS: MAURITIUS",
                    "MYT: MAYOTTE",
                    "MEX: MEXICO",
                    "MDA: MOLDOVA",
                    "MCO: MONACO",
                    "MNG: MONGOLIA",
                    "MNE: MONTENEGRO",
                    "MSR: MONTSERRAT",
                    "MAR: MOROCCO",
                    "MOZ: MOZAMBIQUE",
                    "NAM: NAMIBIA",
                    "NRU: NAURU",
                    "NPL: NEPAL",
                    "NLD: NETHERLANDS",
                    "NCL: NEW CALEDONIA",
                    "NZL: NEW ZEALAND",
                    "NIC: NICARAGUA",
                    "NER: NIGER",
                    "NGA: NIGERIA",
                    "NIU: NIUE",
                    "NFK: NORFOLK ISLAND",
                    "MKD: NORTH MACEDONIA",
                    "NOR: NORWAY",
                    "OMN: OMAN",
                    "PAK: PAKISTAN",
                    "PAN: PANAMA",
                    "PNG: PAPUA NEW GUINEA",
                    "XPR: PARACEL ISLANDS",
                    "PRY: PARAGUAY",
                    "PER: PERU",
                    "PHL: PHILIPPINES",
                    "PCN: PITCAIRN ISLANDS",
                    "POL: POLAND",
                    "PRT: PORTUGAL",
                    "QAT: QATAR",
                    "REU: REUNION",
                    "ROU: ROMANIA",
                    "RUS: RUSSIA",
                    "RWA: RWANDA",
                    "BLM: SAINT BARTHELEMY",
                    "SHN: SAINT HELENA, ASCENSION, AND TRISTAN DA CUNHA",
                    "KNA: SAINT KITTS AND NEVIS",
                    "LCA: SAINT LUCIA",
                    "MAF: SAINT MARTIN",
                    "SPM: SAINT PIERRE AND MIQUELON",
                    "VCT: SAINT VINCENT AND THE GRENADINES",
                    "WSM: SAMOA",
                    "SMR: SAN MARINO",
                    "STP: SAO TOME AND PRINCIPE",
                    "SAU: SAUDI ARABIA",
                    "SEN: SENEGAL",
                    "SRB: SERBIA",
                    "SYC: SEYCHELLES",
                    "SLE: SIERRA LEONE",
                    "SGP: SINGAPORE",
                    "SXM: SINT MAARTEN",
                    "SVK: SLOVAKIA",
                    "SVN: SLOVENIA",
                    "SLB: SOLOMON ISLANDS",
                    "SOM: SOMALIA",
                    "ZAF: SOUTH AFRICA",
                    "SGS: SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS",
                    "SSD: SOUTH SUDAN",
                    "ESP: SPAIN",
                    "XSP: SPRATLY ISLANDS",
                    "LKA: SRI LANKA",
                    "SDN: SUDAN",
                    "SUR: SURINAME",
                    "XSV: SVALBARD",
                    "SWE: SWEDEN",
                    "CHE: SWITZERLAND",
                    "SYR: SYRIA",
                    "TWN: TAIWAN",
                    "TJK: TAJIKISTAN",
                    "TZA: TANZANIA",
                    "THA: THAILAND",
                    "TLS: TIMOR-LESTE",
                    "TGO: TOGO",
                    "TKL: TOKELAU",
                    "TON: TONGA",
                    "TTO: TRINIDAD AND TOBAGO",
                    "XTR: TROMELIN ISLAND",
                    "TUN: TUNISIA",
                    "TUR: TURKEY",
                    "TKM: TURKMENISTAN",
                    "TCA: TURKS AND CAICOS ISLANDS",
                    "TUV: TUVALU",
                    "UGA: UGANDA",
                    "UKR: UKRAINE",
                    "ARE: UNITED ARAB EMIRATES",
                    "GBR: UNITED KINGDOM",
                    "USA: UNITED STATES",
                    "URY: URUGUAY",
                    "UZB: UZBEKISTAN",
                    "VUT: VANUATU",
                    "VAT: VATICAN CITY",
                    "VEN: VENEZUELA",
                    "VNM: VIETNAM",
                    "VGB: VIRGIN ISLANDS, BRITISH",
                    "WLF: WALLIS AND FUTUNA",
                    "XWB: WEST BANK",
                    "ESH: WESTERN SAHARA",
                    "YEM: YEMEN",
                    "ZMB: ZAMBIA",
                    "ZWE: ZIMBABWE",
                ],
            },
        },
    },
    # form_rule_schema={}, # TODO - once merged in
    form_ui_schema={},
    # TODO - form instructions?
)
