name: "Set up Terraform"
description: "Set up Terraform with the version stored in the .terraform-version file"
runs:
  using: "composite"
  steps:
    - name: Get .terraform-version
      id: get-terraform-version
      run: |
        terraform_version="$(cat .terraform-version)"
        echo "Terraform version: ${terraform_version}"
        echo "terraform_version=${terraform_version}" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ steps.get-terraform-version.outputs.terraform_version }}
        terraform_wrapper: false
