import io
import logging
import os
import re
import tempfile
import zipfile

import click
import requests

import src.adapters.db as db
import src.logging
import tests.src.db.models.factories as factories
from src.adapters.db import PostgresDBClient
from src.legacy_soap_api.legacy_soap_api_config import SimplerSoapAPI
from src.legacy_soap_api.legacy_soap_api_schemas import SOAPRequest, SOAPResponse
from src.legacy_soap_api.legacy_soap_api_utils import get_alternate_proxy_response
from src.legacy_soap_api.simpler_soap_api import get_simpler_soap_response
from src.util.local import error_if_not_local

logger = logging.getLogger(__name__)


"""
Add following to soap-api.env
CERT_DATA_ENCODED =
KEY_DATA_ENCODED =
SOAP_URI =
For cert and key use awk command to replace newlines
`awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;} bps_grantors.crt`
`awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;} bps_grantors.key`
To run use: `docker compose run --rm grants-api poetry run compare-soap-endpoints`
"""
CERT_DATA_ENCODED = os.getenv("CERT_DATA")
KEY_DATA_ENCODED = os.getenv("KEY_DATA")
SOAP_URI = os.getenv("SOAP_URI", b"")
HEADERS = {"Content-Type": "application/xml"}

if CERT_DATA_ENCODED and KEY_DATA_ENCODED:
    CERT_DATA = CERT_DATA_ENCODED.replace("\\n", "\n")
    KEY_DATA = KEY_DATA_ENCODED.replace("\\n", "\n")
else:
    raise Exception("No cert data")
with tempfile.NamedTemporaryFile(delete=False) as temp_cert_file:
    temp_cert_file.write(CERT_DATA.encode("utf-8"))
    CERT = temp_cert_file.name
with tempfile.NamedTemporaryFile(delete=False) as temp_key_file:
    temp_key_file.write(KEY_DATA.encode("utf-8"))
    KEY = temp_key_file.name


def get_grantors_get_application_zip_request_data(gov_grants_tracking_number: str) -> bytes:
    return (
        '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:agen="http://apply.grants.gov/services/AgencyWebServices-V2.0" xmlns:gran="http://apply.grants.gov/system/GrantsCommonElements-V1.0">'
        "<soapenv:Header/>"
        "<soapenv:Body>"
        "<agen:GetApplicationZipRequest>"
        f"<gran:GrantsGovTrackingNumber>{gov_grants_tracking_number}</gran:GrantsGovTrackingNumber>"
        "</agen:GetApplicationZipRequest>"
        "</soapenv:Body>"
        "</soapenv:Envelope>"
    ).encode("utf-8")


def check_grantor_get_application_zip_request_not_found(db_session: db.Session) -> None:
    """
    Get legacy xml
    """
    legacy_tracking_number = "GRANT60000001"
    legacy_resp = requests.post(
        SOAP_URI,
        data=get_grantors_get_application_zip_request_data(legacy_tracking_number),
        headers=HEADERS,
        cert=(CERT, KEY),
    )
    assert legacy_resp.status_code == 500
    legacy_match = re.search(
        r"<soap:Envelope.*</soap:Envelope>", legacy_resp.content.decode(), re.DOTALL
    )
    if not legacy_match:
        raise AssertionError("No legacy response")

    """
    Get xml from simpler
    """
    simpler_tracking_number = "GRANT80000001"
    soap_request = SOAPRequest(
        api_name=SimplerSoapAPI.GRANTORS,
        method="POST",
        full_path=SOAP_URI,
        headers=HEADERS,
        data=get_grantors_get_application_zip_request_data(simpler_tracking_number),
        operation_name="GetApplicationZipRequest",
    )
    simpler_resp = get_alternate_proxy_response(soap_request)
    if simpler_resp is None:
        raise AssertionError("No simpler response found")
    simpler_xml = simpler_resp.to_flask_response()[0]
    simpler_match = re.search(r"<soap:Envelope.*</soap:Envelope>", simpler_xml.decode(), re.DOTALL)
    if not simpler_match:
        raise AssertionError("No xml found")

    """
    Compare the cleaned xml output from the legacy endpoint to the cleaned xml generated by simpler
    """
    pattern = r"tracking number:(.*?)\)"
    simpler_xml = simpler_match.group(0)
    legacy_xml = legacy_match.group(0)
    cleaned_legacy = re.sub(pattern, "tracking number:", legacy_xml, flags=re.DOTALL)
    cleaned_simpler = re.sub(pattern, "tracking number:", simpler_xml, flags=re.DOTALL)
    assert cleaned_legacy == cleaned_simpler


def check_grantors_get_application_zip_request(db_session: db.Session) -> None:
    legacy_tracking_number = "GRANT00837982"
    legacy_resp = requests.post(
        SOAP_URI,
        data=get_grantors_get_application_zip_request_data(legacy_tracking_number),
        headers=HEADERS,
        cert=(CERT, KEY),
    )
    assert legacy_resp.status_code == 200
    match = re.search(rb"<soap:Envelope.*</soap:Envelope>", legacy_resp.content, re.DOTALL)
    if not match:
        raise AssertionError("No legacy response")
    legacy_xml = match.group(0)

    simpler_tracking_number = "GRANT80000001"
    soap_request = SOAPRequest(
        api_name=SimplerSoapAPI.GRANTORS,
        method="POST",
        full_path=SOAP_URI,
        headers=HEADERS,
        data=get_grantors_get_application_zip_request_data(simpler_tracking_number),
        operation_name="GetApplicationZipRequest",
    )
    simpler_resp = get_simpler_soap_response(
        soap_request, SOAPResponse(data=b"", headers=HEADERS, status_code="500"), db_session
    )
    simpler_xml = simpler_resp.to_flask_response()[0]

    pattern = b"(cid:).*(@)"
    cleaned_legacy = re.sub(pattern, b"cid:", legacy_xml, flags=re.DOTALL)
    cleaned_simpler = re.sub(pattern, b"cid:", simpler_xml, flags=re.DOTALL)
    assert cleaned_legacy == cleaned_simpler
    zip_buffer = io.BytesIO(simpler_xml)
    with zipfile.ZipFile(zip_buffer, "r") as zip_file:
        assert zip_file.testzip() is None


@click.command()
def compare_endpoints() -> None:
    print("=start=")
    with src.logging.init("seed_local_db"):
        logger.info("Running seed script for local DB")
        error_if_not_local()

        db_client = PostgresDBClient()
        with db_client.get_session() as db_session:
            factories._db_session = db_session
            CHECKS = {
                "Grantor GetApplicationZipRequest Not Found": check_grantor_get_application_zip_request_not_found,
                "Grantor GetApplicationZipRequest": check_grantors_get_application_zip_request,
            }
            for msg, check in CHECKS.items():
                print("=" * 25)
                print(f"{msg} started")
                check(db_session)
                print(f"{msg} passed")
    print("=end=")
