STATES = [
    "AL: Alabama",
    "AK: Alaska",
    "AZ: Arizona",
    "AR: Arkansas",
    "CA: California",
    "CO: Colorado",
    "CT: Connecticut",
    "DE: Delaware",
    "DC: District of Columbia",
    "FL: Florida",
    "GA: Georgia",
    "HI: Hawaii",
    "ID: Idaho",
    "IL: Illinois",
    "IN: Indiana",
    "IA: Iowa",
    "KS: Kansas",
    "KY: Kentucky",
    "LA: Louisiana",
    "ME: Maine",
    "MD: Maryland",
    "MA: Massachusetts",
    "MI: Michigan",
    "MN: Minnesota",
    "MS: Mississippi",
    "MO: Missouri",
    "MT: Montana",
    "NE: Nebraska",
    "NV: Nevada",
    "NH: New Hampshire",
    "NJ: New Jersey",
    "NM: New Mexico",
    "NY: New York",
    "NC: North Carolina",
    "ND: North Dakota",
    "OH: Ohio",
    "OK: Oklahoma",
    "OR: Oregon",
    "PA: Pennsylvania",
    "RI: Rhode Island",
    "SC: South Carolina",
    "SD: South Dakota",
    "TN: Tennessee",
    "TX: Texas",
    "UT: Utah",
    "VT: Vermont",
    "VA: Virginia",
    "WA: Washington",
    "WV: West Virginia",
    "WI: Wisconsin",
    "WY: Wyoming",
    "AS: American Samoa",
    "FM: Federated States of Micronesia",
    "GU: Guam",
    "MH: Marshall Islands",
    "MP: Northern Mariana Islands",
    "PW: Palau",
    "PR: Puerto Rico",
    "VI: Virgin Islands",
    "FQ: Baker Island",
    "HQ: Howland Island",
    "DQ: Jarvis Island",
    "JQ: Johnston Atoll",
    "KQ: Kingman Reef",
    "MQ: Midway Islands",
    "BQ: Navassa Island",
    "LQ: Palmyra Atoll",
    "WQ: Wake Island",
    "AA: Armed Forces Americas (except Canada)",
    "AE: Armed Forces Europe, the Middle East, and Canada",
    "AP: Armed Forces Pacific",
]

COUNTRIES = [
    "AFG: AFGHANISTAN",
    "XQZ: AKROTIRI",
    "ALB: ALBANIA",
    "DZA: ALGERIA",
    "AND: ANDORRA",
    "AGO: ANGOLA",
    "AIA: ANGUILLA",
    "ATA: ANTARCTICA",
    "ATG: ANTIGUA AND BARBUDA",
    "ARG: ARGENTINA",
    "ARM: ARMENIA",
    "ABW: ARUBA",
    "XAC: ASHMORE AND CARTIER ISLANDS",
    "AUS: AUSTRALIA",
    "AUT: AUSTRIA",
    "AZE: AZERBAIJAN",
    "BHS: BAHAMAS, THE",
    "BHR: BAHRAIN",
    "BGD: BANGLADESH",
    "BRB: BARBADOS",
    "XBI: BASSAS DA INDIA",
    "BLR: BELARUS",
    "BEL: BELGIUM",
    "BLZ: BELIZE",
    "BEN: BENIN",
    "BMU: BERMUDA",
    "BTN: BHUTAN",
    "BOL: BOLIVIA",
    "BES: BONAIRE, SINT EUSTATIUS, AND SABA",
    "BIH: BOSNIA AND HERZEGOVINA",
    "BWA: BOTSWANA",
    "BVT: BOUVET ISLAND",
    "BRA: BRAZIL",
    "IOT: BRITISH INDIAN OCEAN TERRITORY",
    "BRN: BRUNEI",
    "BGR: BULGARIA",
    "BFA: BURKINA FASO",
    "MMR: BURMA",
    "BDI: BURUNDI",
    "CPV: CABO VERDE",
    "KHM: CAMBODIA",
    "CMR: CAMEROON",
    "CAN: CANADA",
    "CYM: CAYMAN ISLANDS",
    "CAF: CENTRAL AFRICAN REPUBLIC",
    "TCD: CHAD",
    "CHL: CHILE",
    "CHN: CHINA",
    "CXR: CHRISTMAS ISLAND",
    "CPT: CLIPPERTON ISLAND",
    "CCK: COCOS (KEELING) ISLANDS",
    "COL: COLOMBIA",
    "COM: COMOROS",
    "COG: CONGO (BRAZZAVILLE)",
    "COD: CONGO (KINSHASA)",
    "COK: COOK ISLANDS",
    "XCS: CORAL SEA ISLANDS",
    "CRI: COSTA RICA",
    "CIV: CÔTE D'IVOIRE",
    "HRV: CROATIA",
    "CUB: CUBA",
    "CUW: CURAÇAO",
    "CYP: CYPRUS",
    "CZE: CZECHIA",
    "DNK: DENMARK",
    "XXD: DHEKELIA",
    "DGA: DIEGO GARCIA",
    "DJI: DJIBOUTI",
    "DMA: DOMINICA",
    "DOM: DOMINICAN REPUBLIC",
    "ECU: ECUADOR",
    "EGY: EGYPT",
    "SLV: EL SALVADOR",
    "XAZ: ENTITY 1",
    "XCR: ENTITY 2",
    "XCY: ENTITY 3",
    "XKM: ENTITY 4",
    "XKN: ENTITY 5",
    "AX3: ENTITY 6",
    "GNQ: EQUATORIAL GUINEA",
    "ERI: ERITREA",
    "EST: ESTONIA",
    "SWZ: ESWATINI",
    "ETH: ETHIOPIA",
    "XEU: EUROPA ISLAND",
    "FLK: FALKLAND ISLANDS (ISLAS MALVINAS)",
    "FRO: FAROE ISLANDS",
    "FJI: FIJI",
    "FIN: FINLAND",
    "FRA: FRANCE",
    "GUF: FRENCH GUIANA",
    "PYF: FRENCH POLYNESIA",
    "ATF: FRENCH SOUTHERN AND ANTARCTIC LANDS",
    "GAB: GABON",
    "GMB: GAMBIA, THE",
    "XGZ: GAZA STRIP",
    "GEO: GEORGIA",
    "DEU: GERMANY",
    "GHA: GHANA",
    "GIB: GIBRALTAR",
    "XGL: GLORIOSO ISLANDS",
    "GRC: GREECE",
    "GRL: GREENLAND",
    "GRD: GRENADA",
    "GLP: GUADELOUPE",
    "GTM: GUATEMALA",
    "GGY: GUERNSEY",
    "GIN: GUINEA",
    "GNB: GUINEA-BISSAU",
    "GUY: GUYANA",
    "HTI: HAITI",
    "HMD: HEARD ISLAND AND MCDONALD ISLANDS",
    "HND: HONDURAS",
    "HKG: HONG KONG",
    "HUN: HUNGARY",
    "ISL: ICELAND",
    "IND: INDIA",
    "IDN: INDONESIA",
    "IRN: IRAN",
    "IRQ: IRAQ",
    "IRL: IRELAND",
    "IMN: ISLE OF MAN",
    "ISR: ISRAEL",
    "ITA: ITALY",
    "JAM: JAMAICA",
    "XJM: JAN MAYEN",
    "JPN: JAPAN",
    "JEY: JERSEY",
    "JOR: JORDAN",
    "XJN: JUAN DE NOVA ISLAND",
    "KAZ: KAZAKHSTAN",
    "KEN: KENYA",
    "KIR: KIRIBATI",
    "PRK: KOREA, NORTH",
    "KOR: KOREA, SOUTH",
    "XKS: KOSOVO",
    "KWT: KUWAIT",
    "KGZ: KYRGYZSTAN",
    "LAO: LAOS",
    "LVA: LATVIA",
    "LBN: LEBANON",
    "LSO: LESOTHO",
    "LBR: LIBERIA",
    "LBY: LIBYA",
    "LIE: LIECHTENSTEIN",
    "LTU: LITHUANIA",
    "LUX: LUXEMBOURG",
    "MAC: MACAU",
    "MDG: MADAGASCAR",
    "MWI: MALAWI",
    "MYS: MALAYSIA",
    "MDV: MALDIVES",
    "MLI: MALI",
    "MLT: MALTA",
    "MTQ: MARTINIQUE",
    "MRT: MAURITANIA",
    "MUS: MAURITIUS",
    "MYT: MAYOTTE",
    "MEX: MEXICO",
    "MDA: MOLDOVA",
    "MCO: MONACO",
    "MNG: MONGOLIA",
    "MNE: MONTENEGRO",
    "MSR: MONTSERRAT",
    "MAR: MOROCCO",
    "MOZ: MOZAMBIQUE",
    "NAM: NAMIBIA",
    "NRU: NAURU",
    "NPL: NEPAL",
    "NLD: NETHERLANDS",
    "NCL: NEW CALEDONIA",
    "NZL: NEW ZEALAND",
    "NIC: NICARAGUA",
    "NER: NIGER",
    "NGA: NIGERIA",
    "NIU: NIUE",
    "NFK: NORFOLK ISLAND",
    "MKD: NORTH MACEDONIA",
    "NOR: NORWAY",
    "OMN: OMAN",
    "PAK: PAKISTAN",
    "PAN: PANAMA",
    "PNG: PAPUA NEW GUINEA",
    "XPR: PARACEL ISLANDS",
    "PRY: PARAGUAY",
    "PER: PERU",
    "PHL: PHILIPPINES",
    "PCN: PITCAIRN ISLANDS",
    "POL: POLAND",
    "PRT: PORTUGAL",
    "QAT: QATAR",
    "REU: REUNION",
    "ROU: ROMANIA",
    "RUS: RUSSIA",
    "RWA: RWANDA",
    "BLM: SAINT BARTHELEMY",
    "SHN: SAINT HELENA, ASCENSION, AND TRISTAN DA CUNHA",
    "KNA: SAINT KITTS AND NEVIS",
    "LCA: SAINT LUCIA",
    "MAF: SAINT MARTIN",
    "SPM: SAINT PIERRE AND MIQUELON",
    "VCT: SAINT VINCENT AND THE GRENADINES",
    "WSM: SAMOA",
    "SMR: SAN MARINO",
    "STP: SAO TOME AND PRINCIPE",
    "SAU: SAUDI ARABIA",
    "SEN: SENEGAL",
    "SRB: SERBIA",
    "SYC: SEYCHELLES",
    "SLE: SIERRA LEONE",
    "SGP: SINGAPORE",
    "SXM: SINT MAARTEN",
    "SVK: SLOVAKIA",
    "SVN: SLOVENIA",
    "SLB: SOLOMON ISLANDS",
    "SOM: SOMALIA",
    "ZAF: SOUTH AFRICA",
    "SGS: SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS",
    "SSD: SOUTH SUDAN",
    "ESP: SPAIN",
    "XSP: SPRATLY ISLANDS",
    "LKA: SRI LANKA",
    "SDN: SUDAN",
    "SUR: SURINAME",
    "XSV: SVALBARD",
    "SWE: SWEDEN",
    "CHE: SWITZERLAND",
    "SYR: SYRIA",
    "TWN: TAIWAN",
    "TJK: TAJIKISTAN",
    "TZA: TANZANIA",
    "THA: THAILAND",
    "TLS: TIMOR-LESTE",
    "TGO: TOGO",
    "TKL: TOKELAU",
    "TON: TONGA",
    "TTO: TRINIDAD AND TOBAGO",
    "XTR: TROMELIN ISLAND",
    "TUN: TUNISIA",
    "TUR: TURKEY",
    "TKM: TURKMENISTAN",
    "TCA: TURKS AND CAICOS ISLANDS",
    "TUV: TUVALU",
    "UGA: UGANDA",
    "UKR: UKRAINE",
    "ARE: UNITED ARAB EMIRATES",
    "GBR: UNITED KINGDOM",
    "USA: UNITED STATES",
    "URY: URUGUAY",
    "UZB: UZBEKISTAN",
    "VUT: VANUATU",
    "VAT: VATICAN CITY",
    "VEN: VENEZUELA",
    "VNM: VIETNAM",
    "VGB: VIRGIN ISLANDS, BRITISH",
    "WLF: WALLIS AND FUTUNA",
    "XWB: WEST BANK",
    "ESH: WESTERN SAHARA",
    "YEM: YEMEN",
    "ZMB: ZAMBIA",
    "ZWE: ZIMBABWE",
]
