"""add authN tables

Revision ID: 302f2245fc29
Revises: 62789866386c
Create Date: 2026-07-09 09:56:03.011786

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "302f2245fc29"
down_revision = "62789866386c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_external_user_type",
        sa.Column("external_user_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("external_user_type_id", name=op.f("lk_external_user_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_mgmt_user_type",
        sa.Column("mgmt_user_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_user_type_id", name=op.f("lk_mgmt_user_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "mgmt_login_gov_state",
        sa.Column("mgmt_login_gov_state_id", sa.UUID(), nullable=False),
        sa.Column("nonce", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_login_gov_state_id", name=op.f("mgmt_login_gov_state_pkey")),
        schema="grantor",
    )
    op.create_table(
        "mgmt_user",
        sa.Column("mgmt_user_id", sa.UUID(), nullable=False),
        sa.Column("mgmt_user_type_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_user_type_id"],
            ["grantor.lk_mgmt_user_type.mgmt_user_type_id"],
            name=op.f("mgmt_user_mgmt_user_type_id_lk_mgmt_user_type_fkey"),
        ),
        sa.PrimaryKeyConstraint("mgmt_user_id", name=op.f("mgmt_user_pkey")),
        schema="grantor",
    )
    op.create_table(
        "mgmt_link_external_user",
        sa.Column("mgmt_link_external_user_id", sa.UUID(), nullable=False),
        sa.Column("external_user_type_id", sa.Integer(), nullable=False),
        sa.Column("mgmt_user_id", sa.UUID(), nullable=False),
        sa.Column("external_user_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["external_user_type_id"],
            ["grantor.lk_external_user_type.external_user_type_id"],
            name=op.f("mgmt_link_external_user_external_user_type_id_lk_external_user_type_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_user_id"],
            ["grantor.mgmt_user.mgmt_user_id"],
            name=op.f("mgmt_link_external_user_mgmt_user_id_mgmt_user_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_link_external_user_id", name=op.f("mgmt_link_external_user_pkey")
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_link_external_user_email_idx"),
        "mgmt_link_external_user",
        ["email"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_link_external_user_external_user_id_idx"),
        "mgmt_link_external_user",
        ["external_user_id"],
        unique=True,
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_link_external_user_external_user_type_id_idx"),
        "mgmt_link_external_user",
        ["external_user_type_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_link_external_user_mgmt_user_id_idx"),
        "mgmt_link_external_user",
        ["mgmt_user_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "mgmt_user_api_key",
        sa.Column("mgmt_api_key_id", sa.UUID(), nullable=False),
        sa.Column("mgmt_user_id", sa.UUID(), nullable=False),
        sa.Column("key_name", sa.Text(), nullable=False),
        sa.Column("key_id", sa.Text(), nullable=False, comment="AWS API Gateway key identifier"),
        sa.Column("last_used", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_user_id"],
            ["grantor.mgmt_user.mgmt_user_id"],
            name=op.f("mgmt_user_api_key_mgmt_user_id_mgmt_user_fkey"),
        ),
        sa.PrimaryKeyConstraint("mgmt_api_key_id", name=op.f("mgmt_user_api_key_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_user_api_key_key_id_idx"),
        "mgmt_user_api_key",
        ["key_id"],
        unique=True,
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_user_api_key_mgmt_user_id_idx"),
        "mgmt_user_api_key",
        ["mgmt_user_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "mgmt_user_token_session",
        sa.Column("mgmt_user_id", sa.UUID(), nullable=False),
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_user_id"],
            ["grantor.mgmt_user.mgmt_user_id"],
            name=op.f("mgmt_user_token_session_mgmt_user_id_mgmt_user_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_user_id", "token_id", name=op.f("mgmt_user_token_session_pkey")
        ),
        schema="grantor",
    )
    op.drop_table("user", schema="grantor")
    op.drop_table("lk_user_type", schema="grantor")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_user_type",
        sa.Column("user_type_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_type_id", name=op.f("lk_user_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_type_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_type_id"],
            ["grantor.lk_user_type.user_type_id"],
            name=op.f("user_user_type_id_lk_user_type_fkey"),
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("user_pkey")),
        schema="grantor",
    )
    op.drop_table("mgmt_user_token_session", schema="grantor")
    op.drop_index(
        op.f("mgmt_user_api_key_mgmt_user_id_idx"), table_name="mgmt_user_api_key", schema="grantor"
    )
    op.drop_index(
        op.f("mgmt_user_api_key_key_id_idx"), table_name="mgmt_user_api_key", schema="grantor"
    )
    op.drop_table("mgmt_user_api_key", schema="grantor")
    op.drop_index(
        op.f("mgmt_link_external_user_mgmt_user_id_idx"),
        table_name="mgmt_link_external_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("mgmt_link_external_user_external_user_type_id_idx"),
        table_name="mgmt_link_external_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("mgmt_link_external_user_external_user_id_idx"),
        table_name="mgmt_link_external_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("mgmt_link_external_user_email_idx"),
        table_name="mgmt_link_external_user",
        schema="grantor",
    )
    op.drop_table("mgmt_link_external_user", schema="grantor")
    op.drop_table("mgmt_user", schema="grantor")
    op.drop_table("mgmt_login_gov_state", schema="grantor")
    op.drop_table("lk_mgmt_user_type", schema="grantor")
    op.drop_table("lk_external_user_type", schema="grantor")
    # ### end Alembic commands ###
