"""add login tables

Revision ID: 263e8f15bed0
Revises: 62789866386c
Create Date: 2026-07-02 14:26:21.589523

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "263e8f15bed0"
down_revision = "62789866386c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_external_user_type",
        sa.Column("external_user_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("external_user_type_id", name=op.f("lk_external_user_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "login_gov_state",
        sa.Column("login_gov_state_id", sa.UUID(), nullable=False),
        sa.Column("nonce", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("login_gov_state_id", name=op.f("login_gov_state_pkey")),
        schema="grantor",
    )
    op.create_table(
        "link_external_user",
        sa.Column("link_external_user_id", sa.UUID(), nullable=False),
        sa.Column("external_user_type_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("external_user_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["external_user_type_id"],
            ["grantor.lk_external_user_type.external_user_type_id"],
            name=op.f("link_external_user_external_user_type_id_lk_external_user_type_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["grantor.user.user_id"], name=op.f("link_external_user_user_id_user_fkey")
        ),
        sa.PrimaryKeyConstraint("link_external_user_id", name=op.f("link_external_user_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("link_external_user_email_idx"),
        "link_external_user",
        ["email"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("link_external_user_external_user_id_idx"),
        "link_external_user",
        ["external_user_id"],
        unique=True,
        schema="grantor",
    )
    op.create_index(
        op.f("link_external_user_external_user_type_id_idx"),
        "link_external_user",
        ["external_user_type_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("link_external_user_user_id_idx"),
        "link_external_user",
        ["user_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "user_api_key",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("api_key_id", sa.UUID(), nullable=False),
        sa.Column("key_name", sa.Text(), nullable=False),
        sa.Column("key_id", sa.Text(), nullable=False, comment="AWS API Gateway key identifier"),
        sa.Column("last_used", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["grantor.user.user_id"], name=op.f("user_api_key_user_id_user_fkey")
        ),
        sa.PrimaryKeyConstraint("api_key_id", name=op.f("user_api_key_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("user_api_key_key_id_idx"), "user_api_key", ["key_id"], unique=True, schema="grantor"
    )
    op.create_index(
        op.f("user_api_key_user_id_idx"),
        "user_api_key",
        ["user_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "user_token_session",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["grantor.user.user_id"], name=op.f("user_token_session_user_id_user_fkey")
        ),
        sa.PrimaryKeyConstraint("user_id", "token_id", name=op.f("user_token_session_pkey")),
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_token_session", schema="grantor")
    op.drop_index(op.f("user_api_key_user_id_idx"), table_name="user_api_key", schema="grantor")
    op.drop_index(op.f("user_api_key_key_id_idx"), table_name="user_api_key", schema="grantor")
    op.drop_table("user_api_key", schema="grantor")
    op.drop_index(
        op.f("link_external_user_user_id_idx"), table_name="link_external_user", schema="grantor"
    )
    op.drop_index(
        op.f("link_external_user_external_user_type_id_idx"),
        table_name="link_external_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("link_external_user_external_user_id_idx"),
        table_name="link_external_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("link_external_user_email_idx"), table_name="link_external_user", schema="grantor"
    )
    op.drop_table("link_external_user", schema="grantor")
    op.drop_table("login_gov_state", schema="grantor")
    op.drop_table("lk_external_user_type", schema="grantor")
    # ### end Alembic commands ###
