"""add privilege resource

Revision ID: 0a682b37e38c
Revises: 302f2245fc29
Create Date: 2026-07-13 16:26:30.486174

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a682b37e38c"
down_revision = "302f2245fc29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_mgmt_privilege",
        sa.Column("mgmt_privilege_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_privilege_id", name=op.f("lk_mgmt_privilege_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_mgmt_resource_type",
        sa.Column("mgmt_resource_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_resource_type_id", name=op.f("lk_mgmt_resource_type_pkey")),
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lk_mgmt_resource_type", schema="grantor")
    op.drop_table("lk_mgmt_privilege", schema="grantor")
    # ### end Alembic commands ###
