"""authZ models

Revision ID: cc73f991a327
Revises: 0a682b37e38c
Create Date: 2026-07-14 16:42:34.835024

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc73f991a327"
down_revision = "0a682b37e38c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mgmt_role",
        sa.Column("mgmt_role_id", sa.UUID(), nullable=False),
        sa.Column("role_name", sa.Text(), nullable=False),
        sa.Column("is_core", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_role_id", name=op.f("mgmt_role_pkey")),
        schema="grantor",
    )
    op.create_table(
        "mgmt_link_role_privilege",
        sa.Column("mgmt_role_id", sa.UUID(), nullable=False),
        sa.Column("mgmt_privilege_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_privilege_id"],
            ["grantor.lk_mgmt_privilege.mgmt_privilege_id"],
            name=op.f("mgmt_link_role_privilege_mgmt_privilege_id_lk_mgmt_privilege_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_role_id"],
            ["grantor.mgmt_role.mgmt_role_id"],
            name=op.f("mgmt_link_role_privilege_mgmt_role_id_mgmt_role_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_role_id", "mgmt_privilege_id", name=op.f("mgmt_link_role_privilege_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "mgmt_link_role_resource_type",
        sa.Column("mgmt_role_id", sa.UUID(), nullable=False),
        sa.Column("mgmt_resource_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_resource_type_id"],
            ["grantor.lk_mgmt_resource_type.mgmt_resource_type_id"],
            name=op.f(
                "mgmt_link_role_resource_type_mgmt_resource_type_id_lk_mgmt_resource_type_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_role_id"],
            ["grantor.mgmt_role.mgmt_role_id"],
            name=op.f("mgmt_link_role_resource_type_mgmt_role_id_mgmt_role_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_role_id", "mgmt_resource_type_id", name=op.f("mgmt_link_role_resource_type_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "mgmt_resource",
        sa.Column("mgmt_resource_id", sa.UUID(), nullable=False),
        sa.Column("mgmt_resource_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_resource_type_id"],
            ["grantor.lk_mgmt_resource_type.mgmt_resource_type_id"],
            name=op.f("mgmt_resource_mgmt_resource_type_id_lk_mgmt_resource_type_fkey"),
        ),
        sa.PrimaryKeyConstraint("mgmt_resource_id", name=op.f("mgmt_resource_pkey")),
        schema="grantor",
    )
    op.create_table(
        "department",
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("department_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("department_department_id_mgmt_resource_fkey"),
        ),
        sa.PrimaryKeyConstraint("department_id", name=op.f("department_pkey")),
        schema="grantor",
    )
    op.create_table(
        "mgmt_internal_resource",
        sa.Column("mgmt_internal_resource_id", sa.UUID(), nullable=False),
        sa.Column("internal_resource_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_internal_resource_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("mgmt_internal_resource_mgmt_internal_resource_id_mgmt_resource_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_internal_resource_id", name=op.f("mgmt_internal_resource_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "mgmt_resource_user",
        sa.Column("mgmt_resource_user_id", sa.UUID(), nullable=False),
        sa.Column("mgmt_resource_id", sa.UUID(), nullable=False),
        sa.Column("mgmt_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_resource_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("mgmt_resource_user_mgmt_resource_id_mgmt_resource_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_user_id"],
            ["grantor.mgmt_user.mgmt_user_id"],
            name=op.f("mgmt_resource_user_mgmt_user_id_mgmt_user_fkey"),
        ),
        sa.PrimaryKeyConstraint("mgmt_resource_user_id", name=op.f("mgmt_resource_user_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_resource_user_mgmt_resource_id_idx"),
        "mgmt_resource_user",
        ["mgmt_resource_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_resource_user_mgmt_user_id_idx"),
        "mgmt_resource_user",
        ["mgmt_user_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "mgmt_resource_user_role",
        sa.Column("mgmt_resource_user_id", sa.UUID(), nullable=False),
        sa.Column("mgmt_role_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_resource_user_id"],
            ["grantor.mgmt_resource_user.mgmt_resource_user_id"],
            name=op.f("mgmt_resource_user_role_mgmt_resource_user_id_mgmt_resource_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_role_id"],
            ["grantor.mgmt_role.mgmt_role_id"],
            name=op.f("mgmt_resource_user_role_mgmt_role_id_mgmt_role_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_resource_user_id", "mgmt_role_id", name=op.f("mgmt_resource_user_role_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "subagency",
        sa.Column("subagency_id", sa.UUID(), nullable=False),
        sa.Column("subagency_name", sa.Text(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["grantor.department.department_id"],
            name=op.f("subagency_department_id_department_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["subagency_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("subagency_subagency_id_mgmt_resource_fkey"),
        ),
        sa.PrimaryKeyConstraint("subagency_id", name=op.f("subagency_pkey")),
        schema="grantor",
    )
    op.create_table(
        "team",
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("team_name", sa.Text(), nullable=False),
        sa.Column("subagency_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subagency_id"],
            ["grantor.subagency.subagency_id"],
            name=op.f("team_subagency_id_subagency_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("team_team_id_mgmt_resource_fkey"),
        ),
        sa.PrimaryKeyConstraint("team_id", name=op.f("team_pkey")),
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team", schema="grantor")
    op.drop_table("subagency", schema="grantor")
    op.drop_table("mgmt_resource_user_role", schema="grantor")
    op.drop_index(
        op.f("mgmt_resource_user_mgmt_user_id_idx"),
        table_name="mgmt_resource_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("mgmt_resource_user_mgmt_resource_id_idx"),
        table_name="mgmt_resource_user",
        schema="grantor",
    )
    op.drop_table("mgmt_resource_user", schema="grantor")
    op.drop_table("mgmt_internal_resource", schema="grantor")
    op.drop_table("department", schema="grantor")
    op.drop_table("mgmt_resource", schema="grantor")
    op.drop_table("mgmt_link_role_resource_type", schema="grantor")
    op.drop_table("mgmt_link_role_privilege", schema="grantor")
    op.drop_table("mgmt_role", schema="grantor")
    # ### end Alembic commands ###
