"""tmp

Revision ID: c111aac0ed6c
Revises: 5d58c38f2cac
Create Date: 2024-02-23 13:22:27.449784

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c111aac0ed6c"
down_revision = "5d58c38f2cac"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("opportunity_summary")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
