"""make revision number nullable

Revision ID: b26ea0f40066
Revises: f8364285630d
Create Date: 2024-04-16 13:36:35.993325

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b26ea0f40066"
down_revision = "f8364285630d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "opportunity_summary",
        "revision_number",
        existing_type=sa.INTEGER(),
        nullable=True,
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "opportunity_summary",
        "revision_number",
        existing_type=sa.INTEGER(),
        nullable=False,
        schema="api",
    )
    # ### end Alembic commands ###
