"""Add staging tables

Revision ID: e3a1be603d26
Revises: c6878bae0c60
Create Date: 2024-04-24 15:27:13.602523

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3a1be603d26"
down_revision = "c6878bae0c60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tapplicanttypes_forecast",
        sa.Column("at_frcst_id", sa.BigInteger(), nullable=False),
        sa.Column("at_id", sa.Text(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "at_frcst_id", "at_id", "opportunity_id", name=op.f("tapplicanttypes_forecast_pkey")
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tapplicanttypes_forecast_transformed_at_idx"),
        "tapplicanttypes_forecast",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tapplicanttypes_forecast_hist",
        sa.Column("at_frcst_id", sa.BigInteger(), nullable=False),
        sa.Column("at_id", sa.Text(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("revision_number", sa.BigInteger(), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "at_frcst_id",
            "at_id",
            "opportunity_id",
            "revision_number",
            name=op.f("tapplicanttypes_forecast_hist_pkey"),
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tapplicanttypes_forecast_hist_transformed_at_idx"),
        "tapplicanttypes_forecast_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tapplicanttypes_synopsis",
        sa.Column("at_syn_id", sa.BigInteger(), nullable=False),
        sa.Column("at_id", sa.Text(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "at_syn_id", "at_id", "opportunity_id", name=op.f("tapplicanttypes_synopsis_pkey")
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tapplicanttypes_synopsis_transformed_at_idx"),
        "tapplicanttypes_synopsis",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tapplicanttypes_synopsis_hist",
        sa.Column("at_syn_id", sa.BigInteger(), nullable=False),
        sa.Column("at_id", sa.Text(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("revision_number", sa.BigInteger(), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "at_syn_id",
            "at_id",
            "opportunity_id",
            "revision_number",
            name=op.f("tapplicanttypes_synopsis_hist_pkey"),
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tapplicanttypes_synopsis_hist_transformed_at_idx"),
        "tapplicanttypes_synopsis_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tforecast",
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("version_nbr", sa.BigInteger(), nullable=False),
        sa.Column("posting_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("archive_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("forecast_desc", sa.Text(), nullable=True),
        sa.Column("oth_cat_fa_desc", sa.Text(), nullable=True),
        sa.Column("cost_sharing", sa.Text(), nullable=True),
        sa.Column("number_of_awards", sa.Text(), nullable=True),
        sa.Column("est_funding", sa.Text(), nullable=True),
        sa.Column("award_ceiling", sa.Text(), nullable=True),
        sa.Column("award_floor", sa.Text(), nullable=True),
        sa.Column("fd_link_url", sa.Text(), nullable=True),
        sa.Column("fd_link_desc", sa.Text(), nullable=True),
        sa.Column("ac_name", sa.Text(), nullable=True),
        sa.Column("ac_phone", sa.Text(), nullable=True),
        sa.Column("ac_email_addr", sa.Text(), nullable=True),
        sa.Column("ac_email_desc", sa.Text(), nullable=True),
        sa.Column("agency_code", sa.Text(), nullable=True),
        sa.Column("sendmail", sa.Text(), nullable=True),
        sa.Column("applicant_elig_desc", sa.Text(), nullable=True),
        sa.Column("est_synopsis_posting_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("est_appl_response_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("est_appl_response_date_desc", sa.Text(), nullable=True),
        sa.Column("est_award_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("est_project_start_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("fiscal_year", sa.BigInteger(), nullable=True),
        sa.Column("modification_comments", sa.Text(), nullable=True),
        sa.Column("create_ts", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("publisheruid", sa.Text(), nullable=True),
        sa.Column("publisher_profile_id", sa.BigInteger(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("opportunity_id", name=op.f("tforecast_pkey")),
        schema="staging",
    )
    op.create_index(
        op.f("tforecast_transformed_at_idx"),
        "tforecast",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tforecast_hist",
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("revision_number", sa.BigInteger(), nullable=False),
        sa.Column("version_nbr", sa.BigInteger(), nullable=False),
        sa.Column("posting_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("archive_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("forecast_desc", sa.Text(), nullable=True),
        sa.Column("oth_cat_fa_desc", sa.Text(), nullable=True),
        sa.Column("cost_sharing", sa.Text(), nullable=True),
        sa.Column("number_of_awards", sa.Text(), nullable=True),
        sa.Column("est_funding", sa.Text(), nullable=True),
        sa.Column("award_ceiling", sa.Text(), nullable=True),
        sa.Column("award_floor", sa.Text(), nullable=True),
        sa.Column("fd_link_url", sa.Text(), nullable=True),
        sa.Column("fd_link_desc", sa.Text(), nullable=True),
        sa.Column("ac_name", sa.Text(), nullable=True),
        sa.Column("ac_phone", sa.Text(), nullable=True),
        sa.Column("ac_email_addr", sa.Text(), nullable=True),
        sa.Column("ac_email_desc", sa.Text(), nullable=True),
        sa.Column("agency_code", sa.Text(), nullable=True),
        sa.Column("sendmail", sa.Text(), nullable=True),
        sa.Column("applicant_elig_desc", sa.Text(), nullable=True),
        sa.Column("est_synopsis_posting_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("est_appl_response_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("est_appl_response_date_desc", sa.Text(), nullable=True),
        sa.Column("est_award_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("est_project_start_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("fiscal_year", sa.BigInteger(), nullable=True),
        sa.Column("modification_comments", sa.Text(), nullable=True),
        sa.Column("action_type", sa.Text(), nullable=True),
        sa.Column("action_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("create_ts", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("publisheruid", sa.Text(), nullable=True),
        sa.Column("publisher_profile_id", sa.BigInteger(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "opportunity_id", "revision_number", name=op.f("tforecast_hist_pkey")
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tforecast_hist_transformed_at_idx"),
        "tforecast_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tfundactcat_forecast",
        sa.Column("fac_frcst_id", sa.BigInteger(), nullable=False),
        sa.Column("fac_id", sa.Text(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "fac_frcst_id", "fac_id", "opportunity_id", name=op.f("tfundactcat_forecast_pkey")
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tfundactcat_forecast_transformed_at_idx"),
        "tfundactcat_forecast",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tfundactcat_forecast_hist",
        sa.Column("fac_frcst_id", sa.BigInteger(), nullable=False),
        sa.Column("fac_id", sa.Text(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("revision_number", sa.BigInteger(), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "fac_frcst_id",
            "fac_id",
            "opportunity_id",
            "revision_number",
            name=op.f("tfundactcat_forecast_hist_pkey"),
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tfundactcat_forecast_hist_transformed_at_idx"),
        "tfundactcat_forecast_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tfundactcat_synopsis",
        sa.Column("fac_syn_id", sa.BigInteger(), nullable=False),
        sa.Column("fac_id", sa.Text(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "fac_syn_id", "fac_id", "opportunity_id", name=op.f("tfundactcat_synopsis_pkey")
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tfundactcat_synopsis_transformed_at_idx"),
        "tfundactcat_synopsis",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tfundactcat_synopsis_hist",
        sa.Column("fac_syn_id", sa.BigInteger(), nullable=False),
        sa.Column("fac_id", sa.Text(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("revision_number", sa.BigInteger(), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "fac_syn_id",
            "fac_id",
            "opportunity_id",
            "revision_number",
            name=op.f("tfundactcat_synopsis_hist_pkey"),
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tfundactcat_synopsis_hist_transformed_at_idx"),
        "tfundactcat_synopsis_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tfundinstr_forecast",
        sa.Column("fi_frcst_id", sa.BigInteger(), nullable=False),
        sa.Column("fi_id", sa.Text(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "fi_frcst_id", "fi_id", "opportunity_id", name=op.f("tfundinstr_forecast_pkey")
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tfundinstr_forecast_transformed_at_idx"),
        "tfundinstr_forecast",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tfundinstr_forecast_hist",
        sa.Column("fi_frcst_id", sa.BigInteger(), nullable=False),
        sa.Column("fi_id", sa.Text(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("revision_number", sa.BigInteger(), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "fi_frcst_id",
            "fi_id",
            "opportunity_id",
            "revision_number",
            name=op.f("tfundinstr_forecast_hist_pkey"),
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tfundinstr_forecast_hist_transformed_at_idx"),
        "tfundinstr_forecast_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tfundinstr_synopsis",
        sa.Column("fi_syn_id", sa.BigInteger(), nullable=False),
        sa.Column("fi_id", sa.Text(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "fi_syn_id", "fi_id", "opportunity_id", name=op.f("tfundinstr_synopsis_pkey")
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tfundinstr_synopsis_transformed_at_idx"),
        "tfundinstr_synopsis",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tfundinstr_synopsis_hist",
        sa.Column("fi_syn_id", sa.BigInteger(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("fi_id", sa.Text(), nullable=False),
        sa.Column("revision_number", sa.BigInteger(), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "fi_syn_id",
            "opportunity_id",
            "fi_id",
            "revision_number",
            name=op.f("tfundinstr_synopsis_hist_pkey"),
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tfundinstr_synopsis_hist_transformed_at_idx"),
        "tfundinstr_synopsis_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "topportunity",
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("oppnumber", sa.Text(), nullable=True),
        sa.Column("revision_number", sa.BigInteger(), nullable=True),
        sa.Column("opptitle", sa.Text(), nullable=True),
        sa.Column("owningagency", sa.Text(), nullable=True),
        sa.Column("publisheruid", sa.Text(), nullable=True),
        sa.Column("listed", sa.Text(), nullable=True),
        sa.Column("oppcategory", sa.Text(), nullable=True),
        sa.Column("initial_opportunity_id", sa.BigInteger(), nullable=True),
        sa.Column("modified_comments", sa.Text(), nullable=True),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("flag_2006", sa.Text(), nullable=True),
        sa.Column("category_explanation", sa.Text(), nullable=True),
        sa.Column("publisher_profile_id", sa.BigInteger(), nullable=True),
        sa.Column("is_draft", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("opportunity_id", name=op.f("topportunity_pkey")),
        schema="staging",
    )
    op.create_index(
        op.f("topportunity_transformed_at_idx"),
        "topportunity",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "topportunity_cfda",
        sa.Column("opp_cfda_id", sa.BigInteger(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("cfdanumber", sa.Text(), nullable=True),
        sa.Column("programtitle", sa.Text(), nullable=True),
        sa.Column("origtoppid", sa.BigInteger(), nullable=True),
        sa.Column("oppidcfdanum", sa.Text(), nullable=True),
        sa.Column("origoppnum", sa.Text(), nullable=True),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("opp_cfda_id", name=op.f("topportunity_cfda_pkey")),
        schema="staging",
    )
    op.create_index(
        op.f("topportunity_cfda_transformed_at_idx"),
        "topportunity_cfda",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tsynopsis",
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("posting_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("response_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("archive_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("unarchive_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("syn_desc", sa.Text(), nullable=True),
        sa.Column("oth_cat_fa_desc", sa.Text(), nullable=True),
        sa.Column("agency_addr_desc", sa.Text(), nullable=True),
        sa.Column("cost_sharing", sa.Text(), nullable=True),
        sa.Column("number_of_awards", sa.Text(), nullable=True),
        sa.Column("est_funding", sa.Text(), nullable=True),
        sa.Column("award_ceiling", sa.Text(), nullable=True),
        sa.Column("award_floor", sa.Text(), nullable=True),
        sa.Column("fd_link_url", sa.Text(), nullable=True),
        sa.Column("fd_link_desc", sa.Text(), nullable=True),
        sa.Column("agency_contact_desc", sa.Text(), nullable=True),
        sa.Column("ac_email_addr", sa.Text(), nullable=True),
        sa.Column("ac_email_desc", sa.Text(), nullable=True),
        sa.Column("agency_name", sa.Text(), nullable=True),
        sa.Column("agency_phone", sa.Text(), nullable=True),
        sa.Column("a_sa_code", sa.Text(), nullable=True),
        sa.Column("ac_phone_number", sa.Text(), nullable=True),
        sa.Column("ac_name", sa.Text(), nullable=True),
        sa.Column("create_ts", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("sendmail", sa.Text(), nullable=True),
        sa.Column("response_date_desc", sa.Text(), nullable=True),
        sa.Column("applicant_elig_desc", sa.Text(), nullable=True),
        sa.Column("version_nbr", sa.BigInteger(), nullable=True),
        sa.Column("modification_comments", sa.Text(), nullable=True),
        sa.Column("publisheruid", sa.Text(), nullable=True),
        sa.Column("publisher_profile_id", sa.BigInteger(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("opportunity_id", name=op.f("tsynopsis_pkey")),
        schema="staging",
    )
    op.create_index(
        op.f("tsynopsis_transformed_at_idx"),
        "tsynopsis",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tsynopsis_hist",
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("revision_number", sa.BigInteger(), nullable=False),
        sa.Column("posting_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("response_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("archive_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("unarchive_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("syn_desc", sa.Text(), nullable=True),
        sa.Column("oth_cat_fa_desc", sa.Text(), nullable=True),
        sa.Column("agency_addr_desc", sa.Text(), nullable=True),
        sa.Column("cost_sharing", sa.Text(), nullable=True),
        sa.Column("number_of_awards", sa.Text(), nullable=True),
        sa.Column("est_funding", sa.Text(), nullable=True),
        sa.Column("award_ceiling", sa.Text(), nullable=True),
        sa.Column("award_floor", sa.Text(), nullable=True),
        sa.Column("fd_link_url", sa.Text(), nullable=True),
        sa.Column("fd_link_desc", sa.Text(), nullable=True),
        sa.Column("agency_contact_desc", sa.Text(), nullable=True),
        sa.Column("ac_email_addr", sa.Text(), nullable=True),
        sa.Column("ac_email_desc", sa.Text(), nullable=True),
        sa.Column("agency_name", sa.Text(), nullable=True),
        sa.Column("agency_phone", sa.Text(), nullable=True),
        sa.Column("a_sa_code", sa.Text(), nullable=True),
        sa.Column("ac_phone_number", sa.Text(), nullable=True),
        sa.Column("ac_name", sa.Text(), nullable=True),
        sa.Column("create_ts", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("sendmail", sa.Text(), nullable=True),
        sa.Column("response_date_desc", sa.Text(), nullable=True),
        sa.Column("applicant_elig_desc", sa.Text(), nullable=True),
        sa.Column("action_type", sa.Text(), nullable=True),
        sa.Column("action_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("version_nbr", sa.BigInteger(), nullable=False),
        sa.Column("modification_comments", sa.Text(), nullable=True),
        sa.Column("publisheruid", sa.Text(), nullable=True),
        sa.Column("publisher_profile_id", sa.BigInteger(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "opportunity_id", "revision_number", name=op.f("tsynopsis_hist_pkey")
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tsynopsis_hist_transformed_at_idx"),
        "tsynopsis_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("tsynopsis_hist_transformed_at_idx"), table_name="tsynopsis_hist", schema="staging"
    )
    op.drop_table("tsynopsis_hist", schema="staging")
    op.drop_index(op.f("tsynopsis_transformed_at_idx"), table_name="tsynopsis", schema="staging")
    op.drop_table("tsynopsis", schema="staging")
    op.drop_index(
        op.f("topportunity_cfda_transformed_at_idx"),
        table_name="topportunity_cfda",
        schema="staging",
    )
    op.drop_table("topportunity_cfda", schema="staging")
    op.drop_index(
        op.f("topportunity_transformed_at_idx"), table_name="topportunity", schema="staging"
    )
    op.drop_table("topportunity", schema="staging")
    op.drop_index(
        op.f("tfundinstr_synopsis_hist_transformed_at_idx"),
        table_name="tfundinstr_synopsis_hist",
        schema="staging",
    )
    op.drop_table("tfundinstr_synopsis_hist", schema="staging")
    op.drop_index(
        op.f("tfundinstr_synopsis_transformed_at_idx"),
        table_name="tfundinstr_synopsis",
        schema="staging",
    )
    op.drop_table("tfundinstr_synopsis", schema="staging")
    op.drop_index(
        op.f("tfundinstr_forecast_hist_transformed_at_idx"),
        table_name="tfundinstr_forecast_hist",
        schema="staging",
    )
    op.drop_table("tfundinstr_forecast_hist", schema="staging")
    op.drop_index(
        op.f("tfundinstr_forecast_transformed_at_idx"),
        table_name="tfundinstr_forecast",
        schema="staging",
    )
    op.drop_table("tfundinstr_forecast", schema="staging")
    op.drop_index(
        op.f("tfundactcat_synopsis_hist_transformed_at_idx"),
        table_name="tfundactcat_synopsis_hist",
        schema="staging",
    )
    op.drop_table("tfundactcat_synopsis_hist", schema="staging")
    op.drop_index(
        op.f("tfundactcat_synopsis_transformed_at_idx"),
        table_name="tfundactcat_synopsis",
        schema="staging",
    )
    op.drop_table("tfundactcat_synopsis", schema="staging")
    op.drop_index(
        op.f("tfundactcat_forecast_hist_transformed_at_idx"),
        table_name="tfundactcat_forecast_hist",
        schema="staging",
    )
    op.drop_table("tfundactcat_forecast_hist", schema="staging")
    op.drop_index(
        op.f("tfundactcat_forecast_transformed_at_idx"),
        table_name="tfundactcat_forecast",
        schema="staging",
    )
    op.drop_table("tfundactcat_forecast", schema="staging")
    op.drop_index(
        op.f("tforecast_hist_transformed_at_idx"), table_name="tforecast_hist", schema="staging"
    )
    op.drop_table("tforecast_hist", schema="staging")
    op.drop_index(op.f("tforecast_transformed_at_idx"), table_name="tforecast", schema="staging")
    op.drop_table("tforecast", schema="staging")
    op.drop_index(
        op.f("tapplicanttypes_synopsis_hist_transformed_at_idx"),
        table_name="tapplicanttypes_synopsis_hist",
        schema="staging",
    )
    op.drop_table("tapplicanttypes_synopsis_hist", schema="staging")
    op.drop_index(
        op.f("tapplicanttypes_synopsis_transformed_at_idx"),
        table_name="tapplicanttypes_synopsis",
        schema="staging",
    )
    op.drop_table("tapplicanttypes_synopsis", schema="staging")
    op.drop_index(
        op.f("tapplicanttypes_forecast_hist_transformed_at_idx"),
        table_name="tapplicanttypes_forecast_hist",
        schema="staging",
    )
    op.drop_table("tapplicanttypes_forecast_hist", schema="staging")
    op.drop_index(
        op.f("tapplicanttypes_forecast_transformed_at_idx"),
        table_name="tapplicanttypes_forecast",
        schema="staging",
    )
    op.drop_table("tapplicanttypes_forecast", schema="staging")
    # ### end Alembic commands ###
