"""remove DMS exceptions table

Revision ID: 5d58c38f2cac
Revises: 86edfcb92a66
Create Date: 2024-02-21 13:44:50.932948

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "5d58c38f2cac"
down_revision = "86edfcb92a66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS api.awsdms_apply_exceptions")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS api.awsdms_apply_exceptions (
            ERROR_TIME timestamp  NOT NULL,
            TASK_NAME varchar(128)  NOT NULL,
            TABLE_OWNER varchar(128)  NOT NULL,
            TABLE_NAME varchar(128)  NOT NULL,
            STATEMENT text  NOT NULL,
            ERROR text  NOT NULL
        );
    """
    )
    # ### end Alembic commands ###
