"""Add created_at, updated_at, and deleted_at columns to staging tables

Revision ID: 1ddd1d051a99
Revises: e3a1be603d26
Create Date: 2024-05-01 11:14:34.332661

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1ddd1d051a99"
down_revision = "e3a1be603d26"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("topportunity_cfda", schema="legacy")
    op.drop_table("t1", schema="api")
    op.drop_table("tfundinstr_synopsis_hist", schema="legacy")
    op.drop_table("tfundactcat_forecast_hist", schema="legacy")
    op.drop_table("t2", schema="api")
    op.drop_table("tfundinstr_synopsis", schema="legacy")
    op.drop_table("tfundinstr_forecast_hist", schema="legacy")
    op.drop_table("tforecast", schema="legacy")
    op.drop_table("tfundinstr_forecast", schema="legacy")
    op.drop_table("tsynopsis", schema="legacy")
    op.drop_table("test_source_table")
    op.drop_table("tapplicanttypes_synopsis_hist", schema="legacy")
    op.drop_table("tforecast_hist", schema="legacy")
    op.drop_table("test_destination_table")
    op.drop_table("topportunity", schema="legacy")
    op.drop_table("tfundactcat_forecast", schema="legacy")
    op.drop_table("tapplicanttypes_synopsis", schema="legacy")
    op.drop_table("tapplicanttypes_forecast", schema="legacy")
    op.drop_table("tfundactcat_synopsis_hist", schema="legacy")
    op.drop_table("tfundactcat_synopsis", schema="legacy")
    op.drop_table("tsynopsis_hist", schema="legacy")
    op.drop_table("tapplicanttypes_forecast_hist", schema="legacy")
    op.add_column(
        "tapplicanttypes_forecast",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tapplicanttypes_forecast",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tapplicanttypes_forecast",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tapplicanttypes_forecast_hist",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tapplicanttypes_forecast_hist",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tapplicanttypes_forecast_hist",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tapplicanttypes_synopsis",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tapplicanttypes_synopsis",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tapplicanttypes_synopsis",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tapplicanttypes_synopsis_hist",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tapplicanttypes_synopsis_hist",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tapplicanttypes_synopsis_hist",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tforecast",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tforecast",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tforecast",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tforecast_hist",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tforecast_hist",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tforecast_hist",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tfundactcat_forecast",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundactcat_forecast",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundactcat_forecast",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tfundactcat_forecast_hist",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundactcat_forecast_hist",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundactcat_forecast_hist",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tfundactcat_synopsis",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundactcat_synopsis",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundactcat_synopsis",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tfundactcat_synopsis_hist",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundactcat_synopsis_hist",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundactcat_synopsis_hist",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tfundinstr_forecast",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundinstr_forecast",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundinstr_forecast",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tfundinstr_forecast_hist",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundinstr_forecast_hist",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundinstr_forecast_hist",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tfundinstr_synopsis",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundinstr_synopsis",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundinstr_synopsis",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tfundinstr_synopsis_hist",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundinstr_synopsis_hist",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tfundinstr_synopsis_hist",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "topportunity",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "topportunity",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "topportunity",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "topportunity_cfda",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "topportunity_cfda",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "topportunity_cfda",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tsynopsis",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tsynopsis",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tsynopsis",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    op.add_column(
        "tsynopsis_hist",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tsynopsis_hist",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="staging",
    )
    op.add_column(
        "tsynopsis_hist",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="staging",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tsynopsis_hist", "deleted_at", schema="staging")
    op.drop_column("tsynopsis_hist", "updated_at", schema="staging")
    op.drop_column("tsynopsis_hist", "created_at", schema="staging")
    op.drop_column("tsynopsis", "deleted_at", schema="staging")
    op.drop_column("tsynopsis", "updated_at", schema="staging")
    op.drop_column("tsynopsis", "created_at", schema="staging")
    op.drop_column("topportunity_cfda", "deleted_at", schema="staging")
    op.drop_column("topportunity_cfda", "updated_at", schema="staging")
    op.drop_column("topportunity_cfda", "created_at", schema="staging")
    op.drop_column("topportunity", "deleted_at", schema="staging")
    op.drop_column("topportunity", "updated_at", schema="staging")
    op.drop_column("topportunity", "created_at", schema="staging")
    op.drop_column("tfundinstr_synopsis_hist", "deleted_at", schema="staging")
    op.drop_column("tfundinstr_synopsis_hist", "updated_at", schema="staging")
    op.drop_column("tfundinstr_synopsis_hist", "created_at", schema="staging")
    op.drop_column("tfundinstr_synopsis", "deleted_at", schema="staging")
    op.drop_column("tfundinstr_synopsis", "updated_at", schema="staging")
    op.drop_column("tfundinstr_synopsis", "created_at", schema="staging")
    op.drop_column("tfundinstr_forecast_hist", "deleted_at", schema="staging")
    op.drop_column("tfundinstr_forecast_hist", "updated_at", schema="staging")
    op.drop_column("tfundinstr_forecast_hist", "created_at", schema="staging")
    op.drop_column("tfundinstr_forecast", "deleted_at", schema="staging")
    op.drop_column("tfundinstr_forecast", "updated_at", schema="staging")
    op.drop_column("tfundinstr_forecast", "created_at", schema="staging")
    op.drop_column("tfundactcat_synopsis_hist", "deleted_at", schema="staging")
    op.drop_column("tfundactcat_synopsis_hist", "updated_at", schema="staging")
    op.drop_column("tfundactcat_synopsis_hist", "created_at", schema="staging")
    op.drop_column("tfundactcat_synopsis", "deleted_at", schema="staging")
    op.drop_column("tfundactcat_synopsis", "updated_at", schema="staging")
    op.drop_column("tfundactcat_synopsis", "created_at", schema="staging")
    op.drop_column("tfundactcat_forecast_hist", "deleted_at", schema="staging")
    op.drop_column("tfundactcat_forecast_hist", "updated_at", schema="staging")
    op.drop_column("tfundactcat_forecast_hist", "created_at", schema="staging")
    op.drop_column("tfundactcat_forecast", "deleted_at", schema="staging")
    op.drop_column("tfundactcat_forecast", "updated_at", schema="staging")
    op.drop_column("tfundactcat_forecast", "created_at", schema="staging")
    op.drop_column("tforecast_hist", "deleted_at", schema="staging")
    op.drop_column("tforecast_hist", "updated_at", schema="staging")
    op.drop_column("tforecast_hist", "created_at", schema="staging")
    op.drop_column("tforecast", "deleted_at", schema="staging")
    op.drop_column("tforecast", "updated_at", schema="staging")
    op.drop_column("tforecast", "created_at", schema="staging")
    op.drop_column("tapplicanttypes_synopsis_hist", "deleted_at", schema="staging")
    op.drop_column("tapplicanttypes_synopsis_hist", "updated_at", schema="staging")
    op.drop_column("tapplicanttypes_synopsis_hist", "created_at", schema="staging")
    op.drop_column("tapplicanttypes_synopsis", "deleted_at", schema="staging")
    op.drop_column("tapplicanttypes_synopsis", "updated_at", schema="staging")
    op.drop_column("tapplicanttypes_synopsis", "created_at", schema="staging")
    op.drop_column("tapplicanttypes_forecast_hist", "deleted_at", schema="staging")
    op.drop_column("tapplicanttypes_forecast_hist", "updated_at", schema="staging")
    op.drop_column("tapplicanttypes_forecast_hist", "created_at", schema="staging")
    op.drop_column("tapplicanttypes_forecast", "deleted_at", schema="staging")
    op.drop_column("tapplicanttypes_forecast", "updated_at", schema="staging")
    op.drop_column("tapplicanttypes_forecast", "created_at", schema="staging")
    op.create_table(
        "tapplicanttypes_forecast_hist",
        sa.Column("at_frcst_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("at_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "at_frcst_id",
            "at_id",
            "opportunity_id",
            "revision_number",
            name="tapplicanttypes_forecast_hist_pkey",
        ),
        schema="legacy",
    )
    op.create_table(
        "tsynopsis_hist",
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "posting_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "response_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "archive_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "unarchive_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("syn_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("oth_cat_fa_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_addr_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("cost_sharing", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("number_of_awards", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("est_funding", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("award_ceiling", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("award_floor", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fd_link_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fd_link_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_contact_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_email_addr", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_email_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_phone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("a_sa_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_phone_number", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "create_ts", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("sendmail", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("response_date_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("applicant_elig_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("action_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "action_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("version_nbr", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("modification_comments", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisheruid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisher_profile_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("opportunity_id", "revision_number", name="tsynopsis_hist_pkey"),
        schema="legacy",
    )
    op.create_table(
        "tfundactcat_synopsis",
        sa.Column("fac_syn_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("fac_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "fac_syn_id", "fac_id", "opportunity_id", name="tfundactcat_synopsis_pkey"
        ),
        schema="legacy",
    )
    op.create_table(
        "tfundactcat_synopsis_hist",
        sa.Column("fac_syn_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("fac_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "fac_syn_id",
            "fac_id",
            "opportunity_id",
            "revision_number",
            name="tfundactcat_synopsis_hist_pkey",
        ),
        schema="legacy",
    )
    op.create_table(
        "tapplicanttypes_forecast",
        sa.Column("at_frcst_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("at_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "at_frcst_id", "at_id", "opportunity_id", name="tapplicanttypes_forecast_pkey"
        ),
        schema="legacy",
    )
    op.create_table(
        "tapplicanttypes_synopsis",
        sa.Column("at_syn_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("at_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "at_syn_id", "at_id", "opportunity_id", name="tapplicanttypes_synopsis_pkey"
        ),
        schema="legacy",
    )
    op.create_table(
        "tfundactcat_forecast",
        sa.Column("fac_frcst_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("fac_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "fac_frcst_id", "fac_id", "opportunity_id", name="tfundactcat_forecast_pkey"
        ),
        schema="legacy",
    )
    op.create_table(
        "topportunity",
        sa.Column(
            "opportunity_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('legacy.topportunity_opportunity_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("oppnumber", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("opptitle", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("owningagency", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisheruid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("listed", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("oppcategory", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("initial_opportunity_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("modified_comments", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "last_upd_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("flag_2006", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("category_explanation", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisher_profile_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("is_draft", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("opportunity_id", name="topportunity_pkey"),
        schema="legacy",
    )
    op.create_table(
        "test_destination_table",
        sa.Column("id1", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id2", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("x", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("transformed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id1", "id2", name="test_destination_table_pkey"),
    )
    op.create_table(
        "tforecast_hist",
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("version_nbr", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "posting_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "archive_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("forecast_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("oth_cat_fa_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("cost_sharing", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("number_of_awards", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("est_funding", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("award_ceiling", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("award_floor", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fd_link_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fd_link_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_phone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_email_addr", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_email_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("sendmail", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("applicant_elig_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "est_synopsis_posting_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "est_appl_response_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("est_appl_response_date_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "est_award_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "est_project_start_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("fiscal_year", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("modification_comments", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("action_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "action_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "create_ts", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisheruid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisher_profile_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("opportunity_id", "revision_number", name="tforecast_hist_pkey"),
        schema="legacy",
    )
    op.create_table(
        "tapplicanttypes_synopsis_hist",
        sa.Column("at_syn_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("at_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "at_syn_id",
            "at_id",
            "opportunity_id",
            "revision_number",
            name="tapplicanttypes_synopsis_hist_pkey",
        ),
        schema="legacy",
    )
    op.create_table(
        "test_source_table",
        sa.Column("id1", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id2", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("x", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id1", "id2", name="test_source_table_pkey"),
    )
    op.create_table(
        "tsynopsis",
        sa.Column(
            "opportunity_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('legacy.tsynopsis_opportunity_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "posting_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "response_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "archive_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "unarchive_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("syn_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("oth_cat_fa_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_addr_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("cost_sharing", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("number_of_awards", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("est_funding", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("award_ceiling", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("award_floor", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fd_link_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fd_link_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_contact_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_email_addr", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_email_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_phone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("a_sa_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_phone_number", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "create_ts", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("sendmail", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("response_date_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("applicant_elig_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("version_nbr", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("modification_comments", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisheruid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisher_profile_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("opportunity_id", name="tsynopsis_pkey"),
        schema="legacy",
    )
    op.create_table(
        "tfundinstr_forecast",
        sa.Column("fi_frcst_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("fi_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "fi_frcst_id", "fi_id", "opportunity_id", name="tfundinstr_forecast_pkey"
        ),
        schema="legacy",
    )
    op.create_table(
        "tforecast",
        sa.Column(
            "opportunity_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('legacy.tforecast_opportunity_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("version_nbr", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "posting_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "archive_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("forecast_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("oth_cat_fa_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("cost_sharing", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("number_of_awards", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("est_funding", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("award_ceiling", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("award_floor", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fd_link_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fd_link_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_phone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_email_addr", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_email_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("sendmail", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("applicant_elig_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "est_synopsis_posting_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "est_appl_response_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("est_appl_response_date_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "est_award_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "est_project_start_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("fiscal_year", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("modification_comments", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "create_ts", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisheruid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisher_profile_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("opportunity_id", name="tforecast_pkey"),
        schema="legacy",
    )
    op.create_table(
        "tfundinstr_forecast_hist",
        sa.Column("fi_frcst_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("fi_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "fi_frcst_id",
            "fi_id",
            "opportunity_id",
            "revision_number",
            name="tfundinstr_forecast_hist_pkey",
        ),
        schema="legacy",
    )
    op.create_table(
        "tfundinstr_synopsis",
        sa.Column("fi_syn_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("fi_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "fi_syn_id", "fi_id", "opportunity_id", name="tfundinstr_synopsis_pkey"
        ),
        schema="legacy",
    )
    op.create_table(
        "t2",
        sa.Column("x", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("y", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("z", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("x", "y", name="t2_pkey"),
        schema="api",
    )
    op.create_table(
        "tfundactcat_forecast_hist",
        sa.Column("fac_frcst_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("fac_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "fac_frcst_id",
            "fac_id",
            "opportunity_id",
            "revision_number",
            name="tfundactcat_forecast_hist_pkey",
        ),
        schema="legacy",
    )
    op.create_table(
        "tfundinstr_synopsis_hist",
        sa.Column("fi_syn_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("fi_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "fi_syn_id",
            "opportunity_id",
            "fi_id",
            "revision_number",
            name="tfundinstr_synopsis_hist_pkey",
        ),
        schema="legacy",
    )
    op.create_table(
        "t1",
        sa.Column("x", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("y", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("z", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("x", "y", name="t1_pkey"),
        schema="api",
    )
    op.create_table(
        "topportunity_cfda",
        sa.Column(
            "opp_cfda_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('legacy.topportunity_cfda_opp_cfda_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("cfdanumber", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("programtitle", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("origtoppid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("oppidcfdanum", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("origoppnum", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("opp_cfda_id", name="topportunity_cfda_pkey"),
        schema="legacy",
    )
    # ### end Alembic commands ###
