"""Add indexes for search

Revision ID: 35062145d2ff
Revises: 578c80acb29c
Create Date: 2024-03-12 12:13:20.649288

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "35062145d2ff"
down_revision = "578c80acb29c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("current_opportunity_summary_opportunity_id_idx"),
        "current_opportunity_summary",
        ["opportunity_id"],
        unique=False,
    )
    op.create_index(
        op.f("current_opportunity_summary_opportunity_status_id_idx"),
        "current_opportunity_summary",
        ["opportunity_status_id"],
        unique=False,
    )
    op.create_index(
        op.f("current_opportunity_summary_opportunity_summary_id_idx"),
        "current_opportunity_summary",
        ["opportunity_summary_id"],
        unique=False,
    )
    op.create_index(
        op.f("link_opportunity_summary_applicant_type_applicant_type_id_idx"),
        "link_opportunity_summary_applicant_type",
        ["applicant_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("link_opportunity_summary_applicant_type_opportunity_summary_id_idx"),
        "link_opportunity_summary_applicant_type",
        ["opportunity_summary_id"],
        unique=False,
    )
    op.create_index(
        op.f("link_opportunity_summary_funding_category_funding_category_id_idx"),
        "link_opportunity_summary_funding_category",
        ["funding_category_id"],
        unique=False,
    )
    op.create_index(
        op.f("link_opportunity_summary_funding_category_opportunity_summary_id_idx"),
        "link_opportunity_summary_funding_category",
        ["opportunity_summary_id"],
        unique=False,
    )
    op.create_index(
        op.f("link_opportunity_summary_funding_instrument_funding_instrument_id_idx"),
        "link_opportunity_summary_funding_instrument",
        ["funding_instrument_id"],
        unique=False,
    )
    op.create_index(
        op.f("link_opportunity_summary_funding_instrument_opportunity_summary_id_idx"),
        "link_opportunity_summary_funding_instrument",
        ["opportunity_summary_id"],
        unique=False,
    )
    op.create_index(op.f("opportunity_agency_idx"), "opportunity", ["agency"], unique=False)
    op.create_index(
        op.f("opportunity_summary_opportunity_id_idx"),
        "opportunity_summary",
        ["opportunity_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("opportunity_summary_opportunity_id_idx"), table_name="opportunity_summary")
    op.drop_index(op.f("opportunity_agency_idx"), table_name="opportunity")
    op.drop_index(
        op.f("link_opportunity_summary_funding_instrument_opportunity_summary_id_idx"),
        table_name="link_opportunity_summary_funding_instrument",
    )
    op.drop_index(
        op.f("link_opportunity_summary_funding_instrument_funding_instrument_id_idx"),
        table_name="link_opportunity_summary_funding_instrument",
    )
    op.drop_index(
        op.f("link_opportunity_summary_funding_category_opportunity_summary_id_idx"),
        table_name="link_opportunity_summary_funding_category",
    )
    op.drop_index(
        op.f("link_opportunity_summary_funding_category_funding_category_id_idx"),
        table_name="link_opportunity_summary_funding_category",
    )
    op.drop_index(
        op.f("link_opportunity_summary_applicant_type_opportunity_summary_id_idx"),
        table_name="link_opportunity_summary_applicant_type",
    )
    op.drop_index(
        op.f("link_opportunity_summary_applicant_type_applicant_type_id_idx"),
        table_name="link_opportunity_summary_applicant_type",
    )
    op.drop_index(
        op.f("current_opportunity_summary_opportunity_summary_id_idx"),
        table_name="current_opportunity_summary",
    )
    op.drop_index(
        op.f("current_opportunity_summary_opportunity_status_id_idx"),
        table_name="current_opportunity_summary",
    )
    op.drop_index(
        op.f("current_opportunity_summary_opportunity_id_idx"),
        table_name="current_opportunity_summary",
    )
    # ### end Alembic commands ###
