"""rename agency column

Revision ID: 66fc09ea856b
Revises: 39f7f941fc6c
Create Date: 2024-10-24 13:23:10.851123

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "66fc09ea856b"
down_revision = "39f7f941fc6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("opportunity", "agency", new_column_name="agency_code", schema="api")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("opportunity", "agency_code", new_column_name="agency", schema="api")
    # ### end Alembic commands ###
