"""Add top level agency field

Revision ID: 39f7f941fc6c
Revises: 558ad9563e9a
Create Date: 2024-10-17 20:08:55.193636

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "39f7f941fc6c"
down_revision = "558ad9563e9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agency", sa.Column("top_level_agency_id", sa.BigInteger(), nullable=True), schema="api"
    )
    op.create_foreign_key(
        op.f("agency_top_level_agency_id_agency_fkey"),
        "agency",
        "agency",
        ["top_level_agency_id"],
        ["agency_id"],
        source_schema="api",
        referent_schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("agency_top_level_agency_id_agency_fkey"), "agency", schema="api", type_="foreignkey"
    )
    op.drop_column("agency", "top_level_agency_id", schema="api")
    # ### end Alembic commands ###
