"""add is_simpler_grants_enabled to competition table

Revision ID: b5946cdc3859
Revises: 9439bffdbc52
Create Date: 2025-06-25 15:33:17.619598

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b5946cdc3859"
down_revision = "9439bffdbc52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "competition",
        sa.Column("is_simpler_grants_enabled", sa.Boolean(), nullable=True),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("competition", "is_simpler_grants_enabled", schema="api")
    # ### end Alembic commands ###
