"""change_name_of_tcertificate_to_tcertificates

Revision ID: 43622a46494e
Revises: 87f28b5e40d5
Create Date: 2025-10-29 20:24:09.458867

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "43622a46494e"
down_revision = "87f28b5e40d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tcertificates",
        sa.Column("currentcertid", sa.Text(), nullable=False),
        sa.Column("previouscertid", sa.Text(), nullable=True),
        sa.Column("orgduns", sa.Text(), nullable=True),
        sa.Column("orgname", sa.Text(), nullable=True),
        sa.Column("expirationdate", sa.Date(), nullable=True),
        sa.Column("certemail", sa.Text(), nullable=False),
        sa.Column("agencyid", sa.Text(), nullable=True),
        sa.Column("requestorlname", sa.Text(), nullable=True),
        sa.Column("requestorfname", sa.Text(), nullable=True),
        sa.Column("requestoremail", sa.Text(), nullable=True),
        sa.Column("requestorphone", sa.Text(), nullable=True),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("creator_id", sa.Text(), nullable=False),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_selfsigned", sa.Text(), nullable=False),
        sa.Column("serial_num", sa.Text(), nullable=True),
        sa.Column("system_name", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("transformation_notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("currentcertid", name=op.f("tcertificates_pkey")),
        schema="staging",
    )
    op.create_index(
        op.f("tcertificates_transformed_at_idx"),
        "tcertificates",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.drop_index(
        op.f("tcertificate_transformed_at_idx"), table_name="tcertificate", schema="staging"
    )
    op.drop_table("tcertificate", schema="staging")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tcertificate",
        sa.Column("currentcertid", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("previouscertid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("orgduns", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("orgname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("expirationdate", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("certemail", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("agencyid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("requestorlname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("requestorfname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("requestoremail", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("requestorphone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_selfsigned", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("serial_num", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("system_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "transformed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("transformation_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("currentcertid", name=op.f("tcertificate_pkey")),
        schema="staging",
    )
    op.create_index(
        op.f("tcertificate_transformed_at_idx"),
        "tcertificate",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.drop_index(
        op.f("tcertificates_transformed_at_idx"), table_name="tcertificates", schema="staging"
    )
    op.drop_table("tcertificates", schema="staging")
    # ### end Alembic commands ###
