"""add short-lived internal token table

Revision ID: a10c4a8ecd42
Revises: bf5b294a7b85
Create Date: 2025-06-20 18:50:27.032515

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a10c4a8ecd42"
down_revision = "bf5b294a7b85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "short_lived_internal_token",
        sa.Column("short_lived_internal_token_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "short_lived_internal_token_id", name=op.f("short_lived_internal_token_pkey")
        ),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("short_lived_internal_token", schema="api")
    # ### end Alembic commands ###
