"""Add application_user table

Revision ID: b4aad25f47bc
Revises: 3b0705202c54
Create Date: 2025-04-30 14:02:54.814779

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b4aad25f47bc"
down_revision = "3b0705202c54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_user",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["api.application.application_id"],
            name=op.f("application_user_application_id_application_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["api.user.user_id"], name=op.f("application_user_user_id_user_fkey")
        ),
        sa.PrimaryKeyConstraint("application_id", "user_id", name=op.f("application_user_pkey")),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("application_user", schema="api")
    # ### end Alembic commands ###
