"""Rename responded_by_user_id to invitee_user_id and make nullable in organization_invitation

Revision ID: c286e166223b
Revises: e0feb8f532bc
Create Date: 2025-10-23 14:22:59.016098

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c286e166223b"
down_revision = "e0feb8f532bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_invitation",
        sa.Column("invitee_user_id", sa.UUID(), nullable=True),
        schema="api",
    )
    op.drop_constraint(
        op.f("organization_invitation_responded_by_user_id_user_fkey"),
        "organization_invitation",
        schema="api",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("organization_invitation_invitee_user_id_user_fkey"),
        "organization_invitation",
        "user",
        ["invitee_user_id"],
        ["user_id"],
        source_schema="api",
        referent_schema="api",
    )
    op.drop_column("organization_invitation", "responded_by_user_id", schema="api")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_invitation",
        sa.Column("responded_by_user_id", sa.UUID(), autoincrement=False, nullable=False),
        schema="api",
    )
    op.drop_constraint(
        op.f("organization_invitation_invitee_user_id_user_fkey"),
        "organization_invitation",
        schema="api",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("organization_invitation_responded_by_user_id_user_fkey"),
        "organization_invitation",
        "user",
        ["responded_by_user_id"],
        ["user_id"],
        source_schema="api",
        referent_schema="api",
    )
    op.drop_column("organization_invitation", "invitee_user_id", schema="api")
    # ### end Alembic commands ###
