"""Add legacy competition table

Revision ID: 617374e55b71
Revises: 20f73906ed2a
Create Date: 2025-04-11 18:46:31.938384

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "617374e55b71"
down_revision = "20f73906ed2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tcompetition",
        sa.Column("comp_id", sa.BigInteger(), nullable=False),
        sa.Column("opp_cfda_id", sa.BigInteger(), nullable=True),
        sa.Column("competitionid", sa.Text(), nullable=True),
        sa.Column("familyid", sa.BigInteger(), nullable=True),
        sa.Column("competitiontitle", sa.Text(), nullable=True),
        sa.Column("openingdate", sa.Date(), nullable=True),
        sa.Column("closingdate", sa.Date(), nullable=True),
        sa.Column("contactinfo", sa.Text(), nullable=True),
        sa.Column("graceperiod", sa.BigInteger(), nullable=True),
        sa.Column("opentoapplicanttype", sa.BigInteger(), nullable=True),
        sa.Column("dialect", sa.Text(), nullable=False),
        sa.Column("last_update", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("electronic_required", sa.Text(), nullable=True),
        sa.Column("expected_appl_num", sa.BigInteger(), nullable=True),
        sa.Column("expected_appl_size", sa.BigInteger(), nullable=True),
        sa.Column("origcfdanum", sa.Text(), nullable=True),
        sa.Column("origoppnumber", sa.Text(), nullable=True),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("ismulti", sa.Text(), nullable=True),
        sa.Column("agency_dwnld_url", sa.Text(), nullable=True),
        sa.Column("package_id", sa.Text(), nullable=True),
        sa.Column("is_wrkspc_compatible", sa.Text(), nullable=False),
        sa.Column("sendmail", sa.Text(), nullable=True),
        sa.Column("modification_comments", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("transformation_notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("comp_id", name=op.f("tcompetition_pkey")),
        schema="staging",
    )
    op.create_index(
        op.f("tcompetition_transformed_at_idx"),
        "tcompetition",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("tcompetition_transformed_at_idx"), table_name="tcompetition", schema="staging"
    )
    op.drop_table("tcompetition", schema="staging")
    # ### end Alembic commands ###
