"""fix vuser_account last_upd_date nullable

Revision ID: 1d7fc98e951a
Revises: d54ee90a403b
Create Date: 2025-12-04 17:33:36.304359

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1d7fc98e951a"
down_revision = "d54ee90a403b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vuser_account",
        "last_upd_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        schema="staging",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vuser_account",
        "last_upd_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        schema="staging",
    )
    # ### end Alembic commands ###
