"""add saved_opportunity_ids and last_notified_at to user_saved_opportunity

Revision ID: 2408905c1435
Revises: dc04ce955a9a
Create Date: 2025-01-28 16:57:55.572278

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2408905c1435"
down_revision = "dc04ce955a9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_saved_search",
        sa.Column(
            "last_notified_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="api",
    )
    op.add_column(
        "user_saved_search",
        sa.Column("searched_opportunity_ids", postgresql.ARRAY(sa.Integer()), nullable=False),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_saved_search", "searched_opportunity_ids", schema="api")
    op.drop_column("user_saved_search", "last_notified_at", schema="api")
    # ### end Alembic commands ###
