"""add_organization_audit_table

Revision ID: aa091607965d
Revises: 78081116ef9e
Create Date: 2025-12-16 18:16:47.676403

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aa091607965d"
down_revision = "78081116ef9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_organization_audit_event",
        sa.Column("organization_audit_event_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "organization_audit_event_id", name=op.f("lk_organization_audit_event_pkey")
        ),
        schema="api",
    )
    op.create_table(
        "organization_audit",
        sa.Column("organization_audit_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("organization_audit_event_id", sa.Integer(), nullable=False),
        sa.Column("target_user_id", sa.UUID(), nullable=True),
        sa.Column("audit_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_audit_event_id"],
            ["api.lk_organization_audit_event.organization_audit_event_id"],
            name=op.f(
                "organization_audit_organization_audit_event_id_lk_organization_audit_event_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["api.organization.organization_id"],
            name=op.f("organization_audit_organization_id_organization_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["api.user.user_id"],
            name=op.f("organization_audit_target_user_id_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["api.user.user_id"], name=op.f("organization_audit_user_id_user_fkey")
        ),
        sa.PrimaryKeyConstraint("organization_audit_id", name=op.f("organization_audit_pkey")),
        schema="api",
    )
    op.create_index(
        op.f("organization_audit_organization_id_idx"),
        "organization_audit",
        ["organization_id"],
        unique=False,
        schema="api",
    )
    op.create_index(
        op.f("organization_audit_target_user_id_idx"),
        "organization_audit",
        ["target_user_id"],
        unique=False,
        schema="api",
    )
    op.create_index(
        op.f("organization_audit_user_id_idx"),
        "organization_audit",
        ["user_id"],
        unique=False,
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("organization_audit_user_id_idx"), table_name="organization_audit", schema="api"
    )
    op.drop_index(
        op.f("organization_audit_target_user_id_idx"), table_name="organization_audit", schema="api"
    )
    op.drop_index(
        op.f("organization_audit_organization_id_idx"),
        table_name="organization_audit",
        schema="api",
    )
    op.drop_table("organization_audit", schema="api")
    op.drop_table("lk_organization_audit_event", schema="api")
    # ### end Alembic commands ###
