"""add_excluded_opportunity_review_table

Revision ID: e79e8dd701ac
Revises: 0754d335287c
Create Date: 2025-08-22 15:43:45.139738

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e79e8dd701ac"
down_revision = "0754d335287c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "excluded_opportunity_review",
        sa.Column("legacy_opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("omb_review_status_display", sa.Text(), nullable=False),
        sa.Column("omb_review_status_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_update_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "legacy_opportunity_id", name=op.f("excluded_opportunity_review_pkey")
        ),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("excluded_opportunity_review", schema="api")
    # ### end Alembic commands ###
