"""add_suppressed_email_table

Revision ID: 6e52e053c111
Revises: 0f085993b457
Create Date: 2025-07-30 15:49:15.202051

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6e52e053c111"
down_revision = "0f085993b457"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppressed_email",
        sa.Column("suppressed_email_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("last_update_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("suppressed_email_id", name=op.f("suppressed_email_pkey")),
        schema="api",
    )
    op.create_index(
        op.f("suppressed_email_email_idx"),
        "suppressed_email",
        ["email"],
        unique=False,
        schema="api",
    )
    op.create_index(
        op.f("suppressed_email_last_update_time_idx"),
        "suppressed_email",
        ["last_update_time"],
        unique=False,
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("suppressed_email_last_update_time_idx"), table_name="suppressed_email", schema="api"
    )
    op.drop_index(op.f("suppressed_email_email_idx"), table_name="suppressed_email", schema="api")
    op.drop_table("suppressed_email", schema="api")
    # ### end Alembic commands ###
