"""add opportunity id

Revision ID: f5ba8d333815
Revises: 56d129425397
Create Date: 2025-02-25 20:06:47.391411

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f5ba8d333815"
down_revision = "56d129425397"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_notification_log",
        sa.Column("opportunity_id", sa.BigInteger(), nullable=True),
        schema="api",
    )
    op.create_index(
        op.f("user_notification_log_opportunity_id_idx"),
        "user_notification_log",
        ["opportunity_id"],
        unique=False,
        schema="api",
    )
    op.create_foreign_key(
        op.f("user_notification_log_opportunity_id_opportunity_fkey"),
        "user_notification_log",
        "opportunity",
        ["opportunity_id"],
        ["opportunity_id"],
        source_schema="api",
        referent_schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("user_notification_log_opportunity_id_opportunity_fkey"),
        "user_notification_log",
        schema="api",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("user_notification_log_opportunity_id_idx"),
        table_name="user_notification_log",
        schema="api",
    )
    op.drop_column("user_notification_log", "opportunity_id", schema="api")
    # ### end Alembic commands ###
