"""Add application_name field to application table

Revision ID: 2a5f2235a428
Revises: 5fe2cac38b7f
Create Date: 2025-05-14 18:24:49.753177

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a5f2235a428"
down_revision = "5fe2cac38b7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application", sa.Column("application_name", sa.Text(), nullable=True), schema="api"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "application_name", schema="api")
    # ### end Alembic commands ###
