"""add_staging_tcertificate_uuid

Revision ID: 4d2cd887708b
Revises: df81941231ad
Create Date: 2025-11-14 20:34:09.872788

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d2cd887708b"
down_revision = "19e80334aaae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tcertificates",
        sa.Column(
            "tcertificates_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=True,
        ),
        schema="staging",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tcertificates", "tcertificates_id", schema="staging")
    # ### end Alembic commands ###
