"""add_lk_user_type_and_add_to_user

Revision ID: 618216bb724a
Revises: cdfb9202130e
Create Date: 2025-11-06 19:29:05.331555

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "618216bb724a"
down_revision = "878613347a9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_user_type",
        sa.Column("user_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_type_id", name=op.f("lk_user_type_pkey")),
        schema="api",
    )
    op.add_column("user", sa.Column("user_type_id", sa.Integer(), nullable=True), schema="api")
    op.create_foreign_key(
        op.f("user_user_type_id_lk_user_type_fkey"),
        "user",
        "lk_user_type",
        ["user_type_id"],
        ["user_type_id"],
        source_schema="api",
        referent_schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("user_user_type_id_lk_user_type_fkey"), "user", schema="api", type_="foreignkey"
    )
    op.drop_column("user", "user_type_id", schema="api")
    op.drop_table("lk_user_type", schema="api")
    # ### end Alembic commands ###
