"""add version queue column

Revision ID: 96c81f27d075
Revises: 448ee11789b1
Create Date: 2025-07-11 16:47:12.468974

"""

import sqlalchemy as sa
from alembic import op

from src.db.migrations.utils import setup_opportunity_search_index_queue_trigger_function

# revision identifiers, used by Alembic.
revision = "96c81f27d075"
down_revision = "448ee11789b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "opportunity_change_audit",
        sa.Column("has_been_versioned", sa.Boolean(), nullable=True),
        schema="api",
    )

    # Add search index triggers
    setup_opportunity_search_index_queue_trigger_function(
        op,
        [
            "opportunity",
            "opportunity_assistance_listing",
            "current_opportunity_summary",
            "opportunity_summary",
            "link_opportunity_summary_funding_instrument",
            "link_opportunity_summary_funding_category",
            "link_opportunity_summary_applicant_type",
            "opportunity_attachment",
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("opportunity_change_audit", "has_been_versioned", schema="api")
    # ### end Alembic commands ###
