"""Remove historical action_type columns

Revision ID: d0390a30efb7
Revises: 56d129425397
Create Date: 2025-02-18 19:41:26.847617

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d0390a30efb7"
down_revision = "56d129425397"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tforecast_hist", "action_type", schema="staging")
    op.drop_column("tsynopsis_hist", "action_type", schema="staging")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tsynopsis_hist",
        sa.Column("action_type", sa.TEXT(), autoincrement=False, nullable=True),
        schema="staging",
    )
    op.add_column(
        "tforecast_hist",
        sa.Column("action_type", sa.TEXT(), autoincrement=False, nullable=True),
        schema="staging",
    )
    # ### end Alembic commands ###
