"""add is deleted col to user saved tables

Revision ID: 5fe2cac38b7f
Revises: b4aad25f47bc
Create Date: 2025-05-08 19:51:41.692050

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5fe2cac38b7f"
down_revision = "b4aad25f47bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_saved_opportunity",
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        schema="api",
    )
    op.add_column(
        "user_saved_search", sa.Column("is_deleted", sa.Boolean(), nullable=True), schema="api"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_saved_search", "is_deleted", schema="api")
    op.drop_column("user_saved_opportunity", "is_deleted", schema="api")
    # ### end Alembic commands ###
