"""Update form_type_id

Revision ID: 5060847aba92
Revises: 5f8e99a128b7
Create Date: 2025-10-03 17:49:11.398034

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5060847aba92"
down_revision = "5f8e99a128b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "form", "form_type_id", existing_type=sa.INTEGER(), nullable=False, schema="api"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("form", "form_type_id", existing_type=sa.INTEGER(), nullable=True, schema="api")
    # ### end Alembic commands ###
