"""Assign application owner role to existing application owners

Revision ID: bfd8ad9cf5d6
Revises: e4ac8da61902
Create Date: 2025-09-16 16:51:37.082923

"""

from alembic import op
from sqlalchemy import text

from src.constants.static_role_values import APPLICATION_OWNER_ID

# revision identifiers, used by Alembic.
revision = "bfd8ad9cf5d6"
down_revision = "e4ac8da61902"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Insert Application Owner role assignments for all existing application owners
    # who don't already have the role
    op.execute(
        text(
            """
        INSERT INTO api.application_user_role (application_user_id, role_id, created_at, updated_at)
        SELECT
            au.application_user_id,
            :role_id,
            NOW(),
            NOW()
        FROM api.application_user au
        WHERE au.is_application_owner = true
        AND NOT EXISTS (
            SELECT 1
            FROM api.application_user_role aur
            WHERE aur.application_user_id = au.application_user_id
            AND aur.role_id = :role_id
        );
        """
        ).params(role_id=APPLICATION_OWNER_ID)
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Not including downgrade as we might need to do some additional filters
    pass
    # ### end Alembic commands ###
