"""add FK Opportunity to Agen`

Revision ID: 78081116ef9e
Revises: 15f2daa87f8b
Create Date: 2025-12-09 16:41:15.052121

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "78081116ef9e"
down_revision = "15f2daa87f8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("opportunity", sa.Column("agency_id", sa.UUID(), nullable=True), schema="api")
    op.create_index(
        op.f("opportunity_agency_id_idx"), "opportunity", ["agency_id"], unique=False, schema="api"
    )
    op.create_foreign_key(
        op.f("opportunity_agency_id_agency_fkey"),
        "opportunity",
        "agency",
        ["agency_id"],
        ["agency_id"],
        source_schema="api",
        referent_schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("opportunity_agency_id_agency_fkey"), "opportunity", schema="api", type_="foreignkey"
    )
    op.drop_index(op.f("opportunity_agency_id_idx"), table_name="opportunity", schema="api")
    op.drop_column("opportunity", "agency_id", schema="api")
    # ### end Alembic commands ###
