"""Create organization and sam.gov entity DB tables

Revision ID: 6c83a4294387
Revises: 3b0705202c54
Create Date: 2025-04-30 16:49:48.316390

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c83a4294387"
down_revision = "3b0705202c54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_sam_gov_import_type",
        sa.Column("sam_gov_import_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("sam_gov_import_type_id", name=op.f("lk_sam_gov_import_type_pkey")),
        schema="api",
    )
    op.create_table(
        "sam_gov_entity",
        sa.Column("sam_gov_entity_id", sa.UUID(), nullable=False),
        sa.Column("uei", sa.Text(), nullable=False),
        sa.Column("legal_business_name", sa.Text(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=False),
        sa.Column("ebiz_poc_email", sa.Text(), nullable=False),
        sa.Column("ebiz_poc_first_name", sa.Text(), nullable=False),
        sa.Column("ebiz_poc_last_name", sa.Text(), nullable=False),
        sa.Column("has_debt_subject_to_offset", sa.Boolean(), nullable=True),
        sa.Column("has_exclusion_status", sa.Boolean(), nullable=True),
        sa.Column("eft_indicator", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("sam_gov_entity_id", name=op.f("sam_gov_entity_pkey")),
        schema="api",
    )
    op.create_index(
        op.f("sam_gov_entity_uei_idx"), "sam_gov_entity", ["uei"], unique=False, schema="api"
    )
    op.create_table(
        "organization",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("sam_gov_entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sam_gov_entity_id"],
            ["api.sam_gov_entity.sam_gov_entity_id"],
            name=op.f("organization_sam_gov_entity_id_sam_gov_entity_fkey"),
        ),
        sa.PrimaryKeyConstraint("organization_id", name=op.f("organization_pkey")),
        schema="api",
    )
    op.create_table(
        "sam_gov_entity_import_type",
        sa.Column("sam_gov_entity_import_id", sa.UUID(), nullable=False),
        sa.Column("sam_gov_entity_id", sa.UUID(), nullable=False),
        sa.Column("sam_gov_import_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sam_gov_entity_id"],
            ["api.sam_gov_entity.sam_gov_entity_id"],
            name=op.f("sam_gov_entity_import_type_sam_gov_entity_id_sam_gov_entity_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["sam_gov_import_type_id"],
            ["api.lk_sam_gov_import_type.sam_gov_import_type_id"],
            name=op.f(
                "sam_gov_entity_import_type_sam_gov_import_type_id_lk_sam_gov_import_type_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "sam_gov_entity_import_id", name=op.f("sam_gov_entity_import_type_pkey")
        ),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sam_gov_entity_import_type", schema="api")
    op.drop_table("organization", schema="api")
    op.drop_index(op.f("sam_gov_entity_uei_idx"), table_name="sam_gov_entity", schema="api")
    op.drop_table("sam_gov_entity", schema="api")
    op.drop_table("lk_sam_gov_import_type", schema="api")
    # ### end Alembic commands ###
