"""Add staging table for TINSTRUCTIONS

Revision ID: 5db7e263238a
Revises: 2a5f2235a428
Create Date: 2025-05-21 23:12:30.459340

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5db7e263238a"
down_revision = "2a5f2235a428"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tinstructions",
        sa.Column("comp_id", sa.BigInteger(), nullable=False),
        sa.Column("extension", sa.Text(), nullable=True),
        sa.Column("mimetype", sa.Text(), nullable=True),
        sa.Column("instructions", sa.LargeBinary(), nullable=True),
        sa.Column("last_update", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_upd_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("creator_id", sa.Text(), nullable=True),
        sa.Column("last_upd_id", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("transformed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("transformation_notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("comp_id", name=op.f("tinstructions_pkey")),
        schema="staging",
    )
    op.create_index(
        op.f("tinstructions_transformed_at_idx"),
        "tinstructions",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("tinstructions_transformed_at_idx"), table_name="tinstructions", schema="staging"
    )
    op.drop_table("tinstructions", schema="staging")
    # ### end Alembic commands ###
