"""Create application submission table

Revision ID: 448ee11789b1
Revises: 4fe76320503b
Create Date: 2025-06-27 13:39:50.381509

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "448ee11789b1"
down_revision = "4fe76320503b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_submission",
        sa.Column("application_submission_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("file_location", sa.Text(), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["api.application.application_id"],
            name=op.f("application_submission_application_id_application_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "application_submission_id", name=op.f("application_submission_pkey")
        ),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("application_submission", schema="api")
    # ### end Alembic commands ###
