"""Create Extract Metadata Table with UUID primary key

Revision ID: 20f73906ed2a
Revises: 3fcfd97a668c
Create Date: 2025-03-31 22:53:15.613438

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20f73906ed2a"
down_revision = "3fcfd97a668c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extract_metadata",
        sa.Column("extract_metadata_id", sa.UUID(), nullable=False),
        sa.Column("extract_type_id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["extract_type_id"],
            ["api.lk_extract_type.extract_type_id"],
            name=op.f("extract_metadata_extract_type_id_lk_extract_type_fkey"),
        ),
        sa.PrimaryKeyConstraint("extract_metadata_id", name=op.f("extract_metadata_pkey")),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("extract_metadata", schema="api")
    # ### end Alembic commands ###
