"""add_ignored_legacy_organization_user_table

Revision ID: 19e80334aaae
Revises: df81941231ad
Create Date: 2025-11-13 21:16:33.936592

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "19e80334aaae"
down_revision = "df81941231ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ignored_legacy_organization_user",
        sa.Column("ignored_legacy_organization_user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("ignored_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ignored_by_user_id"],
            ["api.user.user_id"],
            name=op.f("ignored_legacy_organization_user_ignored_by_user_id_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["api.organization.organization_id"],
            name=op.f("ignored_legacy_organization_user_organization_id_organization_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "ignored_legacy_organization_user_id",
            name=op.f("ignored_legacy_organization_user_pkey"),
        ),
        sa.UniqueConstraint(
            "organization_id",
            "email",
            name=op.f("ignored_legacy_organization_user_organization_id_uniq"),
        ),
        schema="api",
    )
    op.create_index(
        op.f("ignored_legacy_organization_user_email_idx"),
        "ignored_legacy_organization_user",
        ["email"],
        unique=False,
        schema="api",
    )
    op.create_index(
        op.f("ignored_legacy_organization_user_ignored_by_user_id_idx"),
        "ignored_legacy_organization_user",
        ["ignored_by_user_id"],
        unique=False,
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ignored_legacy_organization_user_ignored_by_user_id_idx"),
        table_name="ignored_legacy_organization_user",
        schema="api",
    )
    op.drop_index(
        op.f("ignored_legacy_organization_user_email_idx"),
        table_name="ignored_legacy_organization_user",
        schema="api",
    )
    op.drop_table("ignored_legacy_organization_user", schema="api")
    # ### end Alembic commands ###
