"""add loaded opportunity change audit table

Revision ID: 48c6de6f43ba
Revises: 8f5a763ccc79
Create Date: 2025-03-12 17:43:13.427015

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "48c6de6f43ba"
down_revision = "8f5a763ccc79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "opportunity_change_audit", sa.Column("loaded", sa.Boolean(), nullable=True), schema="api"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("opportunity_change_audit", "loaded", schema="api")
    # ### end Alembic commands ###
