"""drop_legacy_user_account_and_mapper_tables

Revision ID: 627e63fb1eae
Revises: a73e934149e5
Create Date: 2025-12-17 21:04:04.719601

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "627e63fb1eae"
down_revision = "a73e934149e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("tuser_account_transformed_at_idx"), table_name="tuser_account", schema="staging"
    )
    op.drop_table("tuser_account", schema="staging")
    op.drop_index(
        op.f("tuser_account_mapper_transformed_at_idx"),
        table_name="tuser_account_mapper",
        schema="staging",
    )
    op.drop_table("tuser_account_mapper", schema="staging")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tuser_account_mapper",
        sa.Column("user_account_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("ext_user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("ext_issuer", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "last_auth_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("ext_subject", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("source_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "transformed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("transformation_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "user_account_id", "source_type", name=op.f("tuser_account_mapper_pkey")
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tuser_account_mapper_transformed_at_idx"),
        "tuser_account_mapper",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tuser_account",
        sa.Column("user_account_id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("full_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("email_address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("phone_number", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("first_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("middle_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_deleted_legacy", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_duplicate", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_email_confirm_pending", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "deactivated_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("mobile_number", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "transformed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("transformation_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("user_account_id", name=op.f("tuser_account_pkey")),
        schema="staging",
    )
    op.create_index(
        op.f("tuser_account_transformed_at_idx"),
        "tuser_account",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    # ### end Alembic commands ###
