"""Add application status table and field

Revision ID: 462b5b67c0ea
Revises: 3b0705202c54
Create Date: 2025-05-02 17:17:28.799500

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "462b5b67c0ea"
down_revision = "3b0705202c54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_application_status",
        sa.Column("application_status_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("application_status_id", name=op.f("lk_application_status_pkey")),
        schema="api",
    )
    op.add_column(
        "application", sa.Column("application_status_id", sa.Integer(), nullable=True), schema="api"
    )
    op.create_foreign_key(
        op.f("application_application_status_id_lk_application_status_fkey"),
        "application",
        "lk_application_status",
        ["application_status_id"],
        ["application_status_id"],
        source_schema="api",
        referent_schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("application_application_status_id_lk_application_status_fkey"),
        "application",
        schema="api",
        type_="foreignkey",
    )
    op.drop_column("application", "application_status_id", schema="api")
    op.drop_table("lk_application_status", schema="api")
    # ### end Alembic commands ###
