"""add_lk_user_type_to_user

Revision ID: 20eb0b848e1d
Revises: 9f919a9e045e
Create Date: 2025-11-04 18:43:34.137899

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20eb0b848e1d"
down_revision = "9f919a9e045e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("user_type_id", sa.Integer(), nullable=True), schema="api")
    op.create_foreign_key(
        op.f("user_user_type_id_lk_user_type_fkey"),
        "user",
        "lk_user_type",
        ["user_type_id"],
        ["user_type_id"],
        source_schema="api",
        referent_schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("user_user_type_id_lk_user_type_fkey"), "user", schema="api", type_="foreignkey"
    )
    op.drop_column("user", "user_type_id", schema="api")
    # ### end Alembic commands ###
