"""Create sam extract files

Revision ID: 585d0e5aaddb
Revises: 3b0705202c54
Create Date: 2025-05-07 18:58:38.706849

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "585d0e5aaddb"
down_revision = "3b0705202c54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_sam_gov_extract_type",
        sa.Column("sam_gov_extract_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "sam_gov_extract_type_id", name=op.f("lk_sam_gov_extract_type_pkey")
        ),
        schema="api",
    )
    op.create_table(
        "lk_sam_gov_processing_status",
        sa.Column("sam_gov_processing_status_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "sam_gov_processing_status_id", name=op.f("lk_sam_gov_processing_status_pkey")
        ),
        schema="api",
    )
    op.create_table(
        "sam_extract_file",
        sa.Column("sam_extract_file_id", sa.UUID(), nullable=False),
        sa.Column("extract_type_id", sa.Integer(), nullable=False),
        sa.Column("extract_date", sa.Date(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("s3_path", sa.Text(), nullable=False),
        sa.Column("processing_status_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["extract_type_id"],
            ["api.lk_sam_gov_extract_type.sam_gov_extract_type_id"],
            name=op.f("sam_extract_file_extract_type_id_lk_sam_gov_extract_type_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["processing_status_id"],
            ["api.lk_sam_gov_processing_status.sam_gov_processing_status_id"],
            name=op.f("sam_extract_file_processing_status_id_lk_sam_gov_processing_status_fkey"),
        ),
        sa.PrimaryKeyConstraint("sam_extract_file_id", name=op.f("sam_extract_file_pkey")),
        schema="api",
    )
    op.create_index(
        op.f("sam_extract_file_extract_type_id_idx"),
        "sam_extract_file",
        ["extract_type_id"],
        unique=False,
        schema="api",
    )
    op.create_index(
        op.f("sam_extract_file_processing_status_id_idx"),
        "sam_extract_file",
        ["processing_status_id"],
        unique=False,
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("sam_extract_file_processing_status_id_idx"),
        table_name="sam_extract_file",
        schema="api",
    )
    op.drop_index(
        op.f("sam_extract_file_extract_type_id_idx"), table_name="sam_extract_file", schema="api"
    )
    op.drop_table("sam_extract_file", schema="api")
    op.drop_table("lk_sam_gov_processing_status", schema="api")
    op.drop_table("lk_sam_gov_extract_type", schema="api")
    # ### end Alembic commands ###
