"""Assign organization admin role to existing owners

Revision ID: 430b57cd6d23
Revises: 61578095938e
Create Date: 2025-09-16 15:56:53.326303

"""

from alembic import op

from src.constants.static_role_values import ORG_ADMIN_ID

# revision identifiers, used by Alembic.
revision = "430b57cd6d23"
down_revision = "61578095938e"
branch_labels = None
depends_on = None

org_admin_role_id = str(ORG_ADMIN_ID)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Insert Organization Admin role assignments for all existing organization owners
    # who don't already have the role
    op.execute(
        f"""
        INSERT INTO api.organization_user_role (organization_user_id, role_id, created_at, updated_at)
        SELECT
            ou.organization_user_id,
            '{org_admin_role_id}'::uuid,
            NOW(),
            NOW()
        FROM api.organization_user ou
        WHERE ou.is_organization_owner = true
        AND NOT EXISTS (
            SELECT 1
            FROM api.organization_user_role our
            WHERE our.organization_user_id = ou.organization_user_id
            AND our.role_id = '{org_admin_role_id}'::uuid
        );
    """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove Organization Admin role assignments that were added by this migration
    op.execute(
        f"""
        DELETE FROM api.organization_user_role
        WHERE role_id = '{org_admin_role_id}'::uuid
        AND organization_user_id IN (
            SELECT organization_user_id
            FROM api.organization_user
            WHERE is_organization_owner = true
        );
    """
    )

    # ### end Alembic commands ###
