"""rm_is_organization_owner

Revision ID: 5f688dda8d5f
Revises: 75c42327a370
Create Date: 2025-11-04 17:56:48.783246

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5f688dda8d5f"
down_revision = "75c42327a370"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_user", "is_organization_owner", schema="api")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_user",
        sa.Column("is_organization_owner", sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema="api",
    )
    # ### end Alembic commands ###
