"""add_legacy_certificate

Revision ID: 75c42327a370
Revises: 43622a46494e
Create Date: 2025-10-31 21:12:36.885680

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "75c42327a370"
down_revision = "43622a46494e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legacy_certificate",
        sa.Column("legacy_certificate_id", sa.UUID(), nullable=False),
        sa.Column("cert_id", sa.Text(), nullable=False),
        sa.Column("serial_number", sa.Text(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("agency_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["api.agency.agency_id"],
            name=op.f("legacy_certificate_agency_id_agency_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["api.organization.organization_id"],
            name=op.f("legacy_certificate_organization_id_organization_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["api.user.user_id"], name=op.f("legacy_certificate_user_id_user_fkey")
        ),
        sa.PrimaryKeyConstraint("legacy_certificate_id", name=op.f("legacy_certificate_pkey")),
        schema="api",
    )
    op.create_index(
        op.f("legacy_certificate_cert_id_idx"),
        "legacy_certificate",
        ["cert_id"],
        unique=False,
        schema="api",
    )
    op.create_index(
        op.f("legacy_certificate_expiration_date_idx"),
        "legacy_certificate",
        ["expiration_date"],
        unique=False,
        schema="api",
    )
    op.create_index(
        op.f("legacy_certificate_serial_number_idx"),
        "legacy_certificate",
        ["serial_number"],
        unique=False,
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("legacy_certificate_serial_number_idx"), table_name="legacy_certificate", schema="api"
    )
    op.drop_index(
        op.f("legacy_certificate_expiration_date_idx"),
        table_name="legacy_certificate",
        schema="api",
    )
    op.drop_index(
        op.f("legacy_certificate_cert_id_idx"), table_name="legacy_certificate", schema="api"
    )
    op.drop_table("legacy_certificate", schema="api")
    # ### end Alembic commands ###
