"""Remove Competition Assistance Listing table

Revision ID: 615ae75c82bf
Revises: 19e80334aaae
Create Date: 2025-11-23 21:18:43.982811

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "615ae75c82bf"
down_revision = "19e80334aaae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("competition_assistance_listing", schema="api")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competition_assistance_listing",
        sa.Column("competition_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "opportunity_assistance_listing_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["api.competition.competition_id"],
            name=op.f("competition_assistance_listing_competition_id_competition_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_assistance_listing_id"],
            ["api.opportunity_assistance_listing.opportunity_assistance_listing_id"],
            name=op.f("competition_assistance_listing_opportunity_assistance_l_6b02"),
        ),
        sa.PrimaryKeyConstraint(
            "competition_id",
            "opportunity_assistance_listing_id",
            name=op.f("competition_assistance_listing_pkey"),
        ),
        schema="api",
    )
    # ### end Alembic commands ###
