"""Remove Extract Metadata Table

Revision ID: 3fcfd97a668c
Revises: fb95857d5375
Create Date: 2025-03-31 22:51:43.931094

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3fcfd97a668c"
down_revision = "fb95857d5375"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("extract_metadata", schema="api")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extract_metadata",
        sa.Column("extract_metadata_id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("extract_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("file_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_path", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_size_bytes", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["extract_type_id"],
            ["api.lk_extract_type.extract_type_id"],
            name="extract_metadata_extract_type_id_lk_extract_type_fkey",
        ),
        sa.PrimaryKeyConstraint("extract_metadata_id", name="extract_metadata_pkey"),
        schema="api",
    )
    # ### end Alembic commands ###
