"""create workflow management tables

Revision ID: 01ceae9892c9
Revises: 1c069c3a6ccc
Create Date: 2026-02-07 17:32:31.424776

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "01ceae9892c9"
down_revision = "1c069c3a6ccc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("workflow_type_id", sa.Integer(), nullable=False),
        sa.Column("current_workflow_state", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workflow_type_id"],
            ["api.lk_workflow_type.workflow_type_id"],
            name=op.f("workflow_workflow_type_id_lk_workflow_type_fkey"),
        ),
        sa.PrimaryKeyConstraint("workflow_id", name=op.f("workflow_pkey")),
        schema="api",
    )
    op.create_table(
        "workflow_event_history",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=True),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sent_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_successfully_processed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["api.workflow.workflow_id"],
            name=op.f("workflow_event_history_workflow_id_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("workflow_event_history_pkey")),
        schema="api",
    )
    op.create_table(
        "workflow_approval",
        sa.Column("workflow_approval_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("approving_user_id", sa.UUID(), nullable=False),
        sa.Column("approval_type_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("is_still_valid", sa.Boolean(), nullable=False),
        sa.Column("approval_response_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approval_response_type_id"],
            ["api.lk_approval_response_type.approval_response_type_id"],
            name=op.f("workflow_approval_approval_response_type_id_lk_approval_response_type_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["approval_type_id"],
            ["api.lk_approval_type.approval_type_id"],
            name=op.f("workflow_approval_approval_type_id_lk_approval_type_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["approving_user_id"],
            ["api.user.user_id"],
            name=op.f("workflow_approval_approving_user_id_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["api.workflow_event_history.event_id"],
            name=op.f("workflow_approval_event_id_workflow_event_history_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["api.workflow.workflow_id"],
            name=op.f("workflow_approval_workflow_id_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint("workflow_approval_id", name=op.f("workflow_approval_pkey")),
        schema="api",
    )
    op.create_table(
        "workflow_audit",
        sa.Column("workflow_audit_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("acting_user_id", sa.UUID(), nullable=False),
        sa.Column("transition_event", sa.Text(), nullable=False),
        sa.Column("source_state", sa.Text(), nullable=False),
        sa.Column("target_state", sa.Text(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("audit_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["acting_user_id"],
            ["api.user.user_id"],
            name=op.f("workflow_audit_acting_user_id_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["api.workflow_event_history.event_id"],
            name=op.f("workflow_audit_event_id_workflow_event_history_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["api.workflow.workflow_id"],
            name=op.f("workflow_audit_workflow_id_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint("workflow_audit_id", name=op.f("workflow_audit_pkey")),
        schema="api",
    )
    op.create_table(
        "workflow_opportunity",
        sa.Column("workflow_opportunity_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["api.opportunity.opportunity_id"],
            name=op.f("workflow_opportunity_opportunity_id_opportunity_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["api.workflow.workflow_id"],
            name=op.f("workflow_opportunity_workflow_id_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint("workflow_opportunity_id", name=op.f("workflow_opportunity_pkey")),
        schema="api",
    )
    op.create_table(
        "workflow_application",
        sa.Column("workflow_application_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["api.application.application_id"],
            name=op.f("workflow_application_application_id_application_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["api.workflow.workflow_id"],
            name=op.f("workflow_application_workflow_id_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint("workflow_application_id", name=op.f("workflow_application_pkey")),
        schema="api",
    )
    op.create_table(
        "workflow_application_submission",
        sa.Column("workflow_application_submission_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("application_submission_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_submission_id"],
            ["api.application_submission.application_submission_id"],
            name=op.f(
                "workflow_application_submission_application_submission_id_application_submission_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["api.workflow.workflow_id"],
            name=op.f("workflow_application_submission_workflow_id_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "workflow_application_submission_id", name=op.f("workflow_application_submission_pkey")
        ),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workflow_application_submission", schema="api")
    op.drop_table("workflow_application", schema="api")
    op.drop_table("workflow_opportunity", schema="api")
    op.drop_table("workflow_audit", schema="api")
    op.drop_table("workflow_approval", schema="api")
    op.drop_table("workflow_event_history", schema="api")
    op.drop_table("workflow", schema="api")
    # ### end Alembic commands ###
