"""add award recommendation to workflow

Revision ID: fc314a942f96
Revises: f87a711a47cb
Create Date: 2026-04-22 01:46:37.713170

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc314a942f96"
down_revision = "f87a711a47cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow", sa.Column("award_recommendation_id", sa.UUID(), nullable=True), schema="api"
    )
    op.create_foreign_key(
        op.f("workflow_award_recommendation_id_award_recommendation_fkey"),
        "workflow",
        "award_recommendation",
        ["award_recommendation_id"],
        ["award_recommendation_id"],
        source_schema="api",
        referent_schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("workflow_award_recommendation_id_award_recommendation_fkey"),
        "workflow",
        schema="api",
        type_="foreignkey",
    )
    op.drop_column("workflow", "award_recommendation_id", schema="api")
    # ### end Alembic commands ###
