"""Add change type to version table

Revision ID: d4c3021f522a
Revises: 5fab75294ea6
Create Date: 2026-06-12 15:12:23.141174

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d4c3021f522a"
down_revision = "5fab75294ea6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "opportunity_version", sa.Column("change_type", sa.Text(), nullable=False), schema="api"
    )
    op.create_index(
        op.f("opportunity_version_change_type_idx"),
        "opportunity_version",
        ["change_type"],
        unique=False,
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("opportunity_version_change_type_idx"), table_name="opportunity_version", schema="api"
    )
    op.drop_column("opportunity_version", "change_type", schema="api")
    # ### end Alembic commands ###
