"""add submission columns

Revision ID: 3bbb6f5e037e
Revises: dc49bb9e25ab
Create Date: 2026-03-11 14:56:37.489043

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3bbb6f5e037e"
down_revision = "dc49bb9e25ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application_submission",
        sa.Column("application_submission_number", sa.Text(), nullable=True),
        schema="api",
    )
    op.add_column(
        "application_submission", sa.Column("project_title", sa.Text(), nullable=True), schema="api"
    )
    op.add_column(
        "application_submission",
        sa.Column("total_requested_amount", sa.Numeric(), nullable=True),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application_submission", "total_requested_amount", schema="api")
    op.drop_column("application_submission", "project_title", schema="api")
    op.drop_column("application_submission", "application_submission_number", schema="api")
    # ### end Alembic commands ###
