"""created supplemental award recommendation tables

Revision ID: f07517d3bf39
Revises: 04fddd68f52e
Create Date: 2026-04-01 19:11:52.776109

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f07517d3bf39"
down_revision = "04fddd68f52e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "award_recommendation_attachment",
        sa.Column("award_recommendation_attachment_id", sa.UUID(), nullable=False),
        sa.Column("award_recommendation_id", sa.UUID(), nullable=False),
        sa.Column("file_location", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("award_recommendation_attachment_type_id", sa.Integer(), nullable=False),
        sa.Column("uploading_user_id", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_attachment_type_id"],
            ["api.lk_award_recommendation_attachment_type.award_recommendation_attachment_type_id"],
            name=op.f(
                "award_recommendation_attachment_award_recommendation_attachment_type_id_lk_award_recommendation_attachment_type_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_id"],
            ["api.award_recommendation.award_recommendation_id"],
            name=op.f(
                "award_recommendation_attachment_award_recommendation_id_award_recommendation_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["uploading_user_id"],
            ["api.user.user_id"],
            name=op.f("award_recommendation_attachment_uploading_user_id_user_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "award_recommendation_attachment_id", name=op.f("award_recommendation_attachment_pkey")
        ),
        schema="api",
    )
    op.create_index(
        op.f("award_recommendation_attachment_award_recommendation_id_idx"),
        "award_recommendation_attachment",
        ["award_recommendation_id"],
        unique=False,
        schema="api",
    )
    op.create_table(
        "award_recommendation_review",
        sa.Column("award_recommendation_review_id", sa.UUID(), nullable=False),
        sa.Column("award_recommendation_id", sa.UUID(), nullable=False),
        sa.Column("award_recommendation_review_type_id", sa.Integer(), nullable=False),
        sa.Column("is_reviewed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_id"],
            ["api.award_recommendation.award_recommendation_id"],
            name=op.f(
                "award_recommendation_review_award_recommendation_id_award_recommendation_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_review_type_id"],
            ["api.lk_award_recommendation_review_type.award_recommendation_review_type_id"],
            name=op.f(
                "award_recommendation_review_award_recommendation_review_type_id_lk_award_recommendation_review_type_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "award_recommendation_review_id", name=op.f("award_recommendation_review_pkey")
        ),
        schema="api",
    )
    op.create_index(
        op.f("award_recommendation_review_award_recommendation_id_idx"),
        "award_recommendation_review",
        ["award_recommendation_id"],
        unique=False,
        schema="api",
    )
    op.create_table(
        "award_recommendation_risk",
        sa.Column("award_recommendation_risk_id", sa.UUID(), nullable=False),
        sa.Column("award_recommendation_id", sa.UUID(), nullable=False),
        sa.Column("award_recommendation_risk_number", sa.Text(), nullable=False),
        sa.Column("award_recommendation_risk_type_id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_id"],
            ["api.award_recommendation.award_recommendation_id"],
            name=op.f(
                "award_recommendation_risk_award_recommendation_id_award_recommendation_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_risk_type_id"],
            ["api.lk_award_recommendation_risk_type.award_recommendation_risk_type_id"],
            name=op.f(
                "award_recommendation_risk_award_recommendation_risk_type_id_lk_award_recommendation_risk_type_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "award_recommendation_risk_id", name=op.f("award_recommendation_risk_pkey")
        ),
        schema="api",
    )
    op.create_index(
        op.f("award_recommendation_risk_award_recommendation_id_idx"),
        "award_recommendation_risk",
        ["award_recommendation_id"],
        unique=False,
        schema="api",
    )
    op.create_index(
        op.f("award_recommendation_risk_award_recommendation_risk_number_idx"),
        "award_recommendation_risk",
        ["award_recommendation_risk_number"],
        unique=False,
        schema="api",
    )
    op.create_table(
        "award_recommendation_audit_event",
        sa.Column("award_recommendation_audit_id", sa.UUID(), nullable=False),
        sa.Column("award_recommendation_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("award_recommendation_audit_event_id", sa.Integer(), nullable=False),
        sa.Column("award_recommendation_risk_id", sa.UUID(), nullable=True),
        sa.Column("award_recommendation_attachment_id", sa.UUID(), nullable=True),
        sa.Column("award_recommendation_review_id", sa.UUID(), nullable=True),
        sa.Column("award_recommendation_application_submission_id", sa.UUID(), nullable=True),
        sa.Column("workflow_approval_id", sa.UUID(), nullable=True),
        sa.Column("audit_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_application_submission_id"],
            [
                "api.award_recommendation_application_submission.award_recommendation_application_submission_id"
            ],
            name=op.f(
                "award_recommendation_audit_event_award_recommendation_application_submission_id_award_recommendation_application_submission_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_attachment_id"],
            ["api.award_recommendation_attachment.award_recommendation_attachment_id"],
            name=op.f(
                "award_recommendation_audit_event_award_recommendation_attachment_id_award_recommendation_attachment_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_audit_event_id"],
            ["api.lk_award_recommendation_audit_event.award_recommendation_audit_event_id"],
            name=op.f(
                "award_recommendation_audit_event_award_recommendation_audit_event_id_lk_award_recommendation_audit_event_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_id"],
            ["api.award_recommendation.award_recommendation_id"],
            name=op.f(
                "award_recommendation_audit_event_award_recommendation_id_award_recommendation_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_review_id"],
            ["api.award_recommendation_review.award_recommendation_review_id"],
            name=op.f(
                "award_recommendation_audit_event_award_recommendation_review_id_award_recommendation_review_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_risk_id"],
            ["api.award_recommendation_risk.award_recommendation_risk_id"],
            name=op.f(
                "award_recommendation_audit_event_award_recommendation_risk_id_award_recommendation_risk_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["api.user.user_id"],
            name=op.f("award_recommendation_audit_event_user_id_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_approval_id"],
            ["api.workflow_approval.workflow_approval_id"],
            name=op.f(
                "award_recommendation_audit_event_workflow_approval_id_workflow_approval_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "award_recommendation_audit_id", name=op.f("award_recommendation_audit_event_pkey")
        ),
        schema="api",
    )
    op.create_index(
        op.f("award_recommendation_audit_event_award_recommendation_id_idx"),
        "award_recommendation_audit_event",
        ["award_recommendation_id"],
        unique=False,
        schema="api",
    )
    op.create_table(
        "award_recommendation_risk_submission",
        sa.Column("award_recommendation_risk_id", sa.UUID(), nullable=False),
        sa.Column("award_recommendation_application_submission_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_application_submission_id"],
            [
                "api.award_recommendation_application_submission.award_recommendation_application_submission_id"
            ],
            name=op.f(
                "award_recommendation_risk_submission_award_recommendation_application_submission_id_award_recommendation_application_submission_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_risk_id"],
            ["api.award_recommendation_risk.award_recommendation_risk_id"],
            name=op.f(
                "award_recommendation_risk_submission_award_recommendation_risk_id_award_recommendation_risk_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "award_recommendation_risk_id",
            "award_recommendation_application_submission_id",
            name=op.f("award_recommendation_risk_submission_pkey"),
        ),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("award_recommendation_risk_submission", schema="api")
    op.drop_index(
        op.f("award_recommendation_audit_event_award_recommendation_id_idx"),
        table_name="award_recommendation_audit_event",
        schema="api",
    )
    op.drop_table("award_recommendation_audit_event", schema="api")
    op.drop_index(
        op.f("award_recommendation_risk_award_recommendation_risk_number_idx"),
        table_name="award_recommendation_risk",
        schema="api",
    )
    op.drop_index(
        op.f("award_recommendation_risk_award_recommendation_id_idx"),
        table_name="award_recommendation_risk",
        schema="api",
    )
    op.drop_table("award_recommendation_risk", schema="api")
    op.drop_index(
        op.f("award_recommendation_review_award_recommendation_id_idx"),
        table_name="award_recommendation_review",
        schema="api",
    )
    op.drop_table("award_recommendation_review", schema="api")
    op.drop_index(
        op.f("award_recommendation_attachment_award_recommendation_id_idx"),
        table_name="award_recommendation_attachment",
        schema="api",
    )
    op.drop_table("award_recommendation_attachment", schema="api")
    # ### end Alembic commands ###
