"""drop excluded opportunity review table

Revision ID: 440d762b84dc
Revises: de02084c3fdd
Create Date: 2026-01-16 17:23:44.540205

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "440d762b84dc"
down_revision = "de02084c3fdd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("excluded_opportunity_review", schema="api")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "excluded_opportunity_review",
        sa.Column("legacy_opportunity_id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("omb_review_status_display", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "omb_review_status_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_update_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "legacy_opportunity_id", name=op.f("excluded_opportunity_review_pkey")
        ),
        schema="api",
    )
    # ### end Alembic commands ###
