"""remove unused agency fields from opportunity summary

Revision ID: 649b1aa24f78
Revises: de02084c3fdd
Create Date: 2026-01-15 16:40:40.139812

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "649b1aa24f78"
down_revision = "de02084c3fdd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("opportunity_summary", "agency_code", schema="api")
    op.drop_column("opportunity_summary", "agency_name", schema="api")
    op.drop_column("opportunity_summary", "agency_phone_number", schema="api")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "opportunity_summary",
        sa.Column("agency_phone_number", sa.TEXT(), autoincrement=False, nullable=True),
        schema="api",
    )
    op.add_column(
        "opportunity_summary",
        sa.Column("agency_name", sa.TEXT(), autoincrement=False, nullable=True),
        schema="api",
    )
    op.add_column(
        "opportunity_summary",
        sa.Column("agency_code", sa.TEXT(), autoincrement=False, nullable=True),
        schema="api",
    )
    # ### end Alembic commands ###
