"""add_referenced_opportunity_table

Revision ID: c35a270795d3
Revises: 649b1aa24f78
Create Date: 2026-01-28 16:46:54.136719

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c35a270795d3"
down_revision = "649b1aa24f78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "opportunity",
        sa.Column("is_simpler_grants_opportunity", sa.Boolean(), nullable=False),
        schema="api",
    )
    op.alter_column(
        "opportunity",
        "legacy_opportunity_id",
        existing_type=sa.BIGINT(),
        nullable=True,
        schema="api",
    )
    op.create_index(
        op.f("opportunity_is_simpler_grants_opportunity_idx"),
        "opportunity",
        ["is_simpler_grants_opportunity"],
        unique=False,
        schema="api",
    )
    
    # Add referenced_opportunity table
    op.create_table(
        'referenced_opportunity',
        sa.Column('referenced_opportunity_id', postgresql.UUID(), nullable=False),
        sa.Column('original_opportunity_id', postgresql.UUID(), nullable=False),
        sa.Column('derived_opportunity_id', postgresql.UUID(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=text('NOW()'), nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['derived_opportunity_id'], ['api.opportunity.opportunity_id'], ),
        sa.ForeignKeyConstraint(['original_opportunity_id'], ['api.opportunity.opportunity_id'], ),
        sa.PrimaryKeyConstraint('referenced_opportunity_id'),
        sa.UniqueConstraint('derived_opportunity_id'),
        schema='api'
    )
    op.create_index(op.f('ix_api_referenced_opportunity_derived_opportunity_id'), 'referenced_opportunity', ['derived_opportunity_id'], unique=False, schema='api')
    op.create_index(op.f('ix_api_referenced_opportunity_original_opportunity_id'), 'referenced_opportunity', ['original_opportunity_id'], unique=False, schema='api')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop referenced_opportunity table
    op.drop_index(op.f('ix_api_referenced_opportunity_original_opportunity_id'), table_name='referenced_opportunity', schema='api')
    op.drop_index(op.f('ix_api_referenced_opportunity_derived_opportunity_id'), table_name='referenced_opportunity', schema='api')
    op.drop_table('referenced_opportunity', schema='api')
    
    # Revert opportunity table changes
    op.drop_index(
        op.f("opportunity_is_simpler_grants_opportunity_idx"),
        table_name="opportunity",
        schema="api",
    )
    op.alter_column(
        "opportunity",
        "legacy_opportunity_id",
        existing_type=sa.BIGINT(),
        nullable=False,
        schema="api",
    )
    op.drop_column("opportunity", "is_simpler_grants_opportunity", schema="api")
    # ### end Alembic commands ###
