"""Create Assistance Listing table

Revision ID: da0124034eb9
Revises: a1afe497ff6f
Create Date: 2026-02-06 18:27:39.772042

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "da0124034eb9"
down_revision = "a1afe497ff6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistance_listing",
        sa.Column("assistance_listing_record_id", sa.UUID(), nullable=False),
        sa.Column("assistance_listing_number", sa.Text(), nullable=False),
        sa.Column("program_title", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "assistance_listing_record_id", name=op.f("assistance_listing_pkey")
        ),
        schema="api",
    )
    op.alter_column(
        "opportunity_assistance_listing",
        "legacy_opportunity_assistance_listing_id",
        existing_type=sa.BIGINT(),
        nullable=True,
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "opportunity_assistance_listing",
        "legacy_opportunity_assistance_listing_id",
        existing_type=sa.BIGINT(),
        nullable=False,
        schema="api",
    )
    op.drop_table("assistance_listing", schema="api")
    # ### end Alembic commands ###
