"""drop unused staging hist tables

Revision ID: 0b3e125c6bac
Revises: 4a9d04a66c98
Create Date: 2026-07-28 05:10:05.848480

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0b3e125c6bac"
down_revision = "4a9d04a66c98"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("tfundinstr_synopsis_hist_transformed_at_idx"),
        table_name="tfundinstr_synopsis_hist",
        schema="staging",
    )
    op.drop_table("tfundinstr_synopsis_hist", schema="staging")
    op.drop_index(
        op.f("tfundactcat_forecast_hist_transformed_at_idx"),
        table_name="tfundactcat_forecast_hist",
        schema="staging",
    )
    op.drop_table("tfundactcat_forecast_hist", schema="staging")
    op.drop_index(
        op.f("tforecast_hist_transformed_at_idx"), table_name="tforecast_hist", schema="staging"
    )
    op.drop_table("tforecast_hist", schema="staging")
    op.drop_index(
        op.f("tapplicanttypes_forecast_hist_transformed_at_idx"),
        table_name="tapplicanttypes_forecast_hist",
        schema="staging",
    )
    op.drop_table("tapplicanttypes_forecast_hist", schema="staging")
    op.drop_index(
        op.f("tfundinstr_forecast_hist_transformed_at_idx"),
        table_name="tfundinstr_forecast_hist",
        schema="staging",
    )
    op.drop_table("tfundinstr_forecast_hist", schema="staging")
    op.drop_index(
        op.f("tapplicanttypes_synopsis_hist_transformed_at_idx"),
        table_name="tapplicanttypes_synopsis_hist",
        schema="staging",
    )
    op.drop_table("tapplicanttypes_synopsis_hist", schema="staging")
    op.drop_index(
        op.f("tsynopsis_hist_transformed_at_idx"), table_name="tsynopsis_hist", schema="staging"
    )
    op.drop_table("tsynopsis_hist", schema="staging")
    op.drop_index(
        op.f("tfundactcat_synopsis_hist_transformed_at_idx"),
        table_name="tfundactcat_synopsis_hist",
        schema="staging",
    )
    op.drop_table("tfundactcat_synopsis_hist", schema="staging")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tfundactcat_synopsis_hist",
        sa.Column("fac_syn_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("fac_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "transformed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("transformation_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "fac_syn_id",
            "fac_id",
            "opportunity_id",
            "revision_number",
            name=op.f("tfundactcat_synopsis_hist_pkey"),
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tfundactcat_synopsis_hist_transformed_at_idx"),
        "tfundactcat_synopsis_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tsynopsis_hist",
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "posting_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "response_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "archive_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "unarchive_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("syn_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("oth_cat_fa_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_addr_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("cost_sharing", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("number_of_awards", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("est_funding", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("award_ceiling", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("award_floor", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fd_link_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fd_link_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_contact_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_email_addr", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_email_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_phone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("a_sa_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_phone_number", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "create_ts", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("sendmail", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("response_date_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("applicant_elig_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("action_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "action_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("version_nbr", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("modification_comments", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisheruid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisher_profile_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "transformed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("transformation_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "opportunity_id", "revision_number", name=op.f("tsynopsis_hist_pkey")
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tsynopsis_hist_transformed_at_idx"),
        "tsynopsis_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tapplicanttypes_synopsis_hist",
        sa.Column("at_syn_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("at_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "transformed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("transformation_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "at_syn_id",
            "at_id",
            "opportunity_id",
            "revision_number",
            name=op.f("tapplicanttypes_synopsis_hist_pkey"),
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tapplicanttypes_synopsis_hist_transformed_at_idx"),
        "tapplicanttypes_synopsis_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tfundinstr_forecast_hist",
        sa.Column("fi_frcst_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("fi_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "transformed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("transformation_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "fi_frcst_id",
            "fi_id",
            "opportunity_id",
            "revision_number",
            name=op.f("tfundinstr_forecast_hist_pkey"),
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tfundinstr_forecast_hist_transformed_at_idx"),
        "tfundinstr_forecast_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tapplicanttypes_forecast_hist",
        sa.Column("at_frcst_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("at_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "transformed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("transformation_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "at_frcst_id",
            "at_id",
            "opportunity_id",
            "revision_number",
            name=op.f("tapplicanttypes_forecast_hist_pkey"),
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tapplicanttypes_forecast_hist_transformed_at_idx"),
        "tapplicanttypes_forecast_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tforecast_hist",
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("version_nbr", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "posting_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "archive_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("forecast_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("oth_cat_fa_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("cost_sharing", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("number_of_awards", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("est_funding", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("award_ceiling", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("award_floor", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fd_link_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fd_link_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_phone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_email_addr", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ac_email_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("agency_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("sendmail", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("applicant_elig_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "est_synopsis_posting_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "est_appl_response_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("est_appl_response_date_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "est_award_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "est_project_start_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("fiscal_year", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("modification_comments", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("action_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "action_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "create_ts", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisheruid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publisher_profile_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "transformed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("transformation_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "opportunity_id", "revision_number", name=op.f("tforecast_hist_pkey")
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tforecast_hist_transformed_at_idx"),
        "tforecast_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tfundactcat_forecast_hist",
        sa.Column("fac_frcst_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("fac_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "transformed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("transformation_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "fac_frcst_id",
            "fac_id",
            "opportunity_id",
            "revision_number",
            name=op.f("tfundactcat_forecast_hist_pkey"),
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tfundactcat_forecast_hist_transformed_at_idx"),
        "tfundactcat_forecast_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "tfundinstr_synopsis_hist",
        sa.Column("fi_syn_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("opportunity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("fi_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_upd_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_upd_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "transformed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("transformation_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "fi_syn_id",
            "opportunity_id",
            "fi_id",
            "revision_number",
            name=op.f("tfundinstr_synopsis_hist_pkey"),
        ),
        schema="staging",
    )
    op.create_index(
        op.f("tfundinstr_synopsis_hist_transformed_at_idx"),
        "tfundinstr_synopsis_hist",
        ["transformed_at"],
        unique=False,
        schema="staging",
    )
    # ### end Alembic commands ###
