"""add key_id_hash to user_api_key

Revision ID: 33fa7d0cffbe
Revises: c3792748f4e5
Create Date: 2026-09-30 16:33:43.396764

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "33fa7d0cffbe"
down_revision = "c3792748f4e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_api_key",
        sa.Column(
            "key_id_hash",
            sa.Text(),
            nullable=True,
            comment="HMAC-SHA256 hash of key_id, keyed with the API key pepper",
        ),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_api_key", "key_id_hash", schema="api")
    # ### end Alembic commands ###
