"""create application_submission_retrieved table

Revision ID: a2a8f9f15489
Revises: dc49bb9e25ab
Create Date: 2026-03-11 19:09:13.949910

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a2a8f9f15489"
down_revision = "dc49bb9e25ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_submission_retrieved",
        sa.Column("application_submission_retrieved_id", sa.UUID(), nullable=False),
        sa.Column("application_submission_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("modified_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_submission_id"],
            ["api.application_submission.application_submission_id"],
            name=op.f(
                "application_submission_retrieved_application_submission_id_application_submission_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["api.user.user_id"],
            name=op.f("application_submission_retrieved_created_by_user_id_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_user_id"],
            ["api.user.user_id"],
            name=op.f("application_submission_retrieved_modified_by_user_id_user_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "application_submission_retrieved_id",
            name=op.f("application_submission_retrieved_pkey"),
        ),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("application_submission_retrieved", schema="api")
    # ### end Alembic commands ###
