"""create application_submission_retrieved table

Revision ID: e401db65ab7a
Revises: dc49bb9e25ab
Create Date: 2026-03-11 18:53:08.962268

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e401db65ab7a"
down_revision = "dc49bb9e25ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "award_recommendation_submission_detail",
        sa.Column("award_recommendation_submission_detail_id", sa.UUID(), nullable=False),
        sa.Column("recommended_amount", sa.Numeric(), nullable=True),
        sa.Column("scoring_comment", sa.Text(), nullable=True),
        sa.Column("general_comment", sa.Text(), nullable=True),
        sa.Column("award_recommendation_type_id", sa.Integer(), nullable=True),
        sa.Column("has_exception", sa.Boolean(), nullable=False),
        sa.Column("exception_detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_type_id"],
            ["api.lk_award_recommendation_type.award_recommendation_type_id"],
            name=op.f(
                "award_recommendation_submission_detail_award_recommendation_type_id_lk_award_recommendation_type_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "award_recommendation_submission_detail_id",
            name=op.f("award_recommendation_submission_detail_pkey"),
        ),
        schema="api",
    )
    op.create_table(
        "application_submission_retrieved",
        sa.Column("application_submission_retrieved_id", sa.UUID(), nullable=False),
        sa.Column("application_submission_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("modified_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_submission_id"],
            ["api.application_submission.application_submission_id"],
            name=op.f(
                "application_submission_retrieved_application_submission_id_application_submission_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["api.user.user_id"],
            name=op.f("application_submission_retrieved_created_by_user_id_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_user_id"],
            ["api.user.user_id"],
            name=op.f("application_submission_retrieved_modified_by_user_id_user_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "application_submission_retrieved_id",
            name=op.f("application_submission_retrieved_pkey"),
        ),
        schema="api",
    )
    op.create_table(
        "award_recommendation",
        sa.Column("award_recommendation_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("award_recommendation_number", sa.Text(), nullable=False),
        sa.Column("award_recommendation_status_id", sa.Integer(), nullable=False),
        sa.Column("additional_info", sa.Text(), nullable=True),
        sa.Column("award_selection_method_id", sa.Integer(), nullable=True),
        sa.Column("other_key_information", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("review_workflow_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_status_id"],
            ["api.lk_award_recommendation_status.award_recommendation_status_id"],
            name=op.f(
                "award_recommendation_award_recommendation_status_id_lk_award_recommendation_status_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["award_selection_method_id"],
            ["api.lk_award_selection_method.award_selection_method_id"],
            name=op.f(
                "award_recommendation_award_selection_method_id_lk_award_selection_method_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["api.opportunity.opportunity_id"],
            name=op.f("award_recommendation_opportunity_id_opportunity_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["review_workflow_id"],
            ["api.workflow.workflow_id"],
            name=op.f("award_recommendation_review_workflow_id_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint("award_recommendation_id", name=op.f("award_recommendation_pkey")),
        schema="api",
    )
    op.create_index(
        op.f("award_recommendation_award_recommendation_number_idx"),
        "award_recommendation",
        ["award_recommendation_number"],
        unique=False,
        schema="api",
    )
    op.create_index(
        op.f("award_recommendation_opportunity_id_idx"),
        "award_recommendation",
        ["opportunity_id"],
        unique=False,
        schema="api",
    )
    op.create_table(
        "award_recommendation_application_submission",
        sa.Column("award_recommendation_application_submission_id", sa.UUID(), nullable=False),
        sa.Column("award_recommendation_id", sa.UUID(), nullable=False),
        sa.Column("application_submission_id", sa.UUID(), nullable=False),
        sa.Column("award_recommendation_submission_detail_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_submission_id"],
            ["api.application_submission.application_submission_id"],
            name=op.f(
                "award_recommendation_application_submission_application_submission_id_application_submission_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_id"],
            ["api.award_recommendation.award_recommendation_id"],
            name=op.f(
                "award_recommendation_application_submission_award_recommendation_id_award_recommendation_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["award_recommendation_submission_detail_id"],
            [
                "api.award_recommendation_submission_detail.award_recommendation_submission_detail_id"
            ],
            name=op.f(
                "award_recommendation_application_submission_award_recommendation_submission_detail_id_award_recommendation_submission_detail_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "award_recommendation_application_submission_id",
            name=op.f("award_recommendation_application_submission_pkey"),
        ),
        schema="api",
    )
    op.create_index(
        op.f("award_recommendation_application_submission_award_recommendation_id_idx"),
        "award_recommendation_application_submission",
        ["award_recommendation_id"],
        unique=False,
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("award_recommendation_application_submission_award_recommendation_id_idx"),
        table_name="award_recommendation_application_submission",
        schema="api",
    )
    op.drop_table("award_recommendation_application_submission", schema="api")
    op.drop_index(
        op.f("award_recommendation_opportunity_id_idx"),
        table_name="award_recommendation",
        schema="api",
    )
    op.drop_index(
        op.f("award_recommendation_award_recommendation_number_idx"),
        table_name="award_recommendation",
        schema="api",
    )
    op.drop_table("award_recommendation", schema="api")
    op.drop_table("application_submission_retrieved", schema="api")
    op.drop_table("award_recommendation_submission_detail", schema="api")
    # ### end Alembic commands ###
