"""Create & Link Assistance Listing table

Revision ID: 290f5c9d7e0c
Revises: 1c069c3a6ccc
Create Date: 2026-02-09 17:12:32.872937

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "290f5c9d7e0c"
down_revision = "1c069c3a6ccc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistance_listing",
        sa.Column("assistance_listing_record_id", sa.UUID(), nullable=False),
        sa.Column("assistance_listing_number", sa.Text(), nullable=False),
        sa.Column("program_title", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "assistance_listing_record_id", name=op.f("assistance_listing_pkey")
        ),
        schema="api",
    )
    op.create_index(
        op.f("assistance_listing_assistance_listing_number_idx"),
        "assistance_listing",
        ["assistance_listing_number"],
        unique=False,
        schema="api",
    )
    op.add_column(
        "opportunity_assistance_listing",
        sa.Column("assistance_listing_record_id", sa.UUID(), nullable=True),
        schema="api",
    )
    op.alter_column(
        "opportunity_assistance_listing",
        "legacy_opportunity_assistance_listing_id",
        existing_type=sa.BIGINT(),
        nullable=True,
        schema="api",
    )
    op.create_index(
        op.f("opportunity_assistance_listing_assistance_listing_record_id_idx"),
        "opportunity_assistance_listing",
        ["assistance_listing_record_id"],
        unique=False,
        schema="api",
    )
    op.create_foreign_key(
        op.f("opportunity_assistance_listing_assistance_listing_record_id_assistance_listing_fkey"),
        "opportunity_assistance_listing",
        "assistance_listing",
        ["assistance_listing_record_id"],
        ["assistance_listing_record_id"],
        source_schema="api",
        referent_schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("opportunity_assistance_listing_assistance_listing_record_id_assistance_listing_fkey"),
        "opportunity_assistance_listing",
        schema="api",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("opportunity_assistance_listing_assistance_listing_record_id_idx"),
        table_name="opportunity_assistance_listing",
        schema="api",
    )
    op.alter_column(
        "opportunity_assistance_listing",
        "legacy_opportunity_assistance_listing_id",
        existing_type=sa.BIGINT(),
        nullable=False,
        schema="api",
    )
    op.drop_column("opportunity_assistance_listing", "assistance_listing_record_id", schema="api")
    op.drop_index(
        op.f("assistance_listing_assistance_listing_number_idx"),
        table_name="assistance_listing",
        schema="api",
    )
    op.drop_table("assistance_listing", schema="api")
    # ### end Alembic commands ###
