"""Sample test cases for XML validation against XSD schemas."""

from typing import Any

# Sample test cases for SF-424 validation
SF424_TEST_CASES = [
    {
        "name": "minimal_valid_sf424",
        "json_input": {
            "submission_type": "Application",
            "application_type": "New",
            "date_received": "2024-01-01",
            "organization_name": "Test Organization",
            "employer_taxpayer_identification_number": "123456789",
            "sam_uei": "TEST12345678",
            "applicant_address": {
                "street1": "123 Main St",
                "city": "Washington",
                "state": "DC: District of Columbia",
                "zip_postal_code": "20001",
                "country": "USA: UNITED STATES",
            },
            "phone_number": "555-123-4567",
            "email": "test@example.org",
            "applicant_type_code": ["A: State Government"],
            "agency_name": "Test Agency",
            "funding_opportunity_number": "TEST-FON-2024-001",
            "funding_opportunity_title": "Test Funding Opportunity",
            "project_title": "Test Project Title",
            "congressional_district_applicant": "DC-00",
            "congressional_district_program_project": "DC-00",
            "project_start_date": "2024-04-01",
            "project_end_date": "2025-03-31",
            "federal_estimated_funding": "100000.00",
            "applicant_estimated_funding": "0.00",
            "state_estimated_funding": "0.00",
            "local_estimated_funding": "0.00",
            "other_estimated_funding": "0.00",
            "program_income_estimated_funding": "0.00",
            "total_estimated_funding": "100000.00",
            "state_review": "c. Program is not covered by E.O. 12372.",
            "delinquent_federal_debt": False,
            "certification_agree": True,
            "authorized_representative": {"first_name": "John", "last_name": "Doe"},
            "authorized_representative_title": "CEO",
            "authorized_representative_phone_number": "555-123-4567",
            "authorized_representative_email": "john@testorg.com",
            "aor_signature": "John Doe Signature",
            "date_signed": "2025-01-15",
        },
        "form_name": "SF424_4_0",
        "xsd_url": "https://apply07.grants.gov/apply/forms/schemas/SF424_4_0-V4.0.xsd",
        "pretty_print": True,
    },
    {
        "name": "revision_application_sf424",
        "json_input": {
            "submission_type": "Application",
            "application_type": "New",
            "date_received": "2024-01-01",
            "organization_name": "Test Organization",
            "employer_taxpayer_identification_number": "123456789",
            "sam_uei": "TEST12345678",
            "applicant_address": {
                "street1": "123 Main St",
                "city": "Washington",
                "state": "DC: District of Columbia",
                "zip_postal_code": "20001",
                "country": "USA: UNITED STATES",
            },
            "phone_number": "555-123-4567",
            "email": "test@example.org",
            "applicant_type_code": ["A: State Government", "B: County Government"],
            "agency_name": "Test Agency",
            "funding_opportunity_number": "TEST-FON-2024-001",
            "funding_opportunity_title": "Test Funding Opportunity",
            "project_title": "Test Project Title",
            "congressional_district_applicant": "DC-00",
            "congressional_district_program_project": "DC-00",
            "project_start_date": "2024-04-01",
            "project_end_date": "2025-03-31",
            "revision_type": "Other",
            "federal_award_identifier": "HHS-2025-001",
            "federal_estimated_funding": "150000.00",
            "applicant_estimated_funding": "25000.00",
            "state_estimated_funding": "0.00",
            "local_estimated_funding": "0.00",
            "other_estimated_funding": "0.00",
            "program_income_estimated_funding": "0.00",
            "total_estimated_funding": "175000.00",
            "state_review": "c. Program is not covered by E.O. 12372.",
            "delinquent_federal_debt": False,
            "certification_agree": True,
            "authorized_representative": {"first_name": "John", "last_name": "Doe"},
            "authorized_representative_title": "Director",
            "authorized_representative_phone_number": "555-987-6543",
            "authorized_representative_email": "jane@testorg.com",
            "aor_signature": "Jane Smith Signature",
            "date_signed": "2025-01-15",
        },
        "form_name": "SF424_4_0",
        "xsd_url": "https://apply07.grants.gov/apply/forms/schemas/SF424_4_0-V4.0.xsd",
        "pretty_print": True,
    },
    {
        "name": "continuation_application_sf424",
        "json_input": {
            "submission_type": "Application",
            "application_type": "Continuation",
            "date_received": "2024-01-01",
            "organization_name": "Test Organization",
            "employer_taxpayer_identification_number": "123456789",
            "sam_uei": "TEST12345678",
            "applicant_address": {
                "street1": "456 Oak Ave",
                "city": "Washington",
                "state": "DC: District of Columbia",
                "zip_postal_code": "20002",
                "country": "USA: UNITED STATES",
            },
            "phone_number": "555-123-4567",
            "email": "test@example.org",
            "applicant_type_code": ["A: State Government"],
            "agency_name": "Test Agency",
            "funding_opportunity_number": "TEST-FON-2024-001",
            "funding_opportunity_title": "Test Funding Opportunity",
            "project_title": "Test Project Title",
            "congressional_district_applicant": "DC-00",
            "congressional_district_program_project": "DC-00",
            "project_start_date": "2024-04-01",
            "project_end_date": "2025-03-31",
            "federal_award_identifier": "HHS-2023-002",
            "federal_estimated_funding": "200000.00",
            "applicant_estimated_funding": "0.00",
            "state_estimated_funding": "0.00",
            "local_estimated_funding": "0.00",
            "other_estimated_funding": "0.00",
            "program_income_estimated_funding": "0.00",
            "total_estimated_funding": "100000.00",
            "state_review": "c. Program is not covered by E.O. 12372.",
            "delinquent_federal_debt": False,
            "certification_agree": True,
            "authorized_representative": {"first_name": "John", "last_name": "Doe"},
            "authorized_representative_name": "Bob Johnson",
            "authorized_representative_title": "President",
            "authorized_representative_phone_number": "555-456-7890",
            "authorized_representative_email": "bob@testorg.com",
            "aor_signature": "Bob Johnson Signature",
            "date_signed": "2025-01-15",
        },
        "form_name": "SF424_4_0",
        "xsd_url": "https://apply07.grants.gov/apply/forms/schemas/SF424_4_0-V4.0.xsd",
        "pretty_print": True,
    },
    {
        "name": "multiple_applicant_types_sf424",
        "json_input": {
            "submission_type": "Application",
            "application_type": "New",
            "date_received": "2024-01-01",
            "organization_name": "Test Organization",
            "employer_taxpayer_identification_number": "123456789",
            "sam_uei": "TEST12345678",
            "applicant_address": {
                "street1": "321 Elm St",
                "city": "Washington",
                "state": "DC: District of Columbia",
                "zip_postal_code": "20004",
                "country": "USA: UNITED STATES",
            },
            "phone_number": "555-123-4567",
            "email": "test@example.org",
            "applicant_type_code": [
                "A: State Government",
                "B: County Government",
                "C: City or Township Government",
            ],
            "agency_name": "Test Agency",
            "funding_opportunity_number": "TEST-FON-2024-001",
            "funding_opportunity_title": "Test Funding Opportunity",
            "project_title": "Test Project Title",
            "congressional_district_applicant": "DC-00",
            "congressional_district_program_project": "DC-00",
            "project_start_date": "2024-04-01",
            "project_end_date": "2025-03-31",
            "federal_estimated_funding": "300000.00",
            "applicant_estimated_funding": "50000.00",
            "state_estimated_funding": "25000.00",
            "local_estimated_funding": "10000.00",
            "other_estimated_funding": "15000.00",
            "program_income_estimated_funding": "0.00",
            "total_estimated_funding": "100000.00",
            "state_review": "c. Program is not covered by E.O. 12372.",
            "delinquent_federal_debt": False,
            "certification_agree": True,
            "authorized_representative": {"first_name": "John", "last_name": "Doe"},
            "authorized_representative_name": "Charlie Wilson",
            "authorized_representative_title": "Manager",
            "authorized_representative_phone_number": "555-654-3210",
            "authorized_representative_email": "charlie@testorg.com",
            "aor_signature": "Charlie Wilson Signature",
            "date_signed": "2025-01-15",
        },
        "form_name": "SF424_4_0",
        "xsd_url": "https://apply07.grants.gov/apply/forms/schemas/SF424_4_0-V4.0.xsd",
        "pretty_print": True,
    },
]


def get_all_test_cases() -> list[dict[str, Any]]:
    """Get all available test cases.

    Returns:
        List of all test case dictionaries
    """
    return SF424_TEST_CASES


def get_test_cases_by_form(form_name: str) -> list[dict[str, Any]]:
    """Get test cases for a specific form.

    Args:
        form_name: The form name to filter by

    Returns:
        List of test case dictionaries for the specified form
    """
    all_cases = get_all_test_cases()
    return [case for case in all_cases if case.get("form_name") == form_name]
