"""Sample test cases for XML validation against XSD schemas."""

from typing import Any

# Sample test cases for SF-424 validation
SF424_TEST_CASES = [
    {
        "name": "minimal_valid_sf424",
        "json_input": {
            "submission_type": "Application",
            "application_type": "New",
            "date_received": "2024-01-01",
            "organization_name": "Test Organization",
            "employer_taxpayer_identification_number": "123456789",
            "sam_uei": "TEST12345678",
            "applicant_address": {
                "street1": "123 Main St",
                "city": "Washington",
                "state": "DC: District of Columbia",
                "zip_postal_code": "20001",
                "country": "USA: UNITED STATES",
            },
            "phone_number": "555-123-4567",
            "email": "test@example.org",
            "applicant_type_code": ["A: State Government"],
            "agency_name": "Test Agency",
            "funding_opportunity_number": "TEST-FON-2024-001",
            "funding_opportunity_title": "Test Funding Opportunity",
            "project_title": "Test Project Title",
            "congressional_district_applicant": "DC-00",
            "congressional_district_program_project": "DC-00",
            "project_start_date": "2024-04-01",
            "project_end_date": "2025-03-31",
            "federal_estimated_funding": "100000.00",
            "applicant_estimated_funding": "0.00",
            "state_estimated_funding": "0.00",
            "local_estimated_funding": "0.00",
            "other_estimated_funding": "0.00",
            "program_income_estimated_funding": "0.00",
            "total_estimated_funding": "100000.00",
            "state_review": "c. Program is not covered by E.O. 12372.",
            "delinquent_federal_debt": False,
            "certification_agree": True,
            "authorized_representative": {"first_name": "John", "last_name": "Doe"},
            "authorized_representative_title": "CEO",
            "authorized_representative_phone_number": "555-123-4567",
            "authorized_representative_email": "john@testorg.com",
            "aor_signature": "John Doe Signature",
            "date_signed": "2025-01-15",
        },
        "form_name": "SF424_4_0",
        "xsd_url": "https://apply07.grants.gov/apply/forms/schemas/SF424_4_0-V4.0.xsd",
        "pretty_print": True,
    },
    {
        "name": "revision_application_sf424",
        "json_input": {
            "submission_type": "Application",
            "application_type": "New",
            "date_received": "2024-01-01",
            "organization_name": "Test Organization",
            "employer_taxpayer_identification_number": "123456789",
            "sam_uei": "TEST12345678",
            "applicant_address": {
                "street1": "123 Main St",
                "city": "Washington",
                "state": "DC: District of Columbia",
                "zip_postal_code": "20001",
                "country": "USA: UNITED STATES",
            },
            "phone_number": "555-123-4567",
            "email": "test@example.org",
            "applicant_type_code": ["A: State Government", "B: County Government"],
            "agency_name": "Test Agency",
            "funding_opportunity_number": "TEST-FON-2024-001",
            "funding_opportunity_title": "Test Funding Opportunity",
            "project_title": "Test Project Title",
            "congressional_district_applicant": "DC-00",
            "congressional_district_program_project": "DC-00",
            "project_start_date": "2024-04-01",
            "project_end_date": "2025-03-31",
            "revision_type": "Other",
            "federal_award_identifier": "HHS-2025-001",
            "federal_estimated_funding": "150000.00",
            "applicant_estimated_funding": "25000.00",
            "state_estimated_funding": "0.00",
            "local_estimated_funding": "0.00",
            "other_estimated_funding": "0.00",
            "program_income_estimated_funding": "0.00",
            "total_estimated_funding": "175000.00",
            "state_review": "c. Program is not covered by E.O. 12372.",
            "delinquent_federal_debt": False,
            "certification_agree": True,
            "authorized_representative": {"first_name": "John", "last_name": "Doe"},
            "authorized_representative_title": "Director",
            "authorized_representative_phone_number": "555-987-6543",
            "authorized_representative_email": "jane@testorg.com",
            "aor_signature": "Jane Smith Signature",
            "date_signed": "2025-01-15",
        },
        "form_name": "SF424_4_0",
        "xsd_url": "https://apply07.grants.gov/apply/forms/schemas/SF424_4_0-V4.0.xsd",
        "pretty_print": True,
    },
    {
        "name": "continuation_application_sf424",
        "json_input": {
            "submission_type": "Application",
            "application_type": "Continuation",
            "date_received": "2024-01-01",
            "organization_name": "Test Organization",
            "employer_taxpayer_identification_number": "123456789",
            "sam_uei": "TEST12345678",
            "applicant_address": {
                "street1": "456 Oak Ave",
                "city": "Washington",
                "state": "DC: District of Columbia",
                "zip_postal_code": "20002",
                "country": "USA: UNITED STATES",
            },
            "phone_number": "555-123-4567",
            "email": "test@example.org",
            "applicant_type_code": ["A: State Government"],
            "agency_name": "Test Agency",
            "funding_opportunity_number": "TEST-FON-2024-001",
            "funding_opportunity_title": "Test Funding Opportunity",
            "project_title": "Test Project Title",
            "congressional_district_applicant": "DC-00",
            "congressional_district_program_project": "DC-00",
            "project_start_date": "2024-04-01",
            "project_end_date": "2025-03-31",
            "federal_award_identifier": "HHS-2023-002",
            "federal_estimated_funding": "200000.00",
            "applicant_estimated_funding": "0.00",
            "state_estimated_funding": "0.00",
            "local_estimated_funding": "0.00",
            "other_estimated_funding": "0.00",
            "program_income_estimated_funding": "0.00",
            "total_estimated_funding": "100000.00",
            "state_review": "c. Program is not covered by E.O. 12372.",
            "delinquent_federal_debt": False,
            "certification_agree": True,
            "authorized_representative": {"first_name": "John", "last_name": "Doe"},
            "authorized_representative_name": "Bob Johnson",
            "authorized_representative_title": "President",
            "authorized_representative_phone_number": "555-456-7890",
            "authorized_representative_email": "bob@testorg.com",
            "aor_signature": "Bob Johnson Signature",
            "date_signed": "2025-01-15",
        },
        "form_name": "SF424_4_0",
        "xsd_url": "https://apply07.grants.gov/apply/forms/schemas/SF424_4_0-V4.0.xsd",
        "pretty_print": True,
    },
    {
        "name": "multiple_applicant_types_sf424",
        "json_input": {
            "submission_type": "Application",
            "application_type": "New",
            "date_received": "2024-01-01",
            "organization_name": "Test Organization",
            "employer_taxpayer_identification_number": "123456789",
            "sam_uei": "TEST12345678",
            "applicant_address": {
                "street1": "321 Elm St",
                "city": "Washington",
                "state": "DC: District of Columbia",
                "zip_postal_code": "20004",
                "country": "USA: UNITED STATES",
            },
            "phone_number": "555-123-4567",
            "email": "test@example.org",
            "applicant_type_code": [
                "A: State Government",
                "B: County Government",
                "C: City or Township Government",
            ],
            "agency_name": "Test Agency",
            "funding_opportunity_number": "TEST-FON-2024-001",
            "funding_opportunity_title": "Test Funding Opportunity",
            "project_title": "Test Project Title",
            "congressional_district_applicant": "DC-00",
            "congressional_district_program_project": "DC-00",
            "project_start_date": "2024-04-01",
            "project_end_date": "2025-03-31",
            "federal_estimated_funding": "300000.00",
            "applicant_estimated_funding": "50000.00",
            "state_estimated_funding": "25000.00",
            "local_estimated_funding": "10000.00",
            "other_estimated_funding": "15000.00",
            "program_income_estimated_funding": "0.00",
            "total_estimated_funding": "100000.00",
            "state_review": "c. Program is not covered by E.O. 12372.",
            "delinquent_federal_debt": False,
            "certification_agree": True,
            "authorized_representative": {"first_name": "John", "last_name": "Doe"},
            "authorized_representative_name": "Charlie Wilson",
            "authorized_representative_title": "Manager",
            "authorized_representative_phone_number": "555-654-3210",
            "authorized_representative_email": "charlie@testorg.com",
            "aor_signature": "Charlie Wilson Signature",
            "date_signed": "2025-01-15",
        },
        "form_name": "SF424_4_0",
        "xsd_url": "https://apply07.grants.gov/apply/forms/schemas/SF424_4_0-V4.0.xsd",
        "pretty_print": True,
    },
    {
        "name": "sf424_with_single_attachment",
        "json_input": {
            "submission_type": "Application",
            "application_type": "New",
            "date_received": "2024-01-01",
            "organization_name": "Test Organization",
            "employer_taxpayer_identification_number": "123456789",
            "sam_uei": "TEST12345678",
            "applicant_address": {
                "street1": "123 Main St",
                "city": "Washington",
                "state": "DC: District of Columbia",
                "zip_postal_code": "20001",
                "country": "USA: UNITED STATES",
            },
            "phone_number": "555-123-4567",
            "email": "test@example.org",
            "applicant_type_code": ["A: State Government"],
            "agency_name": "Test Agency",
            "funding_opportunity_number": "TEST-FON-2024-001",
            "funding_opportunity_title": "Test Funding Opportunity",
            "project_title": "Test Project Title",
            "congressional_district_applicant": "DC-00",
            "congressional_district_program_project": "DC-00",
            "project_start_date": "2024-04-01",
            "project_end_date": "2025-03-31",
            "federal_estimated_funding": "100000.00",
            "applicant_estimated_funding": "0.00",
            "state_estimated_funding": "0.00",
            "local_estimated_funding": "0.00",
            "other_estimated_funding": "0.00",
            "program_income_estimated_funding": "0.00",
            "total_estimated_funding": "100000.00",
            "state_review": "c. Program is not covered by E.O. 12372.",
            "delinquent_federal_debt": True,
            "debt_explanation": "11111111-1111-1111-1111-111111111111",  # UUID reference
            "certification_agree": True,
            "authorized_representative": {"first_name": "John", "last_name": "Doe"},
            "authorized_representative_title": "CEO",
            "authorized_representative_phone_number": "555-123-4567",
            "authorized_representative_email": "john@testorg.com",
            "aor_signature": "John Doe Signature",
            "date_signed": "2025-01-15",
        },
        "form_name": "SF424_4_0",
        "xsd_url": "https://apply07.grants.gov/apply/forms/schemas/SF424_4_0-V4.0.xsd",
        "pretty_print": True,
        "attachment_mapping": {
            "11111111-1111-1111-1111-111111111111": {
                "FileName": "debt_explanation.pdf",
                "MimeType": "application/pdf",
                "FileLocation": {"@href": "./attachments/debt_explanation.pdf"},
                "HashValue": {
                    "@hashAlgorithm": "SHA-1",
                    "#text": "aGVsbG8gd29ybGQxMjM0NTY3ODk=",
                },
            }
        },
    },
    {
        "name": "sf424_with_multiple_attachments",
        "json_input": {
            "submission_type": "Application",
            "application_type": "New",
            "date_received": "2024-01-01",
            "organization_name": "Test Organization",
            "employer_taxpayer_identification_number": "123456789",
            "sam_uei": "TEST12345678",
            "applicant_address": {
                "street1": "123 Main St",
                "city": "Washington",
                "state": "DC: District of Columbia",
                "zip_postal_code": "20001",
                "country": "USA: UNITED STATES",
            },
            "phone_number": "555-123-4567",
            "email": "test@example.org",
            "applicant_type_code": ["A: State Government"],
            "agency_name": "Test Agency",
            "funding_opportunity_number": "TEST-FON-2024-001",
            "funding_opportunity_title": "Test Funding Opportunity",
            "project_title": "Test Project Title",
            "congressional_district_applicant": "DC-00",
            "congressional_district_program_project": "DC-00",
            "project_start_date": "2024-04-01",
            "project_end_date": "2025-03-31",
            "federal_estimated_funding": "100000.00",
            "applicant_estimated_funding": "0.00",
            "state_estimated_funding": "0.00",
            "local_estimated_funding": "0.00",
            "other_estimated_funding": "0.00",
            "program_income_estimated_funding": "0.00",
            "total_estimated_funding": "100000.00",
            "state_review": "c. Program is not covered by E.O. 12372.",
            "delinquent_federal_debt": False,
            "additional_project_title": [
                "22222222-2222-2222-2222-222222222222",
                "33333333-3333-3333-3333-333333333333",
            ],
            "certification_agree": True,
            "authorized_representative": {"first_name": "John", "last_name": "Doe"},
            "authorized_representative_title": "CEO",
            "authorized_representative_phone_number": "555-123-4567",
            "authorized_representative_email": "john@testorg.com",
            "aor_signature": "John Doe Signature",
            "date_signed": "2025-01-15",
        },
        "form_name": "SF424_4_0",
        "xsd_url": "https://apply07.grants.gov/apply/forms/schemas/SF424_4_0-V4.0.xsd",
        "pretty_print": True,
        "attachment_mapping": {
            "22222222-2222-2222-2222-222222222222": {
                "FileName": "project_description.pdf",
                "MimeType": "application/pdf",
                "FileLocation": {"@href": "./attachments/project_description.pdf"},
                "HashValue": {
                    "@hashAlgorithm": "SHA-1",
                    "#text": "cHJvamVjdERlc2NyaXB0aW9uSGFzaA==",
                },
            },
            "33333333-3333-3333-3333-333333333333": {
                "FileName": "project_timeline.xlsx",
                "MimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "FileLocation": {"@href": "./attachments/project_timeline.xlsx"},
                "HashValue": {
                    "@hashAlgorithm": "SHA-1",
                    "#text": "cHJvamVjdFRpbWVsaW5lSGFzaA==",
                },
            },
        },
    },
    {
        "name": "sf424_with_all_attachment_types",
        "json_input": {
            "submission_type": "Application",
            "application_type": "New",
            "date_received": "2024-01-01",
            "organization_name": "Test Organization",
            "employer_taxpayer_identification_number": "123456789",
            "sam_uei": "TEST12345678",
            "applicant_address": {
                "street1": "123 Main St",
                "city": "Washington",
                "state": "DC: District of Columbia",
                "zip_postal_code": "20001",
                "country": "USA: UNITED STATES",
            },
            "phone_number": "555-123-4567",
            "email": "test@example.org",
            "applicant_type_code": ["A: State Government"],
            "agency_name": "Test Agency",
            "funding_opportunity_number": "TEST-FON-2024-001",
            "funding_opportunity_title": "Test Funding Opportunity",
            "project_title": "Test Project Title",
            "congressional_district_applicant": "DC-00",
            "congressional_district_program_project": "DC-00, VA-08",
            "additional_congressional_districts": "44444444-4444-4444-4444-444444444444",
            "project_start_date": "2024-04-01",
            "project_end_date": "2025-03-31",
            "federal_estimated_funding": "100000.00",
            "applicant_estimated_funding": "0.00",
            "state_estimated_funding": "0.00",
            "local_estimated_funding": "0.00",
            "other_estimated_funding": "0.00",
            "program_income_estimated_funding": "0.00",
            "total_estimated_funding": "100000.00",
            "areas_affected": "55555555-5555-5555-5555-555555555555",
            "state_review": "c. Program is not covered by E.O. 12372.",
            "delinquent_federal_debt": True,
            "debt_explanation": "66666666-6666-6666-6666-666666666666",
            "additional_project_title": [
                "77777777-7777-7777-7777-777777777777",
                "88888888-8888-8888-8888-888888888888",
                "99999999-9999-9999-9999-999999999999",
            ],
            "certification_agree": True,
            "authorized_representative": {"first_name": "John", "last_name": "Doe"},
            "authorized_representative_title": "CEO",
            "authorized_representative_phone_number": "555-123-4567",
            "authorized_representative_email": "john@testorg.com",
            "aor_signature": "John Doe Signature",
            "date_signed": "2025-01-15",
        },
        "form_name": "SF424_4_0",
        "xsd_url": "https://apply07.grants.gov/apply/forms/schemas/SF424_4_0-V4.0.xsd",
        "pretty_print": True,
        "attachment_mapping": {
            "44444444-4444-4444-4444-444444444444": {
                "FileName": "additional_districts.pdf",
                "MimeType": "application/pdf",
                "FileLocation": {"@href": "./attachments/additional_districts.pdf"},
                "HashValue": {
                    "@hashAlgorithm": "SHA-1",
                    "#text": "YWRkaXRpb25hbERpc3RyaWN0c0hhc2g=",
                },
            },
            "55555555-5555-5555-5555-555555555555": {
                "FileName": "geographic_areas.pdf",
                "MimeType": "application/pdf",
                "FileLocation": {"@href": "./attachments/geographic_areas.pdf"},
                "HashValue": {
                    "@hashAlgorithm": "SHA-1",
                    "#text": "Z2VvZ3JhcGhpY0FyZWFzSGFzaA==",
                },
            },
            "66666666-6666-6666-6666-666666666666": {
                "FileName": "debt_explanation_detailed.docx",
                "MimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "FileLocation": {"@href": "./attachments/debt_explanation_detailed.docx"},
                "HashValue": {
                    "@hashAlgorithm": "SHA-1",
                    "#text": "ZGVidEV4cGxhbmF0aW9uSGFzaA==",
                },
            },
            "77777777-7777-7777-7777-777777777777": {
                "FileName": "project_overview.pdf",
                "MimeType": "application/pdf",
                "FileLocation": {"@href": "./attachments/project_overview.pdf"},
                "HashValue": {
                    "@hashAlgorithm": "SHA-1",
                    "#text": "cHJvamVjdE92ZXJ2aWV3SGFzaA==",
                },
            },
            "88888888-8888-8888-8888-888888888888": {
                "FileName": "project_budget.xlsx",
                "MimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "FileLocation": {"@href": "./attachments/project_budget.xlsx"},
                "HashValue": {
                    "@hashAlgorithm": "SHA-1",
                    "#text": "cHJvamVjdEJ1ZGdldEhhc2g=",
                },
            },
            "99999999-9999-9999-9999-999999999999": {
                "FileName": "project_partners.txt",
                "MimeType": "text/plain",
                "FileLocation": {"@href": "./attachments/project_partners.txt"},
                "HashValue": {
                    "@hashAlgorithm": "SHA-1",
                    "#text": "cHJvamVjdFBhcnRuZXJzSGFzaA==",
                },
            },
        },
    },
]


def get_all_test_cases() -> list[dict[str, Any]]:
    """Get all available test cases.

    Returns:
        List of all test case dictionaries
    """
    return SF424_TEST_CASES


def get_test_cases_by_form(form_name: str) -> list[dict[str, Any]]:
    """Get test cases for a specific form.

    Args:
        form_name: The form name to filter by

    Returns:
        List of test case dictionaries for the specified form
    """
    all_cases = get_all_test_cases()
    return [case for case in all_cases if case.get("form_name") == form_name]
