FORM_NAME = "Application For Federal Assistance SFS 424 - Individual"

UI_SCHEMA = [
    {
        "type": "section",
        "label": "1. Name of Federal Agency",
        "name": "NameFederalAgency",
        "children": [{"type": "field", "definition": "/properties/FederalAgency"}],
    },
    {
        "type": "section",
        "label": "2. Assistance Listing Number",
        "name": "AssistanceListingNumber",
        "children": [
            {"type": "field", "definition": "/properties/CFDANumber"},
            {"type": "field", "definition": "/properties/CFDATitle"},
        ],
    },
    {
        "type": "section",
        "label": "3. Date Received",
        "name": "DateReived",
        "children": [
            {
                "type": "field",
                "schema": {
                    "title": "Date received",
                    "type": "null",
                    "description": "Completed by Grants.gov upon submission.",
                },
            }
        ],
    },
    {
        "type": "section",
        "label": "4. Funding Opportunity Number",
        "name": "FundingOpportunityNumber",
        "children": [
            {"type": "field", "definition": "/properties/OpportunityID"},
            {"type": "field", "definition": "/properties/OpportunityTitle"},
        ],
    },
    {
        "type": "section",
        "label": "5. Applicant Information",
        "name": "ApplicantInformationHeader",
        "children": [
            {
                "type": "section",
                "label": "5a. Name and Contact Information",
                "name": "NameandContactInformationHeader",
                "children": [
                    {"type": "field", "definition": "/properties/PrefixName"},
                    {"type": "field", "definition": "/properties/FirstName"},
                    {"type": "field", "definition": "/properties/MiddleName"},
                    {"type": "field", "definition": "/properties/LastName"},
                    {"type": "field", "definition": "/properties/Suffix"},
                    {
                        "type": "field",
                        "definition": "/properties/AuthorizedRepresentativePhoneNumber",
                    },
                    {"type": "field", "definition": "/properties/EveningPhone"},
                    {"type": "field", "definition": "/properties/AuthorizedRepresentativeFax"},
                    {"type": "field", "definition": "/properties/AuthorizedRepresentativeEmail"},
                ],
            },
            {
                "type": "section",
                "label": "5b. Address",
                "name": "AddressHeader",
                "children": [
                    {"type": "field", "definition": "/properties/Street1"},
                    {"type": "field", "definition": "/properties/Street2"},
                    {"type": "field", "definition": "/properties/City"},
                    {"type": "field", "definition": "/properties/County"},
                    {"type": "field", "definition": "/properties/State"},
                    {"type": "field", "definition": "/properties/Province"},
                    {"type": "field", "definition": "/properties/Country"},
                    {"type": "field", "definition": "/properties/ZipPostalCode"},
                ],
            },
            {
                "type": "section",
                "label": "5c. Citizenship Status",
                "name": "CitizenshipStatusHeader",
                "children": [
                    {"type": "field", "definition": "/properties/citizenship"},
                    {"type": "field", "definition": "/properties/AlienRegistrationNumber"},
                    {"type": "field", "definition": "/properties/CountryofOrigin"},
                    {"type": "field", "definition": "/properties/VisitDate"},
                ],
            },
            {
                "type": "section",
                "label": "5d. Congressional District of Applicant",
                "name": "CongressionalDistrictApplicant",
                "children": [
                    {"type": "field", "definition": "/properties/CongressionalDistrictApplicant"}
                ],
            },
        ],
    },
    {
        "type": "section",
        "label": "6. Project Information",
        "name": "ProjectInformationHeader",
        "children": [
            {
                "type": "section",
                "label": "6a. Project Title",
                "name": "ProjectTitle",
                "children": [{"type": "field", "definition": "/properties/ProjectTitle"}],
            },
            {
                "type": "section",
                "label": "6b. Project Description",
                "name": "ProjectDescription",
                "children": [{"type": "field", "definition": "/properties/ProjectDescription"}],
            },
            {
                "type": "section",
                "label": "6c. Proposed Project",
                "name": "ProposedProjectHeader",
                "children": [
                    {"type": "field", "definition": "/properties/FundingPeriodStartDate"},
                    {"type": "field", "definition": "/properties/FundingPeriodEndDate"},
                ],
            },
        ],
    },
    {
        "type": "section",
        "label": "7. Certification Text",
        "name": "CertificationText",
        "children": [
            {"type": "field", "definition": "/properties/ApplicationCertification"},
            {
                "type": "field",
                "schema": {
                    "title": "Signature",
                    "type": "null",
                    "description": "Completed by Grants.gov upon submission.",
                },
            },
            {
                "type": "field",
                "schema": {
                    "title": "Date",
                    "type": "null",
                    "description": "Completed by Grants.gov upon submission.",
                },
            },
        ],
    },
]

JSON_SCHEMA_FORM = {
    "type": "object",
    "required": [
        "FederalAgency",
        "OpportunityID",
        "OpportunityTitle",
        "FirstName",
        "LastName",
        "AuthorizedRepresentativePhoneNumber",
        "AuthorizedRepresentativeEmail",
        "Street1",
        "City",
        "Country",
        "citizenship",
        "CongressionalDistrictApplicant",
        "ProjectTitle",
        "ProjectDescription",
        "FundingPeriodStartDate",
        "FundingPeriodEndDate",
        "ApplicationCertification",
    ],
    "properties": {
        "FederalAgency": {
            "type": "string",
            "title": "Name of Federal Agency",
            "minLength": 1,
            "maxLength": 60,
        },
        "CFDANumber": {
            "type": "string",
            "title": "Assistance Listing Number",
            "minLength": 0,
            "maxLength": 15,
        },
        "CFDATitle": {
            "type": "string",
            "title": "Assistance Listing Title",
            "minLength": 0,
            "maxLength": 120,
        },
        "OpportunityID": {
            "type": "string",
            "title": "Funding Opportunity Number",
            "minLength": 1,
            "maxLength": 40,
        },
        "OpportunityTitle": {
            "type": "string",
            "title": "Funding Opportunity Title",
            "minLength": 1,
            "maxLength": 255,
        },
        "PrefixName": {
            "type": "string",
            "title": "Prefix",
            "minLength": 0,
            "maxLength": 10,
            "enum": ["Mr.", "Mrs.", "Miss", "Ms.", "Dr.", "Rev."],
        },
        "FirstName": {"type": "string", "title": "First Name", "minLength": 1, "maxLength": 35},
        "MiddleName": {"type": "string", "title": "Middle Name", "minLength": 0, "maxLength": 25},
        "LastName": {"type": "string", "title": "Last Name", "minLength": 1, "maxLength": 60},
        "Suffix": {
            "type": "string",
            "title": "Suffix",
            "minLength": 0,
            "maxLength": 10,
            "enum": ["Jr.", "Sr.", "M.D.", "Ph.D"],
        },
        "AuthorizedRepresentativePhoneNumber": {
            "type": "string",
            "title": "Daytime Phone Number",
            "minLength": 1,
            "maxLength": 25,
        },
        "EveningPhone": {
            "type": "string",
            "title": "Evening Phone Number",
            "minLength": 0,
            "maxLength": 25,
        },
        "AuthorizedRepresentativeFax": {
            "type": "string",
            "title": "Fax Number",
            "minLength": 1,
            "maxLength": 25,
        },
        "AuthorizedRepresentativeEmail": {
            "type": "string",
            "title": "Email",
            "description": "Enter a valid Email Address.",
            "minLength": 1,
            "maxLength": 60,
            "format": "email",
        },
        "Street1": {"type": "string", "title": "Street1", "minLength": 1, "maxLength": 55},
        "Street2": {"type": "string", "title": "Street2", "minLength": 0, "maxLength": 55},
        "City": {"type": "string", "title": "City", "minLength": 1, "maxLength": 35},
        "County": {"type": "string", "title": "County/Parish", "minLength": 0, "maxLength": 30},
        "State": {"$ref": "#/$defs/StateCode", "title": "State"},
        "Province": {"type": "string", "title": "Province", "minLength": 0, "maxLength": 30},
        "Country": {"$ref": "#/$defs/CountryCode", "title": "Country"},
        "ZipPostalCode": {
            "type": "string",
            "title": "Zip/Postal Code",
            "description": "Enter the nine-digit Postal Code (e.g., ZIP code). This field is required if the country is the United States.",
            "minLength": 0,
            "maxLength": 30,
        },
        "citizenship": {"type": "string", "title": "U.S. Citizenship", "enum": ["Y: Yes", "N: No"]},
        "AlienRegistrationNumber": {
            "type": "string",
            "title": "Alien Registration Number",
            "description": "If a permanent resident of the U.S., enter your Alien Registration Number.",
            "minLength": 0,
            "maxLength": 14,
        },
        "CountryofOrigin": {
            "$ref": "#/$defs/CountryCode",
            "title": "Citizenship Country",
            "description": "If foreign national, enter country of citizenship.",
        },
        "VisitDate": {
            "type": "string",
            "title": "Residency Start Date",
            "description": "If foreign national, enter start date of the most recent residency in the U.S. This field is required if the applicant is not a U.S. Citizen.",
            "format": "date",
        },
        "CongressionalDistrictApplicant": {
            "type": "string",
            "title": "Congressional District of Applicant",
            "description": "Enter the Congressional District in the format: 2 character State Abbreviation - 3 character District Number. Examples: CA-005 for California's 5th district, CA-012 for California's 12th district, NC-103 for North Carolina's 103rd district. If outside the US, enter 00-000.",
            "minLength": 1,
            "maxLength": 6,
        },
        "ProjectTitle": {
            "type": "string",
            "title": "Project Title",
            "description": "Enter a brief, descriptive title of the project.",
            "minLength": 1,
            "maxLength": 200,
        },
        "ProjectDescription": {
            "type": "string",
            "title": "Project Description",
            "description": "Enter a brief description of the project.",
            "minLength": 1,
            "maxLength": 1000,
        },
        "FundingPeriodStartDate": {
            "type": "string",
            "title": "Proposed Project Start Date",
            "format": "date",
        },
        "FundingPeriodEndDate": {
            "type": "string",
            "title": "Proposed Project End Date",
            "format": "date",
        },
        "ApplicationCertification": {
            "type": "string",
            "title": "I Agree",
            "enum": ["Y: Yes", "N: No"],
        },
    },
    "$defs": {
        "StateCode": {
            "type": "string",
            "title": "State",
            "enum": [
                "AL: Alabama",
                "AK: Alaska",
                "AZ: Arizona",
                "AR: Arkansas",
                "CA: California",
                "CO: Colorado",
                "CT: Connecticut",
                "DE: Delaware",
                "DC: District of Columbia",
                "FL: Florida",
                "GA: Georgia",
                "HI: Hawaii",
                "ID: Idaho",
                "IL: Illinois",
                "IN: Indiana",
                "IA: Iowa",
                "KS: Kansas",
                "KY: Kentucky",
                "LA: Louisiana",
                "ME: Maine",
                "MD: Maryland",
                "MA: Massachusetts",
                "MI: Michigan",
                "MN: Minnesota",
                "MS: Mississippi",
                "MO: Missouri",
                "MT: Montana",
                "NE: Nebraska",
                "NV: Nevada",
                "NH: New Hampshire",
                "NJ: New Jersey",
                "NM: New Mexico",
                "NY: New York",
                "NC: North Carolina",
                "ND: North Dakota",
                "OH: Ohio",
                "OK: Oklahoma",
                "OR: Oregon",
                "PA: Pennsylvania",
                "RI: Rhode Island",
                "SC: South Carolina",
                "SD: South Dakota",
                "TN: Tennessee",
                "TX: Texas",
                "UT: Utah",
                "VT: Vermont",
                "VA: Virginia",
                "WA: Washington",
                "WV: West Virginia",
                "WI: Wisconsin",
                "WY: Wyoming",
                "AS: American Samoa",
                "FM: Federated States of Micronesia",
                "GU: Guam",
                "MH: Marshall Islands",
                "MP: Northern Mariana Islands",
                "PW: Palau",
                "PR: Puerto Rico",
                "VI: Virgin Islands",
                "FQ: Baker Island",
                "HQ: Howland Island",
                "DQ: Jarvis Island",
                "JQ: Johnston Atoll",
                "KQ: Kingman Reef",
                "MQ: Midway Islands",
                "BQ: Navassa Island",
                "LQ: Palmyra Atoll",
                "WQ: Wake Island",
                "AA: Armed Forces Americas (except Canada)",
                "AE: Armed Forces Europe, the Middle East, and Canada",
                "AP: Armed Forces Pacific",
            ],
        },
        "CountryCode": {
            "type": "string",
            "title": "Country",
            "enum": [
                "AFG: AFGHANISTAN",
                "XQZ: AKROTIRI",
                "ALB: ALBANIA",
                "DZA: ALGERIA",
                "AND: ANDORRA",
                "AGO: ANGOLA",
                "AIA: ANGUILLA",
                "ATA: ANTARCTICA",
                "ATG: ANTIGUA AND BARBUDA",
                "ARG: ARGENTINA",
                "ARM: ARMENIA",
                "ABW: ARUBA",
                "XAC: ASHMORE AND CARTIER ISLANDS",
                "AUS: AUSTRALIA",
                "AUT: AUSTRIA",
                "AZE: AZERBAIJAN",
                "BHS: BAHAMAS, THE",
                "BHR: BAHRAIN",
                "BGD: BANGLADESH",
                "BRB: BARBADOS",
                "XBI: BASSAS DA INDIA",
                "BLR: BELARUS",
                "BEL: BELGIUM",
                "BLZ: BELIZE",
                "BEN: BENIN",
                "BMU: BERMUDA",
                "BTN: BHUTAN",
                "BOL: BOLIVIA",
                "BES: BONAIRE, SINT EUSTATIUS, AND SABA",
                "BIH: BOSNIA AND HERZEGOVINA",
                "BWA: BOTSWANA",
                "BVT: BOUVET ISLAND",
                "BRA: BRAZIL",
                "IOT: BRITISH INDIAN OCEAN TERRITORY",
                "BRN: BRUNEI",
                "BGR: BULGARIA",
                "BFA: BURKINA FASO",
                "MMR: BURMA",
                "BDI: BURUNDI",
                "CPV: CABO VERDE",
                "KHM: CAMBODIA",
                "CMR: CAMEROON",
                "CAN: CANADA",
                "CYM: CAYMAN ISLANDS",
                "CAF: CENTRAL AFRICAN REPUBLIC",
                "TCD: CHAD",
                "CHL: CHILE",
                "CHN: CHINA",
                "CXR: CHRISTMAS ISLAND",
                "CPT: CLIPPERTON ISLAND",
                "CCK: COCOS (KEELING) ISLANDS",
                "COL: COLOMBIA",
                "COM: COMOROS",
                "COG: CONGO (BRAZZAVILLE)",
                "COD: CONGO (KINSHASA)",
                "COK: COOK ISLANDS",
                "XCS: CORAL SEA ISLANDS",
                "CRI: COSTA RICA",
                "CIV: CÔTE D'IVOIRE",
                "HRV: CROATIA",
                "CUB: CUBA",
                "CUW: CURAÇAO",
                "CYP: CYPRUS",
                "CZE: CZECHIA",
                "DNK: DENMARK",
                "XXD: DHEKELIA",
                "DGA: DIEGO GARCIA",
                "DJI: DJIBOUTI",
                "DMA: DOMINICA",
                "DOM: DOMINICAN REPUBLIC",
                "ECU: ECUADOR",
                "EGY: EGYPT",
                "SLV: EL SALVADOR",
                "XAZ: ENTITY 1",
                "XCR: ENTITY 2",
                "XCY: ENTITY 3",
                "XKM: ENTITY 4",
                "XKN: ENTITY 5",
                "AX3: ENTITY 6",
                "GNQ: EQUATORIAL GUINEA",
                "ERI: ERITREA",
                "EST: ESTONIA",
                "SWZ: ESWATINI",
                "ETH: ETHIOPIA",
                "XEU: EUROPA ISLAND",
                "FLK: FALKLAND ISLANDS (ISLAS MALVINAS)",
                "FRO: FAROE ISLANDS",
                "FJI: FIJI",
                "FIN: FINLAND",
                "FRA: FRANCE",
                "GUF: FRENCH GUIANA",
                "PYF: FRENCH POLYNESIA",
                "ATF: FRENCH SOUTHERN AND ANTARCTIC LANDS",
                "GAB: GABON",
                "GMB: GAMBIA, THE",
                "XGZ: GAZA STRIP",
                "GEO: GEORGIA",
                "DEU: GERMANY",
                "GHA: GHANA",
                "GIB: GIBRALTAR",
                "XGL: GLORIOSO ISLANDS",
                "GRC: GREECE",
                "GRL: GREENLAND",
                "GRD: GRENADA",
                "GLP: GUADELOUPE",
                "GTM: GUATEMALA",
                "GGY: GUERNSEY",
                "GIN: GUINEA",
                "GNB: GUINEA-BISSAU",
                "GUY: GUYANA",
                "HTI: HAITI",
                "HMD: HEARD ISLAND AND MCDONALD ISLANDS",
                "HND: HONDURAS",
                "HKG: HONG KONG",
                "HUN: HUNGARY",
                "ISL: ICELAND",
                "IND: INDIA",
                "IDN: INDONESIA",
                "IRN: IRAN",
                "IRQ: IRAQ",
                "IRL: IRELAND",
                "IMN: ISLE OF MAN",
                "ISR: ISRAEL",
                "ITA: ITALY",
                "JAM: JAMAICA",
                "XJM: JAN MAYEN",
                "JPN: JAPAN",
                "JEY: JERSEY",
                "JOR: JORDAN",
                "XJN: JUAN DE NOVA ISLAND",
                "KAZ: KAZAKHSTAN",
                "KEN: KENYA",
                "KIR: KIRIBATI",
                "PRK: KOREA, NORTH",
                "KOR: KOREA, SOUTH",
                "XKS: KOSOVO",
                "KWT: KUWAIT",
                "KGZ: KYRGYZSTAN",
                "LAO: LAOS",
                "LVA: LATVIA",
                "LBN: LEBANON",
                "LSO: LESOTHO",
                "LBR: LIBERIA",
                "LBY: LIBYA",
                "LIE: LIECHTENSTEIN",
                "LTU: LITHUANIA",
                "LUX: LUXEMBOURG",
                "MAC: MACAU",
                "MDG: MADAGASCAR",
                "MWI: MALAWI",
                "MYS: MALAYSIA",
                "MDV: MALDIVES",
                "MLI: MALI",
                "MLT: MALTA",
                "MTQ: MARTINIQUE",
                "MRT: MAURITANIA",
                "MUS: MAURITIUS",
                "MYT: MAYOTTE",
                "MEX: MEXICO",
                "MDA: MOLDOVA",
                "MCO: MONACO",
                "MNG: MONGOLIA",
                "MNE: MONTENEGRO",
                "MSR: MONTSERRAT",
                "MAR: MOROCCO",
                "MOZ: MOZAMBIQUE",
                "NAM: NAMIBIA",
                "NRU: NAURU",
                "NPL: NEPAL",
                "NLD: NETHERLANDS",
                "NCL: NEW CALEDONIA",
                "NZL: NEW ZEALAND",
                "NIC: NICARAGUA",
                "NER: NIGER",
                "NGA: NIGERIA",
                "NIU: NIUE",
                "NFK: NORFOLK ISLAND",
                "MKD: NORTH MACEDONIA",
                "NOR: NORWAY",
                "OMN: OMAN",
                "PAK: PAKISTAN",
                "PAN: PANAMA",
                "PNG: PAPUA NEW GUINEA",
                "XPR: PARACEL ISLANDS",
                "PRY: PARAGUAY",
                "PER: PERU",
                "PHL: PHILIPPINES",
                "PCN: PITCAIRN ISLANDS",
                "POL: POLAND",
                "PRT: PORTUGAL",
                "QAT: QATAR",
                "REU: REUNION",
                "ROU: ROMANIA",
                "RUS: RUSSIA",
                "RWA: RWANDA",
                "BLM: SAINT BARTHELEMY",
                "SHN: SAINT HELENA, ASCENSION, AND TRISTAN DA CUNHA",
                "KNA: SAINT KITTS AND NEVIS",
                "LCA: SAINT LUCIA",
                "MAF: SAINT MARTIN",
                "SPM: SAINT PIERRE AND MIQUELON",
                "VCT: SAINT VINCENT AND THE GRENADINES",
                "WSM: SAMOA",
                "SMR: SAN MARINO",
                "STP: SAO TOME AND PRINCIPE",
                "SAU: SAUDI ARABIA",
                "SEN: SENEGAL",
                "SRB: SERBIA",
                "SYC: SEYCHELLES",
                "SLE: SIERRA LEONE",
                "SGP: SINGAPORE",
                "SXM: SINT MAARTEN",
                "SVK: SLOVAKIA",
                "SVN: SLOVENIA",
                "SLB: SOLOMON ISLANDS",
                "SOM: SOMALIA",
                "ZAF: SOUTH AFRICA",
                "SGS: SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS",
                "SSD: SOUTH SUDAN",
                "ESP: SPAIN",
                "XSP: SPRATLY ISLANDS",
                "LKA: SRI LANKA",
                "SDN: SUDAN",
                "SUR: SURINAME",
                "XSV: SVALBARD",
                "SWE: SWEDEN",
                "CHE: SWITZERLAND",
                "SYR: SYRIA",
                "TWN: TAIWAN",
                "TJK: TAJIKISTAN",
                "TZA: TANZANIA",
                "THA: THAILAND",
                "TLS: TIMOR-LESTE",
                "TGO: TOGO",
                "TKL: TOKELAU",
                "TON: TONGA",
                "TTO: TRINIDAD AND TOBAGO",
                "XTR: TROMELIN ISLAND",
                "TUN: TUNISIA",
                "TUR: TURKEY",
                "TKM: TURKMENISTAN",
                "TCA: TURKS AND CAICOS ISLANDS",
                "TUV: TUVALU",
                "UGA: UGANDA",
                "UKR: UKRAINE",
                "ARE: UNITED ARAB EMIRATES",
                "GBR: UNITED KINGDOM",
                "USA: UNITED STATES",
                "URY: URUGUAY",
                "UZB: UZBEKISTAN",
                "VUT: VANUATU",
                "VAT: VATICAN CITY",
                "VEN: VENEZUELA",
                "VNM: VIETNAM",
                "VGB: VIRGIN ISLANDS, BRITISH",
                "WLF: WALLIS AND FUTUNA",
                "XWB: WEST BANK",
                "ESH: WESTERN SAHARA",
                "YEM: YEMEN",
                "ZMB: ZAMBIA",
                "ZWE: ZIMBABWE",
            ],
        },
    },
}
