const basicSummaryFixture = {
  additional_info_url: null,
  additional_info_url_description: null,
  agency_code: null,
  agency_contact_description: null,
  agency_email_address: null,
  agency_email_address_description: null,
  agency_name: null,
  agency_phone_number: null,
  applicant_eligibility_description: null,
  applicant_types: null,
  archive_date: null,
  award_ceiling: null,
  award_floor: null,
  close_date: null,
  close_date_description: null,
  estimated_total_program_funding: null,
  expected_number_of_awards: null,
  fiscal_year: null,
  forecasted_award_date: null,
  forecasted_close_date: null,
  forecasted_close_date_description: null,
  forecasted_post_date: null,
  forecasted_project_start_date: null,
  funding_categories: null,
  funding_category_description: null,
  funding_instruments: null,
  is_cost_sharing: null,
  is_forecast: false, // Adjust according to your needs
  post_date: null,
  summary_description: null,
  // Add any missing required fields here
};

export const basicOpportunityFixture = {
  agency: "Mock Agency",
  category: "Mock Category",
  category_explanation: null,
  created_at: "2020-01-01T00:00:00Z",
  opportunity_assistance_listings: [],
  opportunity_id: 1,
  opportunity_number: "12345",
  opportunity_status: "Open",
  opportunity_title: "Mock Opportunity",
  summary: basicSummaryFixture,
};
