name: Deploy Metabase
run-name: Deploy ${{ inputs.image_tag || 'current image' }} to Metabase ${{ inputs.environment || 'nonprod' }}

on:
  push:
    branches:
      - "main"
    paths:
      - "infra/metabase/**"
      - "infra/modules/**"
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - training
          - grantee1
          - prod
      image_tag:
        description: "Metabase enterprise image tag to deploy (e.g., v1.50.10)"
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        envs: ${{ fromJSON(inputs.environment != null && format('["{0}"]', inputs.environment) || github.ref_name == 'main' && '["staging"]' || '["dev"]') }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: metabase
          environment: ${{ matrix.envs }}

      - name: Deploy Metabase
        run: make release-deploy APP_NAME=metabase ENVIRONMENT=${{ matrix.envs }} IMAGE_TAG=${{ inputs.image_tag }}

  send-slack-notification:
    if: failure() && (github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
    needs: [deploy]
    uses: ./.github/workflows/send-slack-notification.yml
    secrets: inherit
