name: Check CI/CD AWS authentication

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: AWS region
        default: us-east-1
        required: false
      role_to_assume:
        description: ARN of IAM role to assume
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  caller-identity:
    name: Check caller identity
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ inputs.role_to_assume }}
      - run: aws sts get-caller-identity
