name: E2E Tests
run-name: E2E Tests

on:
  workflow_call:
    inputs:
      service_endpoint:
        required: true
        type: string
      app_name:
        required: false
        type: string

jobs:
  e2e:
    name: Run E2E tests (${{ matrix.shard }} of ${{ matrix.total_shards }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Continue running tests to completion even if some shards fail
      matrix:
        shard: [1, 2, 3]
        total_shards: [3] # Github Actions doesn't have a built-in method to get the length of an array

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Run e2e tests (Shard ${{ matrix.shard }}/${{ matrix.total_shards }})
        run: |
            make e2e-test \
                APP_NAME=${{ inputs.app_name }} \
                BASE_URL=${{ inputs.service_endpoint }} \
                CURRENT_SHARD=${{ matrix.shard }} \
                TOTAL_SHARDS=${{ matrix.total_shards }}

      - name: Verify blob report directory after tests
        run: |
          echo "Contents of blob-report directory on host:"
          ls -R ./e2e/blob-report || echo "blob-report directory not found"

      - name: Upload blob report
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-shard-${{ matrix.shard }}
          path: ./e2e/blob-report
          retention-days: 1

  create-report:
    name: Create merged test report
    if: ${{ !cancelled() }}
    needs: e2e
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: lts/*

      - name: Cache Node.js dependencies
        id: cache-node
        uses: actions/cache@v4
        with:
            path: e2e/node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('e2e/package-lock.json') }}

      - name: Install dependencies in ./e2e to be able to run `playwright merge-reports`
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: make e2e-setup-ci

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./e2e/blob-report
          pattern: blob-report-shard-*
          merge-multiple: true

      - name: Verify downloaded artifacts
        run: |
          echo "Contents of ./e2e/blob-report after download:"
          ls -R ./e2e/blob-report

      - name: Merge reports
        run: make e2e-merge-reports

      - name: Verify merged report
        run: |
          echo "Contents of ./e2e/playwright-report after merge:"
          ls -R ./e2e/playwright-report || echo "No report found in ./e2e/playwright-report"

      - name: Upload merged HTML report
        uses: actions/upload-artifact@v4
        with:
            name: e2e-test-report
            path: ./e2e/playwright-report
            retention-days: 7
