name: E2E EXPERIMENNTTT
on:
  push:
    branches:
      - "dschrashun/9179-run-e2e-on-cadences"
  workflow_dispatch:
    inputs:
      api_logs:
        description: "print api logs on failure?"
        default: false
        type: boolean
      playwright_tags:
        description: "pipe separated list of @tags denoting groups of tests to run"
        required: false
        type: string
  workflow_call:
    inputs:
      api_logs:
        description: "print api logs on failure?"
        default: false
        type: boolean
      playwright_tags:
        description: "pipe separated list of @tags denoting groups of tests to run"
        required: false
        type: string
  pull_request:
    paths:
      - ".github/actions/e2e/action.yml"
      - ".github/workflows/**"

env:
  NODE_VERSION: 24
  LOCKFILE_PATH: ./frontend/package-lock.json
  PACKAGE_MANAGER: npm
  NODE_OPTIONS: --dns-result-order=ipv4first

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests-local:
    name: Run Local E2E Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Determine test groups to run
        shell: bash
        run: |
          if [[ $GITHUB_EVENT_NAME = "pull_request" ]]; then
            echo "test_group_tags=@smoke" >> "$GITHUB_ENV"
          elif [[ $GITHUB_EVENT_NAME = "push" ]]; then
            echo "test_group_tags=@core-regression" >> "$GITHUB_ENV"
          else
            echo "test_group_tags=${{ inputs.playwright_tags }}" >> "$GITHUB_ENV"
          fi

      - name: Run E2E tests
        shell: bash
        run: echo "${{ env.test_group_tags }}"
