name: E2E Tests Daily
on:
  schedule:
    # Run every day at (6/7am Eastern) before the start of the workday
    - cron: "0 11 * * *"

jobs:
  daily-e2e-tests-deployed:
    name: Daily E2E tests (staging)
    uses: ./.github/workflows/e2e-staging.yml
    if: always()
    secrets: inherit
    with:
      version: main
      target: staging
      playwright_tags: "@smoke|@core-regression|@full-regression"
  daily-e2e-tests-local:
    name: Daily E2E tests (local)
    uses: ./.github/workflows/ci-frontend-e2e.yml
    if: always()
    secrets: inherit
    with:
      playwright_tags: "@smoke|@core-regression|@full-regression"
