name: E2E Tests Daily (EXPERIMENTTTT)
on:
  workflow_dispatch:
  push:
    branches:
      - "fix-e2e-scheduled-jobs"

jobs:
  daily-e2e-tests-deployed:
    name: Daily E2E tests (staging)
    uses: ./.github/workflows/e2e-staging.yml
    if: always()
    secrets: inherit
    with:
      version: main
      target: staging
      playwright_tags: "@full-regression"
  daily-e2e-tests-local:
    name: Daily E2E tests (local)
    uses: ./.github/workflows/ci-frontend-e2e.yml
    if: always()
    secrets: inherit
    with:
      playwright_tags: "@full-regression"
