name: Lint - Inherit parent metadata

on:
  issues:
    types: [opened]

permissions:
  issues: write

defaults:
  run:
    working-directory: ./.github/linters # ensures that this job runs from the ./linters sub-directory

jobs:
  inherit-parent-metadata:
    name: Run inherit parent milestone and deliverable scripts
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ACCESS }}
      # The number of the GitHub project to inherit the metadata from
      PROJECT_NUMBER: 13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run inherit parent milestone script
        run: |
          ./scripts/inherit-parent-milestone.sh "${{ github.event.issue.html_url }}"

      - name: Run inherit parent deliverable script
        run: |
          ./scripts/inherit-parent-deliverable.sh "${{ github.event.issue.html_url }}" \
            --project "${PROJECT_NUMBER}"
