name: Lint - Bulk inherit parent metadata

on:
  # manual trigger
  workflow_dispatch:
  # trigger on a schedule: Monday-Friday at 1am ET
  schedule:
    - cron: "00 5 * * 1-5"

defaults:
  run:
    working-directory: ./.github/linters # ensures that this job runs from the ./linters sub-directory

jobs:
  run-inherit-metadata:
    name: Run bulk inherit parent metadata
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ACCESS }}
    steps:
      - uses: actions/checkout@v4

      - name: Propagate project metadata from parent issue to sub-issues
        run: |
          ./scripts/bulk-inherit-parent-metadata.sh \
            --org HHS \
            --project 13
