name: Lint - Sprint rollover

on:
  workflow_dispatch: # for manual runs
  schedule:
    # Runs "at 09:00 UTC, every week on Wednesday" (see https://crontab.guru)
    # Sprints are 2 weeks long, but crons don't easily support biweekly schedules
    # and this GitHub action won't move tickets out of the current sprint
    - cron: "0 9 * * 3"

jobs:
  sprint-rollover:
    name: Roll over open tickets
    runs-on: ubuntu-latest

    steps:
      - uses: blombard/move-to-next-iteration@master
        with:
          owner: HHS
          number: 13
          token: ${{ secrets.GH_TOKEN_PROJECT_ACCESS }}
          iteration-field: Sprint
          iteration: last
          new-iteration: current
          excluded-statuses: "Done"
