name: Release Grants Shared Package to PyPi
on:
  workflow_call:

  pull_request: # TODO - remove, just need for testing
    paths:
      - backend/grants_shared/**
      - .github/workflows/publish-grants-shared.yml

defaults:
  run:
    working-directory: ./backend/grants_shared

jobs:
  publish-to-pypi:
    name: Publish grants_shared to PyPi
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: make build

      # TODO - consider format/lint/test checks to be safe?

      - name: Smoke Test (wheel)
        run: |
          project_version =$(sed -n -Egrep '^version' file.toml | head -1 | sed 's/.*= *"\(.*\)"/\1/')
          echo "grants_shared project version is: ${project_version}"
          make docker-cmd args="uv run --rebose --isolated --with dist/rants_shared-${project_version}-py3-none-any.whl tests/grants_shared/smoke_test.py"

      - name: Smoke Test (source distribution)
        run: make smoke-test-gz

      # TODO - add uv publish here

      # - name: Release to PyPi
      #   run: make publish-to-pypi