name: Release Grants Shared Package to PyPi
on:
  workflow_call:

defaults:
  run:
    working-directory: ./backend/grants_shared

jobs:
  publish-to-pypi:
    name: Publish grants_shared to PyPi
    runs-on: ubuntu-22.04
    env:
      UV_PUBLISH_TOKEN: ${{ secrets.GRANTS_SHARED_PYPI_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Init / Build
        run: make init

      - name: Run format check
        run: make format-check

      - name: Run linting
        run: make lint

      - name: Run security linting
        run: make lint-security

      - name: Start tests
        run: make test-coverage

      - name: Get Project Version
        id: get-version
        run: |
          PROJECT_VERSION=$(grep '^version' pyproject.toml | head -1 | sed 's/.*= *"\(.*\)"/\1/')
          echo "grants_shared project version is currently: ${PROJECT_VERSION}"
          echo "project_version=$PROJECT_VERSION" >> "$GITHUB_OUTPUT"

      # Verify we built the package in the right shape to use as a module
      - name: Smoke Test (wheel)
        run: |
          make docker-cmd args="uv run --isolated --with dist/grants_shared-${{steps.get-version.outputs.project_version}}-py3-none-any.whl tests/grants_shared/smoke_test.py"

      - name: Smoke Test (source distribution)
        run: |
          make docker-cmd args="uv run --isolated --with dist/grants_shared-${{steps.get-version.outputs.project_version}}.tar.gz tests/grants_shared/smoke_test.py"

      # This publish relies on trusted publishing which
      # uses a trusted connection between github actions
      # and PyPi to avoid us needing to manage API Keys
      #
      # See the following for more information:
      # * https://docs.astral.sh/uv/guides/integration/github/#publishing-to-pypi
      # * https://docs.pypi.org/trusted-publishers/
      - name: Release to PyPi
        run: |
          make docker-cmd args="uv publish"