CREATE TABLE IF NOT EXISTS schema_version (
    one_row BOOL GENERATED ALWAYS AS (TRUE) STORED,
	version INTEGER NOT NULL,
	t_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	t_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS sv_i1 ON schema_version(one_row);
